
(() => {
'use strict';
const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slides = window.DECK_SLIDES;
const evidence = window.DEMO_EVIDENCE;
const demo = id => evidence.demos.find(x=>x.id===id);
const compare = () => window.COMPARISON_DATA || {};
const B = '../comparison/';
const state = {index:0, packed:false, curated:false, later:false, profile:'lab', regression:'before'};
const acts=[];slides.forEach((s,i)=>{if(s.optional)return;const a=acts[acts.length-1];if(a&&a.name===s.chapter){a.last=i;a.minutes+=s.minutes;}else acts.push({name:s.chapter,first:i,last:i,minutes:s.minutes});});
const firstBackup=slides.findIndex(s=>s.optional&&!s.track);
const firstTechnical=slides.findIndex(s=>s.track==="technical");
const firstProducts=slides.findIndex(s=>s.track==="products");
const productMinutes=slides.filter(s=>s.track==="products").reduce((n,s)=>n+s.minutes,0);
const technicalMinutes=slides.filter(s=>s.track==="technical").reduce((n,s)=>n+s.minutes,0);
const viewButton = (label,path,title,cls='') => '<button class="action '+cls+'" data-view="'+esc(path)+'" data-title="'+esc(title||label)+'">'+label+' ↗</button>';
const comparisonButton = label => viewButton(label,B+'index.html','Prepared same-prompt comparison');
const shell=(s,inside,cls='',stamp='') => '<section class="slide '+cls+'"><span class="eyebrow">'+esc(s.eyebrow||s.chapter)+'</span><h1>'+esc(s.title)+'</h1>'+(s.showSubtitle?'<p class="subtitle">'+esc(s.subtitle)+'</p>':'')+inside+'<div class="stamp">'+esc(s.evidenceLabel||'')+'</div><span class="slide-number">'+String(state.index+1).padStart(2,'0')+'</span></section>';
const scoreStatus=v=>{const t=typeof v==='object'?(v.status??v.passed??v.result):v;return t===true||/^(pass|passed)$/i.test(t)?['PASS','pass']:t===false||/^(fail|failed)$/i.test(t)?['FAIL','fail']:[String(t||'Recorded'),'unknown'];};
const iconPaths={"person":"<circle cx=\"24\" cy=\"14\" r=\"7\"/><path d=\"M9 42v-6a15 15 0 0 1 30 0v6\"/>","terminal":"<rect x=\"5\" y=\"8\" width=\"38\" height=\"32\" rx=\"5\"/><path d=\"m13 19 6 5-6 5m13 0h9\"/>","check":"<path d=\"m8 24 10 10 22-23\"/><path d=\"M41 26v12a5 5 0 0 1-5 5H11a5 5 0 0 1-5-5V12a5 5 0 0 1 5-5h18\"/>","layers":"<path d=\"m24 5 20 10-20 10L4 15Zm-20 19 20 10 20-10M4 34l20 10 20-10\"/>","route":"<circle cx=\"10\" cy=\"9\" r=\"4\"/><circle cx=\"38\" cy=\"39\" r=\"4\"/><path d=\"M10 13v18a8 8 0 0 0 8 8h16M14 9h16a8 8 0 0 1 0 16H18\"/>","book":"<path d=\"M24 11c-6-6-13-6-20-3v31c7-3 14-3 20 3 6-6 13-6 20-3V8c-7-3-14-3-20 3Zm0 0v31\"/>","laptop":"<rect x=\"9\" y=\"7\" width=\"30\" height=\"24\" rx=\"3\"/><path d=\"m9 31-6 9h42l-6-9M19 35h10\"/>","folder":"<path d=\"M5 40V11a4 4 0 0 1 4-4h12l5 6h13a4 4 0 0 1 4 4v23Z\"/>","bulb":"<path d=\"M17 34h14m-14 6h14m-20-21a13 13 0 1 1 24 7c-3 3-4 5-4 8H17c0-3-1-5-4-8a13 13 0 0 1-2-7ZM21 44h6\"/>","handoff":"<path d=\"M4 30h10l8 7h16l6-7-4-3-8 5h-8m-10-2 6-7h9a4 4 0 0 1 0 8h-7M4 26v17m10-2H4\"/><rect x=\"21\" y=\"5\" width=\"15\" height=\"13\" rx=\"2\"/><path d=\"M27 5v6h4V5\"/>","git":"<circle cx=\"12\" cy=\"8\" r=\"4\"/><circle cx=\"36\" cy=\"11\" r=\"4\"/><circle cx=\"12\" cy=\"40\" r=\"4\"/><path d=\"M12 12v24m24-21v7c0 9-24 4-24 12\"/>","compass":"<circle cx=\"24\" cy=\"24\" r=\"20\"/><path d=\"m31 17-4 10-10 4 4-10Z\"/>","file":"<path d=\"M10 4h19l10 10v30H10Zm19 0v10h10M17 22h15M17 29h15M17 36h10\"/>","archive":"<rect x=\"5\" y=\"7\" width=\"38\" height=\"9\" rx=\"2\"/><path d=\"M9 16v26h30V16M19 24h10\"/>","bubble":"<path d=\"M43 7H5v28h9v9l11-9h18ZM13 17h22M13 24h15\"/>","lock":"<rect x=\"9\" y=\"21\" width=\"30\" height=\"23\" rx=\"4\"/><path d=\"M15 21V13a9 9 0 0 1 18 0v8\"/><circle cx=\"24\" cy=\"31\" r=\"2\"/><path d=\"M24 33v5\"/>","scales":"<path d=\"M24 4v38M15 44h18M7 13h34M12 13 4 28h16Zm24 0-8 15h16ZM4 28a8 8 0 0 0 16 0m8 0a8 8 0 0 0 16 0\"/>","clock":"<circle cx=\"24\" cy=\"24\" r=\"20\"/><path d=\"M24 11v14l9 6\"/>","flask":"<path d=\"M17 5h14m-11 0v14L7 39a3 3 0 0 0 3 5h28a3 3 0 0 0 3-5L28 19V5M13 30h22\"/>","building":"<path d=\"M10 44V5h28v39M5 44h38M19 44V32h10v12M17 12h3m8 0h3m-14 7h3m8 0h3m-14 7h3m8 0h3\"/>"};
const icon=name=>'<svg class="scene-icon" viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(iconPaths[name]||iconPaths.file)+'</svg>';
// nine steps, the two approval seams (the second is the code line) and the gap before CAPTURE. CSS reads it as --cl; the panel notch is computed from it.
const CL=[133,6,133,6,133,33,133,6,133,33,133,6,133,6,133,13,133]; // sums to 1306 = 1440 stage − 2px border − 2×66px padding
const clCentre=n=>CL.slice(0,2*n).reduce((a,b)=>a+b,0)+CL[2*n]/2;
const bandOf=n=>n<5?'cl-pre':n<8?'cl-code':'cl-keep';
// [name, slip line 1, slip line 2, leaves behind, where you come in, skip it and…] — wording follows docs/the-cycle.md at 275a354; gates are instructions, never locks.
const PHASES=[
['SENSE','Situation','report','A situation report, a first guess at the size — and a suggested route.','Nowhere yet. It only reads, and it never blocks.','Every later step is sized wrong. Half-finished work gets quietly revived — or ignored.'],
['SCOPE','Sized','request','The size it settled on, the reading you chose, and any change of route.','One question at most — and only when the request could be small or huge. Otherwise silent.','Small or huge? Nobody settles it, and the plan cannot pick its depth.'],
['DEFINE','Approved','design','An approved design, not a draft — what every later step is measured against.','You approve the design. The agent is told to stop until you do.','Nothing later can be checked against anything.'],
['DISCOVER','Existing','decisions','A report of what already exists: earlier decisions, lessons, patterns to reuse.','Nowhere. It only reads; it changes nothing.','The plan flies blind — and reinvents or contradicts what was already decided.'],
['PLAN','Plan + spec','+ brief','Three files: small checkable tasks, what “done” means, and a brief a fresh session can start from.','You approve the plan. It is told never to start the build on its own.','The build runs on a plan nobody wrote or reviewed.'],
['BUILD','Small','commits','Code in small commits. Each task gets a fresh worker, then two checks: against the spec, then for quality.','Before it starts you confirm a task count and a token estimate, labelled UNCALIBRATED.','Nothing gets built.'],
['REVIEW','Review','reports','Review reports from three passes: against the spec, for code quality, against team standards.','Only if it finds something serious: the agent is told not to ship.','Unreviewed code reaches shipping with no signal at all.'],
['SHIP','Pull','request','A pull request, release notes and an audit-log entry.','A direct push to the main branch is never the default. Strict team rules can stop it here.','No deploy check, no way back, no audit trail.'],
['CAPTURE','Lessons +','decisions','Lessons from any correction, a decision record, and updated working notes: the handoff.','Nowhere. But this is what a later DISCOVER can find.','Continuity is lost. The next session works it all out again.']
];
// The four requests were run through lib/orientator-routing.sh + lib/scale-estimator.sh at 275a354 (../verification/cycle-routes-source-manifest.json).
// Rails, counts, aria-labels and the phone run list are all derived from run[], so the picture and the words cannot disagree.
const ALL9=[0,1,2,3,4,5,6,7,8];
const YOU_CONFIRM=['YOU','<code>Proceed? [Y/n/edit]</code>','you see what runs, what is skipped, and a token estimate'];
const KEYWORD='a keyword rule · not a judgement';
const ROUTES=[
{req:['','Fix',' the typo on the export button.'],tag:'<b>hotfix</b>',label:'hotfix',run:[0,5,6,7],chips:[['SENSE SPOTS A WORD','“fix” → a fix',KEYWORD],['SUGGESTS','<code>hotfix</code>','known bug · clear fix'],YOU_CONFIRM]},
{req:['','Explore',' how tenant isolation works.'],tag:'<b>research-dive</b>',label:'research-dive',run:[0,2,3],chips:[['SENSE SPOTS A WORD','“explore” → research',KEYWORD],['SUGGESTS','<code>research-dive</code>','understand first · no code on this route'],YOU_CONFIRM]},
{req:['','Add',' a date-range filter to the dashboard.'],tag:'<b>the full cycle</b> · <em>small → flat plan</em>',label:'the full cycle, sized small, so the plan stays a flat list',run:ALL9,chips:[['SENSE SPOTS A WORD','“add” → a build',KEYWORD],['SUGGESTS','the full cycle','all nine · sized small, so the plan stays a flat list'],YOU_CONFIRM]},
{req:['','Deploy',' the support dashboard to Azure.'],warn:true,ask:1,tag:'<s>start at SHIP</s><i>→</i><u>one question</u><i>→</i><b>the full cycle</b>',label:'first guess was to start at SHIP; after one question, re-routed to the full cycle',run:ALL9,chips:[['SENSE SPOTS A WORD','“deploy” → ready to ship','a keyword rule · “confidence: high” — and wrong here'],['SCOPE ASKS YOU ONCE','Static page — or landing zone?','size unclear · treated as large until you answer'],['YOU','“Landing zone.”','large + nothing built yet → full cycle from DEFINE. Small → SHIP stands.']]}
];
const SKIP='<svg class="rt-skip" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><circle cx="12" cy="12" r="8"/><path d="M6.5 17.5 17.5 6.5"/></svg>';
const templates = {
handoff:s=>shell(s,'<div class="handoff-grid">'+[['layers','Lintel','The full harness','Open source · available now'],['building','Pack #1','MS Employee in CAIP','Distribution link to follow'],['terminal','Lintel Core','Build for your own case','Planned shell · link to follow'],['flask','Lintel Benchmark','Measure what earns its place','Evaluation package · link to follow']].map(([i,h,p,n],k)=>'<article><span class="handoff-no">0'+(k+1)+'</span>'+icon(i)+'<h2>'+h+'</h2><p>'+p+'</p><small>'+n+'</small></article>').join('')+'</div><div class="handoff-core"><span>THE CORE IDEA</span><p>A small, explicit workflow.<br>Inside the customer’s existing coding app.</p><small>When the case does not need a hosted agent or a dedicated app.</small></div><div class="actions"><button class="action" data-product="product-family">Meet the product family →</button><a class="action" href="../index.html#takeaway">Get the materials ↗</a></div>','handoff-slide'), // LINTEL_HANDOFF

storage:s=>shell(s,'<div class="storage-map"><div class="storage-machine"><div class="zone-label">'+icon('laptop')+' YOUR MACHINE</div><div class="storage-home"><span class="zone-kicker">GLOBAL · ~/.lintel/</span><h2>Your profile & packs</h2><p>Reusable across projects</p></div><div class="storage-host"><span class="zone-kicker">TOOL-OWNED</span><h2>Your coding app</h2><p>Settings · tools · permissions</p></div></div><div class="storage-connector"><span>reads &<br>applies</span><b>→</b></div><div class="storage-repo"><div class="zone-label">'+icon('folder')+' YOUR PROJECT REPO</div><div class="storage-committed"><span class="zone-kicker">COMMITTED · .claude/</span><div class="record-icons"><span>'+icon('route')+'Plans</span><span>'+icon('book')+'Decisions</span><span>'+icon('bulb')+'Lessons</span><span>'+icon('handoff')+'Handoffs</span></div><div class="git-travel">'+icon('git')+' Git → teammate → next session</div></div><div class="storage-runtime"><strong>.claude/runtime/</strong><span>Temporary state · Git-ignored</span><b>stays here</b></div></div></div><div class="storage-bottom"><span>The <code>.claude/</code> name is shared storage — it does not require Claude Code.</span>'+viewButton('Exact paths','field-guide.html#storage','What lives where')+'</div>','storage'),
definition:s=>shell(s,'<div class="intro-equation"><div class="intro-human">'+icon('person')+'<span>YOU</span><h2>The intent.</h2></div><b class="flow-arrow">→</b><div class="intro-agent">'+icon('terminal')+'<span>YOUR CODING AGENT</span><h2>The execution.</h2><div class="lintel-insert">'+icon('layers')+'<strong>Lintel</strong><span>Method + memory</span></div></div><b class="flow-arrow">→</b><div class="intro-output">'+icon('check')+'<span>THE RESULT</span><h2>Work you<br>can inspect.</h2></div></div><div class="quiet-line">Open source · Public beta · Your existing coding tools</div>','definition'),
primer:s=>{
const later=state.later;
const rows=later?[['file','Instructions','',''],['bubble','“One dashboard. No platform rewrite.”','crowded out','lost'],['terminal','41 tool results','',''],['folder','23 files read','',''],['clock','3 hours of conversation','compacted','']]:[['file','Instructions','',''],['bubble','“One dashboard. No platform rewrite.”','agreed 09:12','agreed'],['person','Your request','',''],['folder','2 files read','','']];
return shell(s,'<div class="primer"><div class="primer-terms">'+[['AGENT','Reads the repo. Edits files. Runs commands.'],['CONTEXT','What it can see right now. Finite.'],['SESSION','One working conversation. Then it ends.']].map(([t,d])=>'<div class="primer-term"><b>'+t+'</b><p>'+d+'</p></div>').join('')+'<button class="action primary" data-action="later" aria-pressed="'+later+'">'+(later?'↶ Back to 09:12':'Three hours later →')+'</button></div><div class="primer-window '+(later?'full':'')+'"><div class="primer-bar"><span>CONTEXT WINDOW</span><i><u></u></i><em>'+(later?'12:12 · nearly full':'09:12 · plenty of room')+'</em></div><div class="primer-rows">'+rows.map(([i,t,tag,c])=>'<div class="primer-row '+c+'">'+icon(i)+'<span>'+t+'</span>'+(tag?'<small>'+tag+'</small>':'')+'</div>').join('')+'</div><div class="primer-after"><div class="gone">New session → empty window</div><div class="stays">'+icon('folder')+'Files in the repo → still there</div></div></div></div>','primer-slide');
},
toolkit:s=>shell(s,'<div class="kit-triptych">'+[['route','A playbook','How to plan, build and review.','Instructions · skills · roles'],['book','Team memory','What we decided — and why.','Packs · decisions · lessons'],['check','Real checks','Scripts that fail when it is wrong.','Local helpers · verification']].map(([i,h,plain,p])=>'<article>'+icon(i)+'<h2>'+h+'</h2><p class="kit-plain">'+plain+'</p><p class="kit-terms">'+p+'</p></article>').join('')+'</div><div class="quiet-line">Load what the work needs.</div>','toolkit'),
clients:s=>shell(s,'<div class="client-hub">'+icon('layers')+'<span>ONE SHARED METHOD</span></div><div class="client-gallery">'+['Claude Code','Codex <small>CLI / App</small>','Cursor','GitHub Copilot <small>CLI</small>','Factory Droid'].map(n=>'<div>'+icon('terminal')+'<strong>'+n+'</strong></div>').join('')+'</div><div class="client-other"><p><b>Workflow files</b> Gemini CLI · OpenCode</p><p><b>Best effort</b> Cline · Continue · Aider</p></div><div class="client-boundary"><span>Copilot repo kit: VS Code · CLI · cloud agent</span><strong>Lintel hooks: Claude Code only</strong></div><div class="actions">'+viewButton('Declared support matrix','field-guide.html#support','Lintel field guide · declared integration matrix')+'</div>','clients'),
cyclemap:s=>{
// The default (DEFINE) already tells the story; a click only moves the highlight, the notch and the three panel cells.
// DOM order is the phone order; desktop placement is explicit. Buttons hold phrasing content only, and the panel uses b/p
// (legacy .phase / .phase-detail span rules in style.css would restyle anything else).
const sel=state.cyclePhase??2,P=PHASES[sel];
const step=n=>'<button class="cl-step '+bandOf(n)+(sel===n?' is-on':'')+'" data-phase="'+n+'" aria-pressed="'+(sel===n)+'" style="grid-column:'+(2*n+1)+'"><span class="cl-num">0'+(n+1)+'</span><b>'+PHASES[n][0]+'</b><span class="cl-art'+(n===3||n===8?' kept':'')+'">'+PHASES[n][1]+' <br>'+PHASES[n][2]+'</span></button>';
const gate=(k,col,text)=>'<div class="cl-gate '+k+'" style="grid-column:'+col+'"><i>'+icon('person')+'</i><span>'+text+'</span></div>';
const strip='<p class="sr-only">The opening conversation: one dashboard was agreed at 09:12. Three hours of building later, at 12:12, the agent had designed a new platform. That is where the misunderstanding was found.</p><div class="cl-grid cl-strip" aria-hidden="true"><span class="cl-kick">WITHOUT A WRITTEN DESIGN</span><span class="cl-tab red">YOU FOUND OUT HERE</span><div class="cl-a1">“One dashboard.”<i>09:12</i></div><div class="cl-a2"><span>THREE HOURS OF WORK</span></div><div class="cl-a3">“…a new platform.”<i>12:12</i></div></div>';
const map='<div class="cl-grid cl-map"><div class="cl-band cl-pre">BEFORE ANY CODE · 5 OF 9</div>'+[0,1,2].map(step).join('')+gate('a',6,'YOU APPROVE THE DESIGN · you can find out here')+[3,4].map(step).join('')+gate('b',10,'CODE STARTS BELOW · YOU APPROVE THE PLAN + A TOKEN ESTIMATE')+'<div class="cl-band cl-code">CODE</div>'+[5,6,7].map(step).join('')+'<div class="cl-band cl-keep">REMEMBER</div>'+step(8)+'<span class="cl-tab lime" aria-hidden="true">YOU CAN FIND OUT HERE</span><span class="cl-flag a" aria-hidden="true">YOU APPROVE THE DESIGN</span><span class="cl-flag b" aria-hidden="true">YOU APPROVE THE PLAN + A TOKEN ESTIMATE</span></div>';
const cell=(k,cls,body,you)=>'<div class="cl-cell '+cls+'"><b class="cl-k">'+(you?icon('person'):'')+k+'</b><p>'+body+'</p></div>';
return shell(s,strip+map+'<div class="phase-detail" aria-live="polite" style="--notch:'+Math.round(clCentre(sel))+'px">'+cell('0'+(sel+1)+' '+P[0]+' · LEAVES BEHIND','leaves',P[3])+cell('WHERE YOU COME IN','you',P[4],[2,4,5].includes(sel))+cell('SKIP IT AND…','skip',P[5])+'</div>','cyclescreen');
},
routes:s=>{
// Same nine positions as the cycle screen. The picture (count, names, four rails, code line) never changes on a click;
// only the row highlight and the band below do, so the Deploy row is always shown in its final, truthful state.
const sel=state.route??0,R=ROUTES[sel];
const names='<div class="cl-grid rt-names" aria-hidden="true">'+PHASES.map((p,n)=>'<span class="'+bandOf(n)+'" style="grid-column:'+(2*n+1)+'">'+p[0]+'</span>').join('')+'<i class="cl-seam"></i></div>';
const rail=r=>'<span class="cl-grid rt-rail" aria-hidden="true">'+PHASES.map((p,n)=>{const on=r.run.includes(n);return '<span class="rt-block '+(on?'is-on '+bandOf(n)+(r.ask===n?' is-ask':''):'is-off')+'" style="grid-column:'+(2*n+1)+'">'+(on?(r.ask===n?'?':''):SKIP)+'</span>';}).join('')+'<i class="cl-seam"></i><i class="rt-you" style="grid-column:'+(2*(r.run.includes(1)?1:0)+2)+'">'+icon('person')+'</i></span>';
const row=(r,n)=>{const ran=r.run.map(i=>PHASES[i][0]),skipped=PHASES.map(p=>p[0]).filter(x=>!ran.includes(x));return '<button class="rt-row'+(sel===n?' is-on':'')+(r.warn?' is-warn':'')+'" data-route="'+n+'" aria-pressed="'+(sel===n)+'" aria-label="'+esc(r.req.join('')+' Route: '+r.label+'. Runs: '+ran.join(', ')+'.'+(skipped.length?' Skipped: '+skipped.join(', ')+'.':''))+'"><span class="rt-line"><span class="rt-req">“'+r.req[0]+'<mark class="rt-m">'+r.req[1]+'</mark>'+r.req[2]+'”</span><span class="rt-tag">'+r.tag+' · '+r.run.length+' of 9</span></span>'+rail(r)+'<span class="rt-runlist">'+ran.join(' → ')+'</span></button>';};
const chip=(c,i)=>'<div class="rt-chip c'+i+(i===1&&R.ask!==undefined?' is-ask':'')+'"><b class="rt-k">'+icon(i===0?'compass':i===2?'person':R.ask!==undefined?'bubble':'route')+c[0]+'</b><p class="rt-main">'+c[1]+'</p><p class="rt-sub">'+c[2]+'</p></div>';
return shell(s,'<div class="rt-count" aria-hidden="true"><div><b>'+ROUTES[0].run.length+'</b><span> of 9</span></div><p>SENSE read one word: “<em>fix</em>”</p></div>'+names+'<div class="rt-rows">'+ROUTES.map(row).join('')+'</div><div class="rt-band" aria-live="polite">'+chip(R.chips[0],0)+'<i class="rt-arrow">→</i>'+chip(R.chips[1],1)+'<i class="rt-arrow">→</i>'+chip(R.chips[2],2)+'</div>','routes-slide');
},
firstsession:s=>shell(s,'<div class="endpoint-example"><div class="endpoint-request"><span class="tiny">ONE REQUEST · NEW BEHAVIOUR, SO IT STARTS WITH A PLAN</span><blockquote>“Add a health endpoint<br>and a focused test.”</blockquote></div><div class="endpoint-result"><div class="endpoint-status"><span>GET /health</span><strong>200 OK</strong></div><pre>{ "status": "ok" }</pre><div class="endpoint-test">'+icon('check')+' Acceptance check passes</div></div></div><div class="receipt-path"><span>Agreed plan</span><b>→</b><span>Code + test</span><b>→</b><span>Useful handoff</span></div>','firstsession'),
hook:s=>shell(s,'<div class="ghost-time">03:00:00 later</div><div class="poll">Quick show of hands. Remote participants, you too.</div><div class="chat-stack"><div class="chat"><div class="who"><span>YOU</span><span>09:12</span></div>We agreed: one dashboard.<br>No platform rewrite.</div><div class="chat"><div class="who"><span>AGENT</span><span>12:12</span></div>Great news. I’ve designed<br><span class="new">a new platform.</span></div></div>','hook','Illustrative conversation. Painfully familiar energy.'),
guild:s=>shell(s,'<div class="ring" aria-hidden="true"></div><div class="guild-lineup"><div class="guild-item"><div class="name">MDASH</div></div><div class="guild-item"><div class="name">AGT</div></div><div class="guild-item"><div class="name accent">Lintel</div></div></div><div class="smallprint">Different tools. Different jobs.</div>','guild'),
title:s=>shell(s,'<ol class="promise">'+['Why agents lose the plot','A kit called Lintel — and the method underneath','An honest A/B test','What is worth adopting'].map((t,i)=>'<li><b>0'+(i+1)+'</b>'+t+'</li>').join('')+'</ol><div class="speaker"><strong>Johannes Åkerman</strong><br><span>THE LINTEL FIELD GUIDE<br>DEVELOPERS + ARCHITECTS · LEVEL 200–300</span></div>','title-slide','A personal engineering journey. A set of ideas to test.'),
drift:s=>shell(s,'<div class="drift-labels"><span>Context loses signal</span><span>The goal drifts</span><span>The handoff breaks</span></div>','drift','A stopped agent may also be hitting a tool, permission or budget boundary. Diagnose before prescribing.'),
journey:s=>shell(s,'<div class="journey-path">'+[['01','Better prompts','bubble','My head'],['02','Reusable habits','route','My clipboard'],['03','A durable method','book','The repo']].map(([n,h,i,w])=>'<article class="journey-step">'+icon(i)+'<div class="n">'+n+'</div><h2>'+h+'</h2><p class="lives"><span>LIVES IN</span>'+w+'</p></article>').join('')+'</div>','journey'),
triad:s=>shell(s,'<div class="triad-grid"><article>'+icon('compass')+'<div class="big violet">WHAT</div><p>Outcome + boundaries</p></article><article>'+icon('route')+'<div class="big accent">HOW</div><p>Work + verification</p></article><article>'+icon('bulb')+'<div class="big violet">WHY</div><p>Decisions + rationale</p></article></div><div class="compound-bar"><b>↻</b><span>Keep what the next task needs.</span></div>','triad'),
architecture:s=>shell(s,'<div class="body"><div class="layer"><strong>THE CLIENT</strong><div class="chips"><span>CLI</span><span>/</span><span>Editor</span><span>/</span><span>Coding desktop app</span></div></div><div class="layer core"><strong>LINTEL</strong><div>Shared spine + team/project pack<br>Skills · roles · decisions · lessons · handoffs · helpers</div></div><div class="layer"><strong>THE PLATFORM</strong><div>Identity · permissions · CI · policy · deployment gates</div></div></div><p class="caveat">Portable method ≠ identical host features.</p>','architecture','Client adapters differ. Hook registration and actual enforcement must be verified per host.'),
reuse:s=>shell(s,'<div class="repo-grid">'+['Workshop','Customer demo','Internal tool'].map((x,i)=>'<article class="repo-card"><div class="repo-name">'+x+'</div><div class="mini-dash">'+[33,65,42,88,72].map(h=>'<i style="height:'+h+'%"></i>').join('')+'</div><div class="repeat">Filters. Empty states. Export.<br>Explain it all again.</div><div class="skill-call">Same quality checks.<br>This project’s requirements.</div></article>').join('')+'</div><div class="reuse-bottom"><button class="action primary" data-action="reuse">'+(state.packed?'↶ Show the repetition':'Package the pattern →')+'</button><div class="reuse-result">'+(state.packed?icon('layers')+'<span>One reusable skill.<br><strong>Three independent projects.</strong></span>':'<span class="tiny">Copy. Paste. Déjà vu.</span>')+'</div></div>','reuse'+(state.packed?' packed':'')),
context:s=>shell(s,'<div class="curator-art" role="img" aria-label="A context curator selecting useful cards from a pile of old papers"></div><div class="context-content"><div class="context-stack">'+[['Approved scope','keep'],['Current task','keep'],['Relevant decision','keep'],['Matching lesson','keep'],['Stale plan','drop'],['Chat dump','drop']].map(([a,b])=>'<div class="context-item '+b+'">'+icon(b==='keep'?'file':'archive')+a+'</div>').join('')+'</div><button class="action primary" data-action="context">'+(state.curated?'↶ Open the junk drawer':'Curate the context →')+'</button><p class="context-takeaway">'+(state.curated?'Keep the signal. Keep the source.':'Somewhere in here is the answer.')+'</p></div>','context'+(state.curated?' curated':'')),
granularity:s=>shell(s,'<div class="work-package"><div class="package-heading"><strong>Consistent filters + export</strong><span class="tag lime">ONE REVIEWABLE OUTCOME</span></div><div class="tasks">'+[['T01','Define “active”','compass'],['T02','Share one dataset','layers'],['T03','Check the export','check']].map(([n,h,i])=>'<article class="task">'+icon(i)+'<span>'+n+'</span><h3>'+h+'</h3></article>').join('')+'</div><div class="package-acceptance">Acceptance → the screen and the CSV show the same selection.</div></div><div class="quiet-line">Short tasks inside a coherent work package.</div>','granularity'),
experiment:s=>shell(s,'<div class="kitchen-art" role="img" aria-label="Two equally well prepared dashboard dishes"></div><div class="dish-labels"><span>Competent baseline</span><span>+ Lintel workflow</span></div><div class="recipe-label">Same prompt. Same knowledge. Same checks.</div>','experiment'),
brief:s=>shell(s,'<div class="prompt-window"><div class="window-bar"><i></i><i></i><i></i><span>THE SHARED REQUEST · ABBREVIATED</span></div><div class="prompt-text">A support dashboard with <mark>active tickets</mark>,<br>a <mark>customer</mark> filter and <mark>CSV export</mark>.<br>Make it <mark>ready for a pilot</mark>.</div></div><div class="actions">'+viewButton('Exact shared prompt',B+'readers/shared-prompt.html','The exact implementation prompt')+'</div>','brief'),
results:s=>shell(s,'<div class="result-grid">'+[['baseline','without-lintel','Competent baseline','Standard project instructions'],['lintel','with-lintel','With Lintel','Same starter + workflow context']].map(([key,path,title,sub])=>'<article class="result-card"><div class="result-preview"><img src="../comparison/screenshots/'+path+'.png" alt="Screenshot of the actual prepared '+title+' dashboard" onerror="this.style.display=\'none\';this.nextElementSibling.hidden=false"><div class="fallback-ui" hidden><div class="fhead"></div><div class="fstats"><i></i><i></i><i></i></div><div class="fbars"><i></i><i></i><i></i><i></i><i></i></div></div></div><div class="result-copy"><div><h2>'+title+'</h2><p>'+sub+'</p></div>'+viewButton('Open app',B+path+'/index.html',title,'primary')+'</div></article>').join('')+'</div><div class="common-actions"><span><b>01</b> Change the customer</span><span><b>02</b> Set a date range</span><span><b>03</b> Inspect the export</span></div><div class="actions" style="margin-top:23px">'+comparisonButton('Open comparison desk')+'</div>','results','Prepared outputs are frozen for the demonstration. Inspect both strengths and failures.'),
questions:s=>{
const choices=[['“Active”','What counts as active?','New + Investigating','KPI + filter assertion'],['Dates','Which day owns this ticket?','UTC, including offsets','Boundary fixture'],['Export','What leaves in the CSV?','The same filtered selection','Export content check']];
const i=state.question??0,q=choices[i];
return shell(s,'<div class="question-selector">'+choices.map((x,n)=>'<button data-question="'+n+'" class="'+(n===i?'selected':'')+'">'+x[0]+'</button>').join('')+'</div><div class="question-trace"><div>'+icon('bubble')+'<span>QUESTION</span><h2>'+q[1]+'</h2></div><b>→</b><div>'+icon('bulb')+'<span>DECISION</span><h2>'+q[2]+'</h2></div><b>→</b><div>'+icon('check')+'<span>CHECK</span><h2>'+q[3]+'</h2></div></div><div class="actions">'+viewButton('Baseline questions',B+'readers/baseline-questions.html','Baseline · actual questions')+viewButton('Lintel questions',B+'readers/lintel-questions.html','Lintel · actual questions')+'</div>','questions');
},
plans:s=>shell(s,'<div class="plan-shape">'+[['REQUIREMENT','Export this selection.','compass'],['DECISION','One filtered dataset.','bulb'],['TASK','Connect every view.','route'],['EVIDENCE','CSV matches screen.','check']].map(([h,p,i])=>'<article class="plan-node">'+icon(i)+'<b>'+h+'</b><p>'+p+'</p></article>').join('')+'</div><div class="actions">'+viewButton('Baseline plan',B+'readers/baseline-plan.html','Baseline · actual plan')+viewButton('Lintel plan',B+'readers/lintel-plan.html','Lintel · actual plan')+'</div>','plans'),
scoreboard:s=>{
const checks=compare().checks||[];
const rows=checks.slice(0,3).map(c=>{const a=scoreStatus(c.baseline),b=scoreStatus(c.lintel);return '<tr><td>'+esc(c.title||c.id)+'</td><td class="'+a[1]+'">'+esc(a[0])+'</td><td class="'+b[1]+'">'+esc(b[0])+'</td></tr>';}).join('');
return shell(s,'<table class="score-table"><thead><tr><th>COMMON CHECK</th><th>BASELINE</th><th>WITH LINTEL</th></tr></thead><tbody>'+rows+'</tbody></table><div class="score-result">14 / 14 <span>in both builds</span></div><div class="actions">'+comparisonButton('All 14 checks + evidence')+'</div>','scoreboard');
},
causal:s=>shell(s,'<div class="tie-score"><div><span>COMPETENT BASELINE</span><strong>14 <em>/14</em></strong><small>common checks passed</small></div><div><span>WITH LINTEL METHOD</span><strong>14 <em>/14</em></strong><small>common checks passed</small></div></div><div class="inference">More structure. More overhead.<br><strong>A better handoff? That is the next test.</strong></div><div class="actions">'+viewButton('Baseline handoff',B+'readers/baseline-handoff.html','Baseline · actual handoff')+viewButton('Lintel handoff',B+'readers/lintel-handoff.html','Lintel · actual handoff')+'</div>','causal'),
profile:s=>{
const p=demo('profile').data[state.profile].resolved_fields;
return shell(s,'<div class="profile-wrap"><div class="profile-switch"><button data-profile="lab" class="'+(state.profile==='lab'?'selected':'')+'">'+icon('flask')+'Lab</button><button data-profile="customer" class="'+(state.profile==='customer'?'selected':'')+'">'+icon('building')+'Customer pilot</button></div><div class="contract">'+[['Identity design','demo_policy.identity'],['Network design','demo_policy.network'],['Required evidence','demo_policy.evidence']].map(([label,key])=>'<div class="contract-row"><span>'+label+'</span><b>'+esc(p[key])+'</b></div>').join('')+'</div></div><div class="proof-label">Real resolver output → prepared presentation consumer</div>','profile');
},
cold:s=>shell(s,'<div class="handoff-art" role="img" aria-label="An engineer handing a compact project case to the next worker"></div><div class="cold-proof"><div class="cold-header">'+icon('git')+' FRESH LOCAL CLONE</div><div class="cold-pointers">'+['Spec','Plan','Tasks','Handoff'].map(t=>'<div>'+icon('file')+t+'</div>').join('')+'</div><div class="next-task"><span>NEXT / T002</span>Reproduce the tenant leak.<br>Verify the fix.</div><div class="runtime-gone">Ignored runtime absent. Committed map intact.</div>'+viewButton('Inspect saved proof','../web/index.html#continuity','Cold handoff · saved helper evidence')+'</div>','cold'),
regression:s=>{
const data=demo('learning').data;const mode=state.regression;const result=mode==='regression'?data.regression_control:data[mode];
const tests=(result?.tests||[]).map(t=>'<div class="test-row"><span>'+esc(t.name)+'</span><strong class="'+(t.passed?'pass':'fail')+'">'+(t.passed?'PASS':'FAIL')+'</strong></div>').join('');
return shell(s,'<div class="mode-switch">'+[['before','1 · Before'],['after','2 · Fixed'],['regression','3 · Reintroduce bug']].map(([key,title])=>'<button data-regression="'+key+'" class="'+(mode===key?'selected':'')+'">'+title+'</button>').join('')+'</div><div class="test-layout"><pre>return next((row for row in DOCUMENTS\n  if row["id"] == document_id'+(mode==='after'?'\n  <span class="code-hot">and row["tenant"] == caller_tenant</span>':'')+'\n), None)</pre><div>'+tests+'</div></div><div class="retrieval">↻ The matching lesson is retrieved. Superseded and unrelated lessons stay out.</div>','regression','Actual saved test executions on prepared Python variants. Caller identity is trusted test input, not production authentication.');
},
compound:s=>shell(s,'<div class="compound-artifacts">'+[['bulb','LESSON','Recall'],['book','DECISION','Explain'],['layers','SKILL','Repeat'],['check','TEST','Detect']].map(([i,t,v])=>'<article class="memory-card">'+icon(i)+'<b>'+t+'</b><p>'+v+'</p></article>').join('')+'</div>','compound'),
enforcement:s=>shell(s,'<div class="lock-comparison"><article><div class="paper-rule">'+icon('file')+'<span>“Use least privilege.”</span></div><h2>Instruction</h2><p>Describes the boundary.</p></article><div class="lock-not-equal">≠</div><article><div class="platform-lock">'+icon('lock')+'</div><h2>Enforced control</h2><p>Permissions · CI · platform policy</p></article></div>','enforcement'),
knowledge:s=>shell(s,'<div class="decision-scene"><div class="meeting-chairs" aria-hidden="true">'+icon('person')+icon('person')+icon('person')+'</div><div class="decision-card"><span>ARCHITECTURE DECISION RECORD</span><h2>We rejected option B.</h2><p>Reason: the agreed data boundary.</p><div>Now the next session can know why.</div></div></div>','knowledge'),
smallcore:s=>shell(s,'<div class="rent-scene"><div class="rent-receipt"><span>THE SMALL DEFAULT</span><div>Intent</div><div>Relevant context</div><div>Next action</div><div>Evidence</div><strong>Less ceremony. Clearer work.</strong></div><div class="rent-choice">'+icon('scales')+'<p>Depth follows risk.</p><span>A button label ≠ a tenant boundary.</span></div></div>','smallcore'),
vibe:s=>shell(s,'<div class="route"><span>'+icon('bubble')+'Describe it</span><b>→</b><span>'+icon('compass')+'Resolve it</span><b>→</b><span>'+icon('terminal')+'Build a slice</span><b>→</b><span>'+icon('check')+'Verify it</span></div><div class="return-address">'+icon('handoff')+'Return to: the agreed intent</div>','vibe'),
team:s=>shell(s,'<div class="roles">'+[['terminal','DEMO BUILDER','A repeatable demo.','“Can I show why it works?”'],['compass','ARCHITECT','A defensible design.','“Why this trade-off?”'],['check','CUSTOMER DEVELOPER','A verifiable first slice.','“What does done look like?”']].map(([i,r,h,q])=>'<article class="role">'+icon(i)+'<div class="role-name">'+r+'</div><h2>'+h+'</h2><div class="question">'+q+'</div></article>').join('')+'</div>','team'),
pilot:s=>shell(s,'<div class="pilot-experiment"><div class="pilot-size"><span>START WITH</span><strong>1</strong><p>recurring workflow</p></div><div class="pilot-measure"><div>'+icon('clock')+'Time to accepted change</div><div>'+icon('bubble')+'Human interventions</div><div>'+icon('check')+'Defects + recovery</div><div>'+icon('scales')+'Total cost + overhead</div></div></div><div class="pilot-decision"><span>Keep</span><span>Change</span><span>Stop</span><b>Let the evidence decide.</b></div>','pilot'),
discussion:s=>shell(s,'<div class="discussion-cards"><span>One task.</span><span>One recurring mistake.</span><span>What should remember it?</span></div><div class="teams">'+icon('bubble')+' Remote participants first.</div>','discussion'),
close:s=>shell(s,'<div class="recap">'+[['The same explanation','Plan + handoff'],['The same decision','Decision record'],['The same mistake','Lesson + test']].map(([a,b])=>'<div><span>'+a+'</span><b>→</b><strong>'+b+'</strong></div>').join('')+'</div><div class="loop">Make the useful part reusable.</div><div class="signature">JOHANNES ÅKERMAN · <span class="repo">github.com/jokerman89/lintel</span></div>','close'),
swarm:s=>shell(s,'<div class="swarm-map"><div class="swarm-node accent">Coordinator<small>One authoritative task map<br>Dependencies + ownership</small></div><div class="worker-stack"><div class="swarm-node">UI lane<small>Isolated scope + attributable changes</small></div><div class="swarm-node">API lane<small>Isolated scope + attributable changes</small></div><div class="swarm-node">Evidence lane<small>Independent verification</small></div></div><div class="swarm-node accent">Integration review<small>Reconciled result<br>Evidence before completion</small></div></div><div class="owner">No safe isolation? Replay the same briefs serially.</div>','swarm','Optional topology illustration. This screen does not execute a swarm.'),
resources:s=>shell(s,'<div class="resource-links">'+comparisonButton('Prepared A/B comparison')+viewButton('Helper proof explorer','../web/index.html','Profiles, cold handoff and learning')+viewButton('English speaker script','../presenter/speaker-script.html','Full English script')+viewButton('Timed run of show','../presenter/run-of-show.html','50-minute run of show')+viewButton('Source notes','../presenter/sources.html','Evidence and sources')+viewButton('Demo protocol',B+'readers/protocol.html','Comparison protocol')+'</div><div class="source-links"><a href="../downloads/lintel-techshots-offline.zip">Download the web presentation</a><a href="../START-HERE.html">Package home</a></div>','resources','Controls: ← / → navigate · N notes · O overview · F fullscreen · Escape closes overlays.')
};
Object.assign(templates, window.LINTEL_OPENING({shell, icon, state}));
Object.assign(templates, window.LINTEL_TECHNICAL({shell,icon,state,viewButton}));
Object.assign(templates, window.LINTEL_PRODUCTS({shell,icon,state,viewButton}));
let lastRendered=-1;
function render(){
const s=slides[state.index];$('#stage').innerHTML=(templates[s.type]||templates.triad)(s);
// A click re-renders the same screen: do not replay the entrance animation over a dense diagram.
if(lastRendered===state.index)$('#stage .slide').classList.add('no-anim');lastRendered=state.index;
$('#chapter').textContent=s.chapter;$('#counter').textContent=String(state.index+1).padStart(2,'0')+' / '+slides.length;
document.querySelectorAll('#acts button').forEach(b=>{const first=Number(b.dataset.act),group=b.dataset.group;const a=acts.find(x=>x.first===first);const here=group==='products'?s.track==='products':group==='technical'?s.track==='technical':group==='backup'?!!s.optional&&!s.track:!!a&&state.index>=a.first&&state.index<=a.last;const last=group?slides.reduce((end,x,i)=>(group==='backup'?x.optional&&!x.track:x.track===group)?i:end,-1):a.last;const fill=here?(group?100:Math.round((state.index-first+1)/(last-first+1)*100)):state.index>last?100:0;b.style.setProperty('--fill',fill+'%');b.classList.toggle('current',here);b.classList.toggle('done',fill===100&&!here);if(here)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});
$('#prev').disabled=state.index===0;$('#next').disabled=state.index===slides.length-1;
const elapsed=slides.slice(0,state.index).filter(x=>!x.optional).reduce((a,x)=>a+x.minutes,0);
const moduleElapsed=slides.slice(0,state.index).filter(x=>x.track===s.track).reduce((a,x)=>a+x.minutes,0);
const timing=(start,end)=>[start,end].map(m=>String(Math.floor(m)).padStart(2,'0')+':'+String(Math.round((m%1)*60)).padStart(2,'0')).join('–');
$('#clock').textContent=s.track==='products'?timing(moduleElapsed,moduleElapsed+s.minutes)+' / '+productMinutes+' MIN · PRODUCTS':s.track==='technical'?timing(moduleElapsed,moduleElapsed+s.minutes)+' / '+technicalMinutes+' MIN · TECHNICAL':s.optional?'OPTIONAL / REFERENCE':timing(elapsed,elapsed+s.minutes)+' / 50 MIN';
$('#noteContent').innerHTML='<p class="note-time">'+esc(s.chapter)+' · '+s.minutes+' MIN · SLIDE '+(state.index+1)+'</p><h2>'+esc(s.title).replace(/\n/g,' ')+'</h2>'+(s.cue?'<div class="oral-cue"><b>SAY</b><p>'+esc(s.cue)+'</p></div>':'')+(s.stageAction?'<div class="oral-action"><b>DO / ASK</b><p>'+esc(s.stageAction)+'</p></div>':'')+(s.bridge?'<div class="oral-bridge"><b>THEN →</b><p>'+esc(s.bridge)+'</p></div>':'')+esc(s.notes).split('\n\n').map(x=>'<p>'+x+'</p>').join('')+(s.sources?'<p>'+s.sources.map(u=>'<a href="'+esc(u)+'" target="_blank" rel="noopener">'+esc(u)+'</a>').join('<br>')+'</p>':'');
document.title=(state.index+1)+' · '+s.title.replace(/\n/g,' ')+' · Lintel';
$('#stage').setAttribute('aria-label','Slide '+(state.index+1)+': '+s.title.replace(/\n/g,' '));
document.querySelectorAll('#overviewGrid button').forEach((b,i)=>b.classList.toggle('active',i===state.index));
fit();
}
function go(i){const leaving=slides[state.index].type;if(leaving==='stateflow')state.trail=0;if(leaving==='primer')state.later=false;if(leaving==='cyclemap')state.cyclePhase=undefined;if(leaving==='routes')state.route=0;state.index=Math.max(0,Math.min(slides.length-1,i));history.replaceState(null,'','#'+slides[state.index].id);render();window.scrollTo(0,0);}
function fit(){if(innerWidth<=650)return;const box=$('#viewport').getBoundingClientRect();const scale=Math.min((box.width-34)/1440,(box.height-22)/810);$('#stage').style.transform='scale('+scale+')';}
function showViewer(url,title){$('#viewerTitle').textContent=title;$('#viewerSource').href=url;$('#viewerFrame').src=url;$('#viewer').showModal();}
function closeViewer(){$('#viewer').close();$('#viewerFrame').src='about:blank';}
function toggleNotes(){$('#notePanel').hidden=!$('#notePanel').hidden;$('#notes').setAttribute('aria-expanded',String(!$('#notePanel').hidden));}
const mmss=m=>String(Math.floor(m)).padStart(2,'0')+':'+String(Math.round((m%1)*60)).padStart(2,'0');
$('#overviewGrid').innerHTML=slides.map((s,i)=>{const n=acts.findIndex(a=>a.first===i);const start=n>=0?acts.slice(0,n).reduce((t,a)=>t+a.minutes,0):0;const head=n>=0?'<h3 class="o-act"><b>'+(n+1)+'</b>'+esc(acts[n].name)+'<span>'+mmss(start)+' · '+acts[n].minutes+' min</span></h3>':i===firstProducts?'<h3 class="o-act"><b>P</b>Product launch<span>separate · '+productMinutes+' min</span></h3>':i===firstTechnical?'<h3 class="o-act"><b>T</b>Technical deep dive<span>separate · '+technicalMinutes+' min</span></h3>':i===firstBackup?'<h3 class="o-act"><b>+</b>Backup<span>optional · reference</span></h3>':'';return head+'<button data-slide="'+i+'"><span class="o-num">'+String(i+1).padStart(2,'0')+(s.optional?' / '+esc(s.chapter):' · '+s.minutes+' min')+'</span>'+esc(s.title).replace(/\n/g,' ')+'</button>';}).join('');
$('#acts').innerHTML=acts.map((a,n)=>'<button data-act="'+a.first+'" style="flex-grow:'+(a.minutes+3)+'" title="'+esc(a.name)+' · '+a.minutes+' min" aria-label="Act '+(n+1)+': '+esc(a.name)+', '+a.minutes+' minutes"><b>'+(n+1)+'</b><span>'+esc(String(a.name||'').replace(/^The /,''))+'</span></button>').join('')+(firstBackup>=0?'<button data-act="'+firstBackup+'" data-group="backup" class="backup" style="flex-grow:5" title="Optional and reference screens" aria-label="Backup: optional and reference screens"><b>+</b><span>Backup</span></button>':'');
if(firstProducts>=0)$('#acts').insertAdjacentHTML('beforeend','<button data-act="'+firstProducts+'" data-group="products" style="flex-grow:7" title="Product launch · '+productMinutes+' minutes" aria-label="Products: '+productMinutes+' minute launch section"><b>P</b><span>Products</span></button>');
if(firstTechnical>=0)$('#acts').insertAdjacentHTML('beforeend','<button data-act="'+firstTechnical+'" data-group="technical" style="flex-grow:8" title="Separate technical section · '+technicalMinutes+' minutes" aria-label="Technical: separate '+technicalMinutes+' minute section"><b>T</b><span>Technical</span></button>');
$('#prev').onclick=()=>go(state.index-1);$('#next').onclick=()=>go(state.index+1);
$('#overview').onclick=()=>$('#overviewDialog').showModal();$('#notes').onclick=toggleNotes;$('#closeNotes').onclick=toggleNotes;
$('#full').onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen();}catch{ $('#full').title='Use the browser fullscreen shortcut';}};
document.addEventListener('click',event=>{
const b=event.target.closest('button');if(!b)return;
const keep=sel=>{if(event.detail===0){const e=$(sel);if(e)e.focus();}};
for(const [key,prop,numeric] of [['techHome','techHome',false],['techPhase','techPhase',true],['techHooks','techHooks',false],['techClient','techClient',true]]){if(b.dataset[key]!==undefined){state[prop]=numeric?Number(b.dataset[key]):b.dataset[key];render();const selector=key.replace(/[A-Z]/g,c=>'-'+c.toLowerCase());keep('#stage [data-'+selector+'="'+state[prop]+'"]');}}
if(b.dataset.trail!==undefined){state.trail=Number(b.dataset.trail);render();keep('#stage [data-trail="'+state.trail+'"]');}
if(b.dataset.product!==undefined){go(slides.findIndex(x=>x.id===b.dataset.product));}
if(b.dataset.slide!==undefined){$('#overviewDialog').close();go(Number(b.dataset.slide));}
if(b.dataset.close){b.dataset.close==='viewer'?closeViewer():$('#'+b.dataset.close).close();}
if(b.dataset.view)showViewer(b.dataset.view,b.dataset.title||'Artifact');
if(b.dataset.action==='reuse'){state.packed=!state.packed;render();keep('#stage [data-action="reuse"]');}
if(b.dataset.action==='context'){state.curated=!state.curated;render();keep('#stage [data-action="context"]');}
if(b.dataset.action==='later'){state.later=!state.later;render();keep('#stage [data-action="later"]');}
if(b.dataset.act!==undefined){go(Number(b.dataset.act));if(event.detail>0)b.blur();}
if(b.dataset.route!==undefined){state.route=Number(b.dataset.route);render();keep('#stage [data-route="'+state.route+'"]');}
if(b.dataset.phase!==undefined){state.cyclePhase=Number(b.dataset.phase);render();keep('#stage [data-phase="'+state.cyclePhase+'"]');}
if(b.dataset.question!==undefined){state.question=Number(b.dataset.question);render();keep('#stage [data-question="'+state.question+'"]');}
if(b.dataset.profile){state.profile=b.dataset.profile;render();keep('#stage [data-profile="'+state.profile+'"]');}
if(b.dataset.regression){state.regression=b.dataset.regression;render();keep('#stage [data-regression="'+state.regression+'"]');}
});
document.addEventListener('keydown',e=>{
if(e.target.closest('input,textarea,select')||e.ctrlKey||e.altKey||e.metaKey)return;
if($('#viewer').open||$('#overviewDialog').open)return;
if(e.key==='Escape'){$('#notePanel').hidden=true;return;}
if(e.key==='ArrowRight'||e.key==='PageDown'||(e.key===' '&&e.target===document.body)){e.preventDefault();go(state.index+1);}
if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();go(state.index-1);}
if(e.key==='Home'){e.preventDefault();go(0);}if(e.key==='End'){e.preventDefault();go(slides.length-1);}
if(e.key.toLowerCase()==='n')toggleNotes();if(e.key.toLowerCase()==='o')$('#overviewDialog').showModal();if(e.key.toLowerCase()==='f')$('#full').click();
});
$('#viewer').addEventListener('close',()=>{$('#viewerFrame').src='about:blank';});
addEventListener('resize',fit);addEventListener('hashchange',()=>{const i=slides.findIndex(s=>s.id===location.hash.slice(1));if(i>=0&&i!==state.index)go(i);});
$('#stage').style.setProperty('--cl',CL.map(w=>w+'px').join(' '));
const initial=slides.findIndex(s=>s.id===location.hash.slice(1));state.index=initial>=0?initial:0;render();
window.DECK_API={go,state,slides};
})();