window.DECK_SLIDES = [
  {
    "id": "welcome",
    "chapter": "Welcome",
    "type": "holding",
    "holding": true,
    "title": "The portal is open.",
    "subtitle": "We begin shortly.",
    "minutes": 0,
    "notes": "Leave this screen on while people join. The supplied portal animation loops silently. Pause motion if preferred; reduced-motion settings show the still image by default. This holding screen is outside the 50-minute talk. When everyone is ready, choose Begin or press the right arrow: the original opening starts on slide 2. The illustration sets the atmosphere; it is not evidence of product behavior.",
    "stageAction": "Let the room settle. Use fullscreen if presenting. Choose Begin when you are ready.",
    "bridge": "We had a plan. The AI had other plans."
  },
  {
    "id": "three-hours",
    "chapter": "Meet Lintel",
    "type": "systemcover",
    "title": "We had a plan.\nThe AI had\nother plans.",
    "subtitle": "Ever had to explain the same plan twice?",
    "minutes": 1,
    "notes": "I am Johannes, and Lintel is my independent open-source engineering project. You write a detailed plan. Hours later the agent is doing impressive work, but the scope has moved. Or it stops, and you have to reconstruct the next step. Then you repeat the same architecture and quality instructions in another repository. I became a rather expensive copy-and-paste loop.\n\nA lintel is the beam over an opening that carries the structure above it. That is the metaphor: useful structure supports the work. Today we follow intent through implementation and review, then see what survives the next session. The conversation on screen is illustrative, not a recorded experiment. We will separate implemented mechanisms, saved demonstrations and things we still need to measure.",
    "showSubtitle": true,
    "evidenceLabel": "Illustrative conversation",
    "cue": "Who has corrected an AI on something you agreed three hours ago?",
    "stageAction": "Pause for hands. Let the dashboard-to-platform joke land. Introduce yourself in one sentence.",
    "bridge": "First, the whole system. Then we open it one part at a time."
  },
  {
    "id": "what-is-lintel",
    "chapter": "Meet Lintel",
    "type": "systemmap",
    "title": "Here’s the whole system.",
    "subtitle": "A workflow kit inside the coding tools you already use.",
    "minutes": 1.5,
    "notes": "Lintel is a kit of repository instructions, workflows and local helpers inside the coding client you already use. There is no hosted Lintel service or background daemon. The host owns the model, tools, permissions and execution.\n\nThe company-neutral spine carries the method. A separate pack supplies the standards, knowledge, roles and language your team owns. Skills tell the agent how to perform a job; roles give delegated workers a focused assignment. Agents and helpers maintain plans, decisions, lessons and a handoff. Later work reads relevant records.\n\nThe arrows describe a workflow, not a promise that every action is automatically intercepted. Hooks support selected events where registered. Permissions and CI remain platform controls. Current source is version 0.12.0, still a public beta. A file being present does not prove a host ran it.",
    "showSubtitle": true,
    "evidenceLabel": "Source 49f2d152 · public beta · host execution and permissions",
    "cue": "Your coding agent executes. Lintel supplies a shared way to work.",
    "stageAction": "Trace client → method → project records → next task. Mention the team pack and platform boundary; save detailed paths for later.",
    "bridge": "Six simple words make this map easier to read.",
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/README.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/architecture.md"
    ]
  },
  {
    "id": "inside-the-kit",
    "chapter": "Meet Lintel",
    "type": "buildingblocks",
    "title": "Six parts. One working system.",
    "subtitle": "",
    "minutes": 1,
    "notes": "Scaffolding gives the project places for instructions, plans, decisions, lessons and handoffs. The method defines the workflow and when clarification or review is needed. Skills are reusable recipes for jobs such as architecture, technical review or testing. Agent roles provide focused expertise; separate execution depends on host support. Hooks are registered event checks, not an intelligent observer of everything. Compounding means a reviewed lesson or decision is retrieved and applied to later relevant work. A team pack changes the standards and context across these parts. Compounding needs retrieval and verification; accumulating more files alone does not create value.",
    "showSubtitle": false,
    "evidenceLabel": "Load the parts the task needs.",
    "cue": "Scaffolding is where it lives. The method says how to work. Compounding brings useful learning back.",
    "stageAction": "Use one short sentence per part. Explain that an agent role is a job description and a hook reacts to an event.",
    "bridge": "Bring the same method to four supported client families."
  },
  {
    "id": "supported-tools",
    "chapter": "Meet Lintel",
    "type": "clients",
    "title": "Four client families.\nOne shared method.",
    "subtitle": "CLI · desktop · IDE · cloud — check the exact surface.",
    "minutes": 1,
    "notes": "Lintel deliberately supports four families: GitHub Copilot, Claude, Codex and Cursor. The earlier much larger registry was narrowed to focus maintenance on the clients the team uses. There are thirteen named surfaces plus the manual other route. Twelve records have native-format discovery; Codex cloud and other use explicit file handoff.\n\nA CLI record is not proof of desktop, IDE or cloud parity. The registry separates vendor documentation, delivered files and observed execution. Most execution records remain not_run. Partial Copilot App observations do not certify that entire family.\n\nThe repo kit keeps one shared source bundle and fifteen starter workflow wrappers, including MARS. It installs no hooks. Copilot has its own hooks, but Lintel has not translated its Claude Code hook bundle to that API. Pilot the exact surface, version and policy you intend to use.",
    "showSubtitle": true,
    "evidenceLabel": "13 named surfaces + manual fallback · discovery ≠ live parity",
    "cue": "Copilot, Claude, Codex and Cursor. Shared method, surface-specific execution.",
    "stageAction": "Name four families, then CLI / desktop / IDE / cloud. Explain the evidence ladder once.",
    "bridge": "That also makes it easier to say what belongs elsewhere.",
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/.claude/decisions/0035-four-supported-client-families.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/lib/cli-tiers.yaml",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/client-adapters.md"
    ]
  },
  {
    "id": "not-one-ring",
    "chapter": "Meet Lintel",
    "type": "guild",
    "title": "No single harness.\nNo magic ring.",
    "subtitle": "Different tools. Different jobs. Plenty of room at the table.",
    "minutes": 0.5,
    "notes": "MDASH and AGT are useful reference points from our engineering conversations. They address their own jobs and do not need replacing for Lintel to be useful. Lintel focuses here on the workflow around coding work: scope, context, execution, review and continuity. Another tool's report can be input without implying a native connector.\n\nMARS, which we will see later, is now a Lintel review workflow. Keep it distinct from swarming: multiple perspectives on one subject versus workers implementing different packages.",
    "showSubtitle": false,
    "evidenceLabel": "Positioning, not a feature comparison",
    "cue": "There is no single harness to rule them all.",
    "stageAction": "Keep this to thirty seconds. Describe complementary jobs, not a feature comparison.",
    "bridge": "The problem I started with was simpler: what can the next session actually see?",
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/README.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/mars/SKILL.md"
    ]
  },
  {
    "id": "context-primer",
    "chapter": "The method",
    "type": "primer",
    "title": "A fresh session.\nA new window.",
    "subtitle": "Everything the agent knows about your project has to fit in here — right now.",
    "minutes": 1.5,
    "notes": "An agent is a model with tools that can read files, edit and run commands under host permissions. Context is what the model can see for this turn: instructions, files, tool results and conversation. A fresh session needs relevant context loaded again.\n\nClick Three hours later. This is an illustration with invented counts. Hosts manage long conversations differently through selection, compaction and truncation. Even when a decision exists in the transcript, we should not depend on it being used correctly later.\n\nDo not put the whole repository into every prompt. Keep current intent, relevant decisions, the next task and its acceptance available. Retain sources and select deliberately. A memory file that is never read is a very organised way of forgetting.",
    "sources": [
      "https://www.trychroma.com/research/context-rot"
    ],
    "showSubtitle": true,
    "evidenceLabel": "Simplified illustration · invented counts · tools manage context differently",
    "cue": "A new conversation gets a new working window. It does not inherit every decision.",
    "stageAction": "Click Three hours later. Define agent, context and session; keep the invented counts illustrative.",
    "bridge": "Separate the intent, the method and the reason—and give them somewhere durable to live."
  },
  {
    "id": "what-how-why",
    "chapter": "The method",
    "type": "triad",
    "title": "What. How. Why.\nThen make it compound.",
    "subtitle": "A working contract the next session can actually use.",
    "minutes": 1,
    "notes": "Here is the method in three words. What defines the outcome and scope. How makes execution and verification explicit. Why preserves the reasons behind choices so later sessions can reuse them. Next, follow these responsibilities through the cycle. WHAT is the intended result and its boundaries: who is this for, what changes, and what does done mean? HOW is the work: a plan at an actionable level, a repeatable workflow, and specific review and verification steps. WHY is the decision context: constraints, rejected alternatives and the reason we chose this approach. Then compound: capture a correction, retain the decision, and retrieve it when the next task matches. The workflow asks for these artifacts. The artifact itself is not a guarantee of quality. Evidence and review have to make the contract real.",
    "showSubtitle": false,
    "evidenceLabel": "",
    "cue": "What are we building, how do we verify it, and why this approach?",
    "stageAction": "Point once to each word; explain compounding with the return arrow.",
    "bridge": "Here is the method that turns those questions into an executable path."
  },
  {
    "id": "the-cycle",
    "chapter": "The method",
    "type": "cyclemap",
    "title": "Agree the work.\nThen build the work.",
    "subtitle": "The full path is a map, not mandatory ceremony.",
    "minutes": 2,
    "notes": "The full cycle is SENSE, SCOPE, DEFINE, DISCOVER, PLAN, BUILD, REVIEW, SHIP and CAPTURE. Think in three chunks: understand and agree; implement and verify; leave a useful trail.\n\nPLAN aligns the original specification, task map and handoff. You authorize the plan before substantial implementation. BUILD executes coherent packages with short verifiable leaves. REVIEW checks requirements, quality and active-pack compliance. SHIP follows the authorized delivery path. CAPTURE updates useful lessons, decisions and working state; not every cycle needs a new ADR.\n\nThese instructions are backed by specific helpers, not a universal scheduler. Content-bound checks validate selected evidence; actual tools and release remain under platform control. Swarming changes how approved packages execute, not the phases or requirements.",
    "showSubtitle": false,
    "evidenceLabel": "Workflow instructions · checks and platform controls do the enforcing · chat strip illustrative",
    "cue": "The expensive mistake is correct code built against the wrong premise.",
    "stageAction": "Trace understand → agree → build → review → capture. Click PLAN and REVIEW; do not recite nine definitions.",
    "bridge": "No, a typo should not need the whole ceremony.",
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/the-cycle.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/build/SKILL.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/review/SKILL.md"
    ]
  },
  {
    "id": "short-routes",
    "chapter": "The method",
    "type": "routes",
    "title": "Nine steps\nfor a typo?",
    "subtitle": "SENSE reads the request and suggests a route. You confirm it.",
    "minutes": 1,
    "notes": "A known fix can use SENSE, BUILD, REVIEW and SHIP. Research stops after SENSE, DEFINE and DISCOVER. A feature can use the full cycle, sized to risk. Explicit phase ranges keep their prerequisites.\n\nThese illustrative examples came from the recorded keyword-routing experiment. A keyword match is advice, not understanding. An explicit mode wins; resolve ambiguity before following a suggestion. The short route preserves review and authority. You should feel saved repetition, not an obligation to invoke ninety-six things.",
    "showSubtitle": false,
    "evidenceLabel": "Illustrative requests · keyword rules today · SENSE recommends, you confirm · an explicit mode always wins · workflow instructions, not enforcement",
    "cue": "Use the shortest route that preserves the necessary checks.",
    "stageAction": "Show hotfix and research. Use the full-cycle row to contrast a feature. Do not improvise routing predictions.",
    "bridge": "Once the route is chosen, stop rewriting the same quality instructions.",
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/the-cycle.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/cycle/SKILL.md"
    ]
  },
  {
    "id": "repeat-yourself",
    "chapter": "The method",
    "type": "reuse",
    "title": "Your fifth dashboard\nshould remember the first.",
    "subtitle": "Repeat the useful method. Revisit the actual requirements.",
    "minutes": 1,
    "notes": "Imagine building dashboards across five repos. Each time you ask for sensible empty states, meaningful time axes, accessible charts, correct filtering and exports that match the screen. Those are recurring review questions. A reusable skill can carry them once. It should not blindly carry the previous customer's requirements or architecture. The reusable part is the decision procedure: what to inspect, what to ask, what evidence to produce and when to stop. Click Package the pattern. The invariant checks move into the skill; the new repo's data, audience and constraints still enter every time. This is deliberate reuse, not copy-paste architecture.",
    "showSubtitle": false,
    "evidenceLabel": "Illustrative skill pattern",
    "cue": "The fifth dashboard should reuse the questions, not inherit the first customer’s answers.",
    "stageAction": "Click Package the pattern once. Mention empty states and export consistency.",
    "bridge": "A reusable method still has to produce the right level of plan."
  },
  {
    "id": "granularity",
    "chapter": "The method",
    "type": "granularity",
    "title": "Small steps.\nA coherent piece of work.",
    "subtitle": "Granular enough to verify. Coarse enough to move.",
    "minutes": 2,
    "notes": "The hybrid rule keeps short two-to-five-minute leaves but executes and reviews a coherent work package. A leaf needs an action, target and acceptance check. The package owns a useful outcome: consistent filtering across dashboard and CSV.\n\nT01 defines active. T02 shares one dataset contract. T03 verifies the export. These are separate checks, not separate visions. One implementer owns the bounded package, followed by spec and quality review covering every leaf. A failed leaf keeps the package open.\n\nDependencies and ownership determine concurrency. More checkboxes do not make a better plan. A fresh worker should know what to do; a reviewer should be able to establish completion. Preserve original finding IDs when turning a report into repair packages.",
    "showSubtitle": true,
    "evidenceLabel": "Review depth follows risk",
    "cue": "Small enough to verify. Coherent enough to deliver.",
    "stageAction": "Walk T01–T03 as one package. Explain the defect when CSV and screen filters differ.",
    "bridge": "Then ask a stronger question than “does this look good?”",
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/build/SKILL.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/concepts/planner-as-module.md"
    ]
  },
  {
    "id": "review-method",
    "type": "reviewmethod",
    "title": "“Looks good”\nis not a review.",
    "subtitle": "Same questions. Explicit coverage. Evidence that matches the work.",
    "showSubtitle": true,
    "evidenceLabel": "Shared Review Method · ADR-0036 · missing coverage stays incomplete",
    "cue": "What was checked, what was found, and what remains unknown?",
    "stageAction": "Trace the cancellation question through evidence to decision. Distinguish executed from traced evidence.",
    "bridge": "Those questions matter more when the system knows this project’s actual standards.",
    "notes": "Lintel now has one Review Method. A single reviewer and each MARS slot receive the same packet body. Standing questions are selected for the subject and relevant surfaces: contracts, boundaries, failure paths, trust, consumers and more. The coordinator confirms tags; keyword guesses are not the final risk assessment.\n\nCan cancellation restore stock twice? A useful finding names the input, actual result and smallest fix. Applicable questions need explicit coverage. Silence is not a pass. A checked row needs evidence; unverified requirements and missing coverage remain incomplete.\n\nFour evidence levels separate executed, traced, pattern and hypothesis. Severity follows consequence, not confidence or taste. P1 fails, P2 requests changes and incomplete evidence stays incomplete.\n\nThe record binds to selected content, acceptance and profile. Changed inputs invalidate old clearance; a later relevant rejection overrides an earlier pass. Helpers validate the record and its binding. They cannot guarantee model understanding or turn a self-claimed actor name into proven independence.",
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/review/references/method.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/lib/review-questions.json",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/review/references/evidence.md"
    ],
    "chapter": "The method",
    "minutes": 2.5
  },
  {
    "id": "profile",
    "chapter": "Make it last",
    "type": "profile",
    "title": "A profile should\nchange the work.",
    "subtitle": "“Enterprise” is not a theme color.",
    "minutes": 2,
    "notes": "Remember the pack from the kit screen: the team’s standards. This switches between two of them, a lab and a customer pilot. Switch between Lab and Customer pilot. This is a separate, deterministic demo: no model runs here, and it is not part of the paired agent builds. The actual Lintel pack resolver supplies values from two synthetic manifests. A presentation consumer turns them into the displayed contract. Notice the evidence requirement changes from a smoke test to a tenant negative test; identity and network design requirements change too. The demo_policy fields are custom presentation fields. No identity or network infrastructure is provisioned, and hard mode is a configuration value, not proof of enforcement. The value hypothesis is concrete: a profile should change decisions, questions and acceptance evidence.\n\nThis saved mechanism proof predates the Universal integration. It retains its original provenance. Current Universal adds content-bound profile identity, shared lifecycle recovery and structured evidence; this older run does not verify those additions.",
    "showSubtitle": true,
    "evidenceLabel": "Saved synthetic resolver proof · historical 28061e4 · not policy enforcement",
    "cue": "Enterprise is not a theme color. The requirements must change.",
    "stageAction": "Toggle Lab → Customer pilot. Read the changed evidence field.",
    "bridge": "Separate configuration from the knowledge that travels with the repository."
  },
  {
    "id": "where-it-lives",
    "chapter": "Make it last",
    "type": "storage",
    "title": "Your setup.\nYour project’s memory.",
    "subtitle": "What stays on your machine? What travels with Git?",
    "minutes": 1.5,
    "showSubtitle": false,
    "evidenceLabel": "Representative Lintel layout · adapter-specific files vary",
    "notes": "Remember the window: files are what survive a session. This is where Lintel puts them. Point to the left first: machine-global means reusable across projects on this computer. The ~/.lintel/ home contains your profile and installed packs, as well as operator-wide records. Your coding client owns its own settings, tools and permissions; ~/.claude/ is a Claude-specific home, not a universal home for every app. Now point right: the project repository keeps reviewed memory, decisions, plans and handoffs under its declared paths. In the standard Lintel layout that is .claude/memory/, .claude/decisions/ and .claude/plans/. Commit the appropriate reviewed knowledge so Git can carry it to the next person or session. The dashed area is .claude/runtime/: temporary execution state is ignored and does not travel in a normal clone. The .claude folder name does not require Claude Code. Client adapters (the files that teach one coding tool where to find all this; the technical module has the full path matrix) can add their own files; the Copilot route of the Universal repository kit uses .github/copilot-instructions.md, .github/skills/, .github/agents/ and .github/lintel/. Those details are in the field guide. Your global profile and installed packs do not automatically appear on a colleague’s machine through Git. The active pack must be available and configured there. The point is to separate reusable operator context, portable project knowledge and disposable run state.\n\nThe shared source bundle remains .github/lintel/ for compatibility. Other selected surfaces get their own discovery roots pointing into it. A repo can require a specific pack in .claude/profile-requirements.json; profile.yaml carries role/mode preferences, not pack selection. Bound profile drift requires explicit reconciliation. See the technical module for exact paths.\n\nThe portable repository kit defaults its configuration home to .claude/runtime/lintel-home, while bare installation defaults to ~/.lintel. An explicit LINTEL_HOME overrides the default. The diagram distinguishes these two routes; a global home is not required.",
    "cue": "Your setup stays with you. The project’s reviewed knowledge travels with the project.",
    "stageAction": "Trace left → right, then the Git arrow. Point to the dashed runtime box last.",
    "bridge": "These files matter only when the workflow writes and reads them.",
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/client-adapters.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/lifecycle.md"
    ]
  },
  {
    "id": "state-loop",
    "chapter": "Make it last",
    "type": "stateflow",
    "title": "The work leaves a way back.",
    "subtitle": "The method requires a trail. Skills and agents write it as they work.",
    "minutes": 1.5,
    "showSubtitle": true,
    "evidenceLabel": "Illustrative walkthrough · no agent or hook is executing here.",
    "cue": "The agent should not need your memory to find its next task.",
    "stageAction": "Click through the three example steps: clarification, saved decision, fresh session. Explain who asks and who writes. Keep the registered-hook lane separate.",
    "notes": "The method requires the agent to clarify material ambiguity, record consequential decisions, keep the plan current and capture evidence. Skills turn those requirements into concrete instructions; agents and local helpers perform the writes. They maintain the existing scaffolding instead of inventing a new memory store. This example begins with an export task and an unresolved date boundary. The workflow surfaces the ambiguity and the agent asks whether dates use UTC or local time. The human answers UTC. The agent records that decision, updates the task and identifies the boundary test as the next action. A compatible SessionStart hook can surface a digest, and a prompt-position hook can reassert the current step. A fresh agent still reads and checks the authoritative files before continuing. Hooks run only on exposed and registered events. A hook may warn, supply context or block selected operations, according to its actual contract; it does not itself understand every uncertainty or guarantee that a question is asked. Stop warnings do not force auto-continuation. Keep reviewed decisions and handoffs with Git; keep temporary counters and runtime ledgers ignored. The quality comes from both writing and reading the trail.",
    "bridge": "Inspect a saved cold-start example rather than trusting the arrows."
  },
  {
    "id": "cold-start",
    "chapter": "Make it last",
    "type": "cold",
    "title": "Delete the chat.\nKeep the plot.",
    "subtitle": "The next session needs coordinates, not a séance.",
    "minutes": 2,
    "notes": "This is the window idea, applied: assume the session is gone — what is left on disk? We do not delete anything in your real repo. The prepared proof creates a local clone of a synthetic fixture without the ignored runtime ledger. The committed specification, plan, tasks and handoff survive. Show the four pointers and the next action T002. The helper validates the map and file boundaries; the explicit handoff supplies the next task. It is not the helper reasoning about priorities. Missing files and a path escaping the repo are rejected in the saved run. A fresh agent still needs to read and reason about those artifacts, but it no longer has to recover the project from chat archaeology. The four on-screen labels stand for the exact committed paths shown in the offline field guide and helper proof explorer.\n\nThis saved mechanism proof predates the Universal integration. It retains its original provenance. Current Universal adds content-bound profile identity, shared lifecycle recovery and structured evidence; this older run does not verify those additions.",
    "showSubtitle": false,
    "evidenceLabel": "Saved cold-clone helper proof · historical 28061e4 · no model replay",
    "cue": "We lose the runtime, not the plot.",
    "stageAction": "Trace the four committed pointers to T002. The saved helper checks the map.",
    "bridge": "Continuity preserves the next action. Learning should preserve a correction."
  },
  {
    "id": "regression",
    "chapter": "Make it last",
    "type": "regression",
    "title": "A lesson that never returns\nis just a diary entry.",
    "subtitle": "Capture → retrieve → verify → reinforce.",
    "minutes": 2.5,
    "notes": "Show Before: lookup by document ID allows another tenant's document. Switch to Fixed: the same three tests now include the tenant condition. Then select Reintroduce bug: deliberately run the vulnerable version again and watch the cross-tenant check fail. That is the important negative control. The prepared lesson is retrieved through the real keyword-scoped memory helper; an obsolete lesson and an unrelated lesson are excluded. This is not model training and not proof of production authentication. It is an example of turning a specific correction into both reusable context and executable protection. Read the red result aloud for remote participants.\n\nThis saved mechanism proof predates the Universal integration. It retains its original provenance. Current Universal adds content-bound profile identity, shared lifecycle recovery and structured evidence; this older run does not verify those additions.",
    "showSubtitle": false,
    "evidenceLabel": "Saved Python fixture runs · trusted caller identity · not deployed authentication",
    "cue": "Put the bug back. Does the test notice?",
    "stageAction": "Click Before → Fixed → Reintroduce bug. Read the red result aloud.",
    "bridge": "Different knowledge needs different durable forms."
  },
  {
    "id": "compound",
    "chapter": "Make it last",
    "type": "compound",
    "title": "Correct once.\nMake the correction travel.",
    "subtitle": "Different artifacts remember different things.",
    "minutes": 1,
    "notes": "A lesson remembers a failure mode and when to look for it. An ADR remembers a decision and its rationale. A skill remembers the reusable method. A test remembers an observable boundary. They work together, but they are not interchangeable. Do not turn every preference into a permanent constitutional rule. Record scope, source and review status; retire what becomes wrong. Compounding context means the next relevant task starts with better material. It does not mean an ever-growing prompt, and it does not promise an exponential learning curve.",
    "showSubtitle": false,
    "evidenceLabel": "Compounding context, not model training",
    "cue": "A correction becomes useful when the next relevant task can find it.",
    "stageAction": "Explain the different jobs of a lesson, ADR, skill and test.",
    "bridge": "Once work and evidence are explicit, we can discuss more than one worker."
  },
  {
    "id": "swarm",
    "chapter": "Scale the work",
    "type": "swarm",
    "title": "Parallel work.\nOne accountable plan.",
    "subtitle": "Parallelize independent work, not shared confusion.",
    "minutes": 2.5,
    "notes": "Triage a bug list or MDASH report into approved packages, preserving the original findings and acceptance. Parallelize only packages whose dependencies and ownership permit it. Swarming is opt-in over PLAN, BUILD and REVIEW.\n\nOne coordinator owns shared task state, generated outputs, commits and integration. Workers write declared paths and report. Separate reviewers examine the lanes. Concurrent writers require attributable worktrees, isolated patches or equivalent host-enforced scope. A shared-folder promise is insufficient.\n\nPassing lane reviews are inputs, not final acceptance. Reconcile the branch and review the integrated result. Without isolation, replay the same briefs serially. Without independent review, keep that requirement open.\n\nRecovery comes from artifacts and attributable changes, not a running-status label. Agree delivery packages, PR authority and stop conditions before dispatch. Optimize accepted changes rather than busy-agent counts.",
    "showSubtitle": false,
    "evidenceLabel": "Opt-in execution · attributable isolation required · serial fallback",
    "cue": "Swarming divides implementation. It does not divide accountability.",
    "stageAction": "Trace task map → independent writer lanes → lane reviews → integrated review. Use report remediation as the example.",
    "bridge": "MARS adds different perspectives on the same subject.",
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/concepts/swarming-work.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/swarm/SKILL.md"
    ]
  },
  {
    "id": "mars",
    "type": "marspanel",
    "title": "Same question.\nMore than one perspective.",
    "subtitle": "MARS · Multi-Model Adversarial Review & Screening",
    "showSubtitle": true,
    "evidenceLabel": "Explicit consent + live eligibility · standalone panels are advisory",
    "cue": "Swarm builds different packages. MARS reviews one subject from different models.",
    "stageAction": "Trace one frozen packet into separate contexts and evidence-based synthesis. Point to the incomplete slot.",
    "bridge": "Now the personal swarming moments should make more sense.",
    "notes": "MARS sends the same Review Method body to separate reviewer contexts. Each first pass is blind to the others. The coordinator deduplicates and adjudicates by evidence, with a challenge round when contested and authorized. Agreement is not a majority-vote permission to ship.\n\nThe host must prove separate contexts, per-child model selection, allowed delegation and observable identities for at least two distinct models. An offer, silence or auto mode is not consent. The helper resolves live models and validates state; it never dispatches, authorizes or closes sessions itself. Actual host tools do that work.\n\nIn the recorded synthetic RM9 pilot, three valid reports aligned on one contract-breaking defect. A fourth had a bad header and hash and was refused. The panel remained partial and multi-model verification was false. This shows the refusal boundary, not ROI or model rankings.\n\nStandalone MARS is advisory. REVIEW can use an adjudicated panel through its own content-bound stage decision and coverage rule. Panels have token and coordination overhead; use them when the cost of a missed issue justifies it.",
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/.claude/decisions/0036-mars-multi-model-review.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/mars/SKILL.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/.claude/plans/mars/pilot-2026-09-25-rm9.md"
    ],
    "chapter": "Scale the work",
    "minutes": 2
  },
  {
    "id": "swarming-moment",
    "chapter": "Scale the work",
    "type": "swarmreveal",
    "title": "I stopped being the queue.",
    "subtitle": "My GitHub activity, before and after adopting Lintel swarming.",
    "showSubtitle": false,
    "minutes": 0.5,
    "evidenceLabel": "Two selected days from my GitHub history. Contributions measure activity — not quality or bugs fixed.",
    "cue": "Here is a day from before I had swarming in Lintel. Fifty-five contributions. Then I changed how I organised the work.",
    "stageAction": "Point to 55. Click “Then I turned on swarming.” Let 711 land in silence for two beats. Point to the original screenshots, then trace the report-to-fix flow. Use “Replay reveal” if rehearsing.",
    "bridge": "More throughput also gave me a very large reminder about delivery boundaries.",
    "notes": "Before swarming, one busy day showed 55contributions. Afterwards, this day showed 711. [Reveal.] That changed the scale of work I could coordinate. These are two personal activity snapshots, not proof of quality or a measured speedup. More activity still has to become reviewed, useful changes. And that brings me to the next morning.",
    "sources": [
      "../presenter/sources.html#swarming-activity",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/concepts/swarming-work.md"
    ]
  },
  {
    "id": "we-broke-github",
    "chapter": "Scale the work",
    "type": "githubmoment",
    "title": "We broke GitHub.*",
    "subtitle": "*My browser tab, technically.",
    "showSubtitle": true,
    "minutes": 0.5,
    "evidenceLabel": "Personal incident · PR #93 screenshot · not a throughput benchmark",
    "cue": "740 commits. 760 files. One very unhappy browser tab.",
    "stageAction": "Point to the unresponsive-tab message, pause for the joke, then move on. Do not open the enormous PR live.",
    "bridge": "The comic version is an unhappy browser. The serious boundary is what has permission to happen.",
    "notes": "I tried the new swarming and left it working overnight. I forgot to authorize pull requests along the way. The result: 740 commits, 760 files—and an unresponsive browser tab. So, obviously, we broke GitHub. [Pause.] My tab, to be precise. More throughput still needs small, reviewable deliveries.\n\nThis is my account of the incident. The supplied screenshot documents the visible PR counts and unresponsive tab, not a GitHub outage or a measured productivity gain. Agree PR authorization, bounded delivery packages and a stop condition before dispatch. A missing delivery decision is a reason to pause the affected work, not permission to keep expanding it.",
    "sources": [
      "https://github.com/jokerman89/lintel/pull/93"
    ]
  },
  {
    "id": "enforcement",
    "chapter": "Scale the work",
    "type": "enforcement",
    "title": "Markdown can tell you to lock it.\nIt cannot be the lock.",
    "subtitle": "Guidance, checks and authority have different jobs.",
    "minutes": 1,
    "notes": "This matters when we talk to customers. The harness can structure the work, ask for evidence and invoke supported checks. Actual permissions, identity, network isolation, CI and deployment approvals must be configured and verified in the platform. A skill saying use least privilege does not grant or enforce least privilege. Likewise, universal method does not mean every host supports the same hooks or parallel agents. Keep this distinction crisp. It makes the rest of the story more credible and gives architects a clear boundary.",
    "showSubtitle": false,
    "evidenceLabel": "Platform controls must be configured and verified.",
    "cue": "The instruction describes the lock. The platform has to provide it.",
    "stageAction": "Point to both objects; name permissions and CI as examples.",
    "bridge": "Finally, test whether the structure earns its overhead."
  },
  {
    "id": "experiment",
    "chapter": "Test the value",
    "type": "experiment",
    "title": "Same kitchen.\nThree ways to build.",
    "subtitle": "Naked Copilot → Lintel → Lintel + Swarming",
    "minutes": 1.5,
    "notes": "Service House is a restaurant operations app: Menu, Orders, Inventory and Reports. Every arm receives the same prompt, brief, fixture, starter and acceptance. Thirty-two requirements are worth a hundred points. The prompt forbids follow-up questions, so Lintel cannot receive extra requirements the baseline lacks.\n\nNaked Copilot has no Lintel or delegation. Lintel serial uses packages and independent review. Swarming retains the same Lintel and delegate configuration but executes eligible packages concurrently. Naked versus Lintel changes workflow and model mix; an all-same-model series would isolate the workflow further.\n\nVersion 2 gives the controller server-readiness and submission ownership. No accepted controlled comparison exists. Builds happen beforehand; we inspect the artifacts together. This is the experiment contract, not a victory chart.",
    "showSubtitle": true,
    "evidenceLabel": "Kitchen v2 protocol · comparative runs not accepted",
    "cue": "The fair comparison must be allowed to disappoint us.",
    "stageAction": "Show three arms and the frozen brief. State results are pending before describing expected value.",
    "bridge": "Inspect the same behaviors in every real candidate."
  },
  {
    "id": "results",
    "chapter": "Test the value",
    "type": "results",
    "title": "A receipt beats\na pretty screenshot.",
    "subtitle": "Try the same actions in all three arms.",
    "minutes": 2,
    "notes": "Apply the same actions to every frozen candidate. Two soups, lemonade and KITCHEN10 should total 21.29. Cancellation restores reserved stock exactly once. Reload preserves orders and inventory without repeating checkout.\n\nTrace K20 from the brief to its package, implementation and repeated-cancel check. Explain a difference through decisions and evidence. Do not prewrite a thin losing plan and a rich winning one.\n\nWith no accepted comparison, show the protocol and state the limitation. Reference and broken-control scores calibrate the grader; they are not agent results. The v2 controller owns the server and stop boundary. HTTP readiness, usable UI and passed acceptance remain different measurements.",
    "showSubtitle": true,
    "evidenceLabel": "Expected acceptance behavior · not candidate scores",
    "cue": "The app can look finished and still get dinner wrong.",
    "stageAction": "Walk the three actions. Use the guide until actual accepted candidates exist. Never substitute the reference solution for an arm.",
    "bridge": "A plan matters if its requirements survive into these checks."
  },
  {
    "id": "ab-evidence",
    "chapter": "Test the value",
    "type": "scoreboard",
    "title": "Four measures.\nZero invented winners.",
    "subtitle": "Speed, completeness and cost are different questions.",
    "minutes": 1.5,
    "notes": "Measure usable UI separately from first HTTP and submission. Grade frozen candidates against the same requirements. Retain failed runs, timeouts and exclusions. Cost includes coordinators, workers, reviewers and retries from actual receipts; missing billing stays unknown.\n\nRun sequential arms, counterbalance order and repeat. Verify active implementation overlap for swarming: open sessions or parallel reviewers are insufficient. Report model, knowledge, tool and permission differences.\n\nNo completed accepted comparison is published. The protocol and exact input are available afterwards. Optimize time to an accepted useful change, not time until an agent says done.",
    "showSubtitle": true,
    "evidenceLabel": "Reference/control checks ≠ comparative model results",
    "cue": "Time, quality and cost are separate questions. Unknown is not zero.",
    "stageAction": "Read the measures. Explain one confound and why failures stay in the result set.",
    "bridge": "Return to the strongest reason for Lintel to exist."
  },
  {
    "id": "smarter-models",
    "chapter": "Make it yours",
    "type": "knowledge",
    "title": "A smarter model still wasn’t\nin last week’s meeting.",
    "subtitle": "The durable advantage is your context — not a generic expert persona.",
    "minutes": 1,
    "notes": "As models and native agent tools improve, generic advice to plan carefully or act like an expert becomes weaker differentiation. The strongest value hypothesis is project-specific knowledge: why we rejected an alternative, which requirement the team accepted, what must survive a handoff, and which check has caught a real mistake. The model cannot recover an unavailable decision by being more intelligent. Native tools already provide useful building blocks; Lintel must earn its place through the content, coordination and observed results. That is why this demonstration compares against a competent repo with ordinary project instructions and checks, rather than an artificially weak prompt-only baseline.",
    "showSubtitle": false,
    "evidenceLabel": "Illustrative ADR · the value hypothesis is project-specific knowledge",
    "cue": "Even a smarter model was not in last Tuesday’s meeting.",
    "stageAction": "Use the rejected-option example. Intelligence cannot replace unavailable project knowledge.",
    "bridge": "That argues for a smaller useful core, not more instructions everywhere."
  },
  {
    "id": "small-core",
    "chapter": "Make it yours",
    "type": "smallcore",
    "title": "96 skills.\nA smaller working set.",
    "subtitle": "Keep the capability. Reduce the overlap.",
    "minutes": 1,
    "notes": "There are ninety-six canonical skills today, rather than the previous one-hundred-and-twenty-seven-entry presentation. Roughly eighty was an earlier direction, not a deletion target. Consolidation reduced overlapping entrypoints while retaining saved work, ownership and evidence contracts.\n\nDEFINE owns intake. INSPECT unifies lenses. VERIFY checks by default; repairs need authority. PAUSE and RESUME preserve continuity. WEB-SESSION groups browser modes. MARS adds a distinct review use case. Specialist depth remains available with its real limitations.\n\nThe small default is intent, relevant context, next action and evidence. Add depth for a tenant boundary; do not impose the same process on a button label.",
    "showSubtitle": true,
    "evidenceLabel": "0.12.0 source census · consolidation preserves useful capability",
    "cue": "The library got smaller. Each task should load only what it needs.",
    "stageAction": "Name three consolidated methods; do not read the catalog.",
    "bridge": "Make the first useful customer workflow easier to teach.",
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/.claude/decisions/0034-native-workflow-consolidation.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/CATALOG.md"
    ]
  },
  {
    "id": "team-value",
    "chapter": "Make it yours",
    "type": "team",
    "title": "Different roles.\nShared context.",
    "subtitle": "One shared contract. Three different jobs.",
    "minutes": 1.5,
    "notes": "For demo builders, the opportunity is more reproducible demos, a clear story about trade-offs and less time reconstructing context before a customer meeting. For architects, it is explicit constraints, traceable decisions and a cleaner architecture handoff. For customer developers, especially newcomers, it is a practical way to turn an intent into a verifiable slice without having to invent the review discipline each time. These are proposed benefits to test in a bounded pilot. We are not claiming a measured customer outcome from this presentation.\n\nFor developers new to agentic coding, teach a small verified slice and a reliable way to resume. This may accelerate vibe coding by reducing repeated specification, but it needs a pilot. A person-driven workflow in an existing coding app does not always need a new hosted application. Unattended services and scheduling still need appropriate hosted infrastructure. The smaller Lintel Core distribution remains planned.",
    "showSubtitle": false,
    "evidenceLabel": "Proposed benefits · validate in a pilot",
    "cue": "The same context helps us in different parts of the customer journey.",
    "stageAction": "Give one concrete benefit each for demo builder, architect and developer.",
    "bridge": "Pick one recurring workflow and measure it."
  },
  {
    "id": "pilot",
    "chapter": "Make it yours",
    "type": "pilot",
    "title": "Don’t roll out a philosophy.\nRun a small experiment.",
    "subtitle": "One workflow. One team. A clear reason to keep it — or stop.",
    "minutes": 2,
    "notes": "Pick a repeating workflow, such as a customer demo dashboard or a prototype handoff. Agree what good looks like before running it. Track rework, missed requirements, handoff completeness and time spent maintaining the workflow. Use several comparable tasks, not only the most flattering run. Keep human review and the same underlying platform controls. Stop or simplify if the method costs more effort than the problems it prevents. A successful pilot gives us a reusable asset and evidence; an unsuccessful pilot gives us a useful boundary.",
    "showSubtitle": false,
    "evidenceLabel": "Several comparable tasks · same knowledge and controls",
    "cue": "One repeating workflow. Several comparable tasks. Then decide.",
    "stageAction": "Point at the four measurements on screen. Keep “what would make us stop?” rhetorical — the discussion is next.",
    "bridge": "Keep that recurring task in mind for the discussion."
  },
  {
    "id": "discussion",
    "chapter": "Make it yours",
    "type": "discussion",
    "title": "What are you tired\nof explaining twice?",
    "subtitle": "Pick one recurring task. Name the mistake. Decide what should remember it.",
    "minutes": 5.5,
    "notes": "Give the room a few seconds to think, then take one answer from a remote participant first. Ask for a specific recurring task rather than general enthusiasm about agents. Which part should be a skill? Which decision belongs in an ADR? Which mistake deserves a regression test? What would make this too heavy? The goal is not to collect a huge roadmap in four minutes. Choose one candidate workflow and an observable failure that a pilot could try to prevent. If there is disagreement, use it: different contexts may need different harnesses.",
    "showSubtitle": false,
    "evidenceLabel": "4 minutes · choose one pilot candidate",
    "cue": "What are you tired of explaining twice?",
    "stageAction": "Take a remote participant first. Choose one task, one recurring failure and what should remember it.",
    "bridge": "The method, sources and limitations are available after this session."
  },
  {
    "id": "take-it-with-you",
    "chapter": "Make it yours",
    "type": "handoff",
    "title": "The talk ends.\nThe toolkit stays.",
    "minutes": 0.5,
    "cue": "Four things to take forward. One available today; three links to follow.",
    "stageAction": "Name the four deliverables. Explain Core as the small, explicit workflow shell for a customer case. Point attendees to the public site.",
    "bridge": "Keep what supports the work. Make the useful part reusable.",
    "evidenceLabel": "Handoff roadmap · Core, CAIP pack and Benchmark links to follow",
    "notes": "You will get four things. Lintel is the full open-source harness. Pack number one adds the MS employee in CAIP context; its distribution link will follow. Lintel Core is the planned stripped-down shell for building a specific customer harness. The intention is explicit, on-demand use inside the customer’s existing coding desktop or CLI, including GitHub Copilot. It is useful when a person is driving a bounded workflow and a separate hosted agent or dedicated application would add unnecessary operational work. It does not replace hosted orchestration when you need unattended execution, shared services, durable infrastructure or platform controls.\n\nLintel Benchmark is the planned evaluation package; its link will follow too. The prepared A/B lab on this site is available now, but it is not a statistically established productivity benchmark. No private employee pack is included in this public site. The presentation, technical reference, notes and prepared browser demos can already be used here or downloaded as an offline kit."
  },
  {
    "id": "close",
    "chapter": "Make it yours",
    "type": "close",
    "title": "Keep the creativity.\nStop paying twice.",
    "subtitle": "For the same explanation. The same decision. The same mistake.",
    "minutes": 0.5,
    "notes": "Close on the practical loop. Three rows, three things we keep paying for twice. The same explanation: write the plan and the handoff where the next session can read them. The same decision: record why, not only what. The same mistake: capture the lesson and give it a test. State the intent. Make the work inspectable. Keep the decisions alive. Retrieve the right lessons. Verify what matters. Lintel is my attempt to make that loop reusable across the tools I work in. It does not replace engineering judgment; it gives that judgment somewhere durable to live. Invite the team to inspect the actual prepared outputs and the comparison protocol in the package; the repository address is on screen. If we named a task in the discussion, try it on that one and tell me what it cost. End on time.",
    "showSubtitle": false,
    "evidenceLabel": "Structure that supports the work.",
    "cue": "Keep the creativity. Stop paying twice.",
    "stageAction": "Do not read the rows; give today’s example for each: the 09:12 agreement, the rejected option B, the tenant leak. Pause. End on time."
  },
  {
    "id": "product-family",
    "chapter": "Product launch",
    "track": "products",
    "optional": true,
    "type": "productfamily",
    "title": "Meet the Lintel family.",
    "minutes": 0.75,
    "cue": "Four packages, with a different job for each.",
    "stageAction": "Pause on the four motifs. Name each product once. Click an image to open the standalone artwork; each product label jumps to its slide.",
    "bridge": "Start with the complete system.",
    "notes": "Four products, four jobs. A portal for the complete system, layers for team context, an open frame for a focused workflow, and a reticle for measurement. Same family, different responsibilities. Think Unix philosophy, with slightly better lighting.\n\nLintel is the complete harness. The CAIP Pack brings our role and team context. Core is the planned smaller shell for a specific customer case. Benchmark is the planned way to test whether the added process is worth it.\n\nThey have different release states. Lintel is available in the public repository. The CAIP Pack distribution link will follow. Core and Benchmark are planned offerings; we will add their links later. The prepared comparison in this presentation is already available, but it is not the complete Benchmark product.",
    "evidenceLabel": "Product family · Core and Benchmark planned",
    "eyebrow": "THE PRODUCT FAMILY"
  },
  {
    "id": "product-lintel",
    "chapter": "Product launch",
    "track": "products",
    "optional": true,
    "type": "productlintel",
    "title": "One task.\nA useful first session.",
    "minutes": 1.5,
    "cue": "Start with an accepted change, not a tour of every command.",
    "stageAction": "Walk select → plan → verify → resume. Link to the getting-started guide.",
    "bridge": "The pack supplies the organisation-specific starting point.",
    "notes": "Choose a reviewed revision and exact client adapter. Use the manual START file if native discovery is unavailable. Plan a bounded health endpoint with an acceptance test. Inspect conventions, authorize the plan, execute the package and obtain separate review.\n\nThen start a fresh session and verify the same work and next action. This is the first useful installation test: an accepted result and usable handoff. The current guide has the complete walkthrough. Installed files alone do not prove host discovery or execution.",
    "evidenceLabel": "Public beta · reviewed source + exact client pilot",
    "eyebrow": "01 / LINTEL",
    "subtitle": "Start with a bounded change, then inspect the trail.",
    "showSubtitle": true,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/getting-started.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/client-adapters.md"
    ]
  },
  {
    "id": "product-caip",
    "chapter": "Product launch",
    "track": "products",
    "optional": true,
    "type": "productpack",
    "title": "Your role.\nAlready in the room.",
    "minutes": 1,
    "cue": "The CAIP Pack brings team context to the universal method.",
    "stageAction": "Read the workshop request, then trace the added context to a more relevant brief. Describe this as the pack’s intended use.",
    "bridge": "What if a customer only needs one focused workflow?",
    "notes": "Imagine the request: prepare a customer technical workshop. Without the relevant team context, the agent has to rediscover the audience, expected evidence and our way of working.\n\nThe purpose of Lintel CAIP Pack, Pack number one, is to carry the MS employee in CAIP role and the approved team knowledge and standards that belong with it. The universal method stays in Lintel. The team-specific content stays in the pack. The example on this slide shows the intended value, not a live execution of a released pack.\n\nFor a solution engineer or architect, this could mean a workshop brief that starts with the right audience, a useful technical agenda and explicit questions still to resolve. The operator remains responsible for the customer context and approved inputs.\n\nThe pack’s distribution link will follow. This public presentation contains no private employee pack.",
    "evidenceLabel": "Lintel CAIP Pack · MS Employee in CAIP · Distribution link to follow",
    "eyebrow": "02 / LINTEL CAIP PACK"
  },
  {
    "id": "product-core",
    "chapter": "Product launch",
    "track": "products",
    "optional": true,
    "type": "productcore",
    "title": "One customer case.\nA smaller harness.",
    "minutes": 1.5,
    "cue": "Core is the planned shell for a focused workflow inside the customer’s coding app.",
    "stageAction": "Trace the explicit start, the chosen workflow and the reviewed artifact. Use architecture review as the example.",
    "bridge": "A smaller workflow still needs to prove that it helps.",
    "notes": "Core is the planned stripped-down version of Lintel. Start with the customer’s case and select only the context, workflow, records and checks it actually needs.\n\nThe intended interaction is explicit: a person asks to run the architecture-review workflow in the coding app they already use, including desktop GitHub Copilot. The harness helps produce a review and decision brief, with enough state to return to the work. It does not need to invoke itself automatically. That is the design intent for Core, not a claim that every host or existing full Lintel install already behaves this way.\n\nThis can avoid maintaining a separate application or hosted agent flow for a bounded, person-driven task. It still takes ownership, versioning and testing. It is not zero maintenance.\n\nWhen a case needs unattended execution, shared services, durable jobs or enforced platform controls, hosted infrastructure still has a job. The question is which runtime the use case requires. Core’s distribution link will follow.",
    "evidenceLabel": "Lintel Core · Planned shell · Explicit invocation is the design intent",
    "eyebrow": "03 / LINTEL CORE"
  },
  {
    "id": "product-benchmark",
    "chapter": "Product launch",
    "track": "products",
    "optional": true,
    "type": "productbenchmark",
    "title": "Does the harness\nearn its place?",
    "minutes": 1.25,
    "cue": "Benchmark should measure accepted work, including the cost of the harness.",
    "stageAction": "Point at what stays the same and what changes. Name the four measures. Open the prepared comparison only if time allows.",
    "bridge": "Choose one recurring task and measure the result.",
    "notes": "Lintel Benchmark is the evaluation direction. The current kitchen harness now defines three arms: Naked Copilot, Lintel serial and Lintel + Swarming. All share the Service House brief and 32 requirements for 100 points. It records usable UI, declared completion, requirement coverage and billed credits separately.\n\nThe harness and reference/control checks exist locally. The public page describes the method; it does not bundle the local server, publish trial/session records or claim completed comparative runs. The distribution link remains pending. This is not evidence of a productivity win. Normal Lintel versus naked also changes delegation/model mix; keep the caveat visible and repeat with matched models if isolating that effect.",
    "evidenceLabel": "Kitchen harness prepared · comparative results and distribution pending",
    "eyebrow": "04 / LINTEL BENCHMARK"
  },
  {
    "id": "tech-kit",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techkit",
    "title": "Open the toolbox.\nChoose a small working set.",
    "minutes": 1,
    "cue": "The current source has 96 skills, 69 roles and 33 hook scripts. The point is a smaller set of overlapping commands, with useful methods retained.",
    "stageAction": "Read the three counts once. Distinguish a source inventory from tools actually loaded or executed.",
    "bridge": "What matters is how a task moves through that library.",
    "notes": "This module follows source 49f2d15260f096213086f02dfeb1fae6cbe62d45. Its 0.12.0 changelog is unreleased. The current census is 96 canonical skills, 69 agent roles and 33 hook scripts. Generated wrappers are not extra canonical skills, and a file on disk is not proof that a host discovered or executed it.\n\nThe consolidation changed entrypoints. Inspection now uses inspect; verification uses verify; investigation uses diagnose; continuity uses pause and compatible resume. It retained useful capabilities, original task authority, saved work and provider contracts. The old 127-skill library and roughly 80 aspiration are historical context, not today's delivered count or ADR-0034's numeric target.\n\nA smaller inventory alone proves no productivity gain. Choose the working set needed for one outcome and verify the result.",
    "evidenceLabel": "Current source 49f2d152 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/CHANGELOG.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/CATALOG.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/.claude/decisions/0034-native-workflow-consolidation.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/migrations/2026-09-25-native-workflows.md"
    ]
  },
  {
    "id": "tech-skills",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techskills",
    "title": "Start with the loop.\nAdd depth on demand.",
    "minutes": 1.5,
    "cue": "One loop; explicit methods when the work needs more depth.",
    "stageAction": "Walk the four central phases, then give inspect, verify and web-session as consolidation examples.",
    "bridge": "The method stays coherent when ownership is clear.",
    "notes": "The nine-phase lifecycle remains. PLAN preserves original requirements and task IDs; BUILD groups connected short leaves into a bounded package with one implementer and evidence for every leaf. REVIEW checks specification, quality and applicable mandatory controls. CAPTURE reconciles reviewed knowledge and the handoff. A failed leaf keeps its package open.\n\nUse inspect for plan or repository lenses; verify is read-only by default and repairs need their actual authority; diagnose owns scoped investigation; cross-check uses a real independent reviewer. TA, DA, SC, DH and TQ remain, as does full-engineering-pass.\n\nweb-session brings browse, scrape, open and cookies behind explicit modes without replacing their actual providers. Frontend advice, variants and built-UI review remain under the design owners; generate-docs, generate-web and generate-pdf retain their outputs. Document-format acceptance remains staged. PDF printing is not PDF content or visual verification.",
    "evidenceLabel": "Current source 49f2d152 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/migrations/2026-09-25-native-workflows.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/build/SKILL.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/verify/SKILL.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/web-session/SKILL.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/.claude/decisions/0033-remove-document-format-acceptance-and-pdf-reader.md"
    ]
  },
  {
    "id": "tech-agents",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techagents",
    "title": "Clear ownership.\nIndependent challenge.",
    "minutes": 1.5,
    "cue": "A role carries expertise. Independent review needs a separate, attributable reviewer.",
    "stageAction": "Follow preparation, implementation and challenge. Separate the MARS review panel from the Swarm implementation diagram.",
    "bridge": "All of that work needs a place to leave its evidence.",
    "notes": "One implementer owns a bounded package. Reviews cover every original leaf and their integration. Substantive work needs actual independent review; a role name, another model name or a builder's self-review cannot manufacture it. Mechanical work can use the documented coordinator review.\n\nThe shared Review Method gives single REVIEW and each MARS participant the same frozen packet body: acceptance, standing questions, evidence levels, severity and coverage. MARS is an optional multi-model second look with consent and observed host capability. Reviewers work blind first; at most one challenge round follows contested claims. The coordinator judges source evidence rather than voting and preserves dissent. MARS itself never grants release clearance.\n\nSwarm is different: it schedules implementation packages. One coordinator owns shared state and integration. Concurrent writers need disjoint scopes and attributable worktrees, patches or equivalent isolation. Without that, replay the briefs serially. Lane reviews never replace the final integrated review.",
    "evidenceLabel": "Current source 49f2d152 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/agents/engineering/CodeReviewer.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/review/references/method.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/concepts/mars.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/concepts/swarming-work.md"
    ]
  },
  {
    "id": "tech-storage",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techstorage",
    "title": "Four places.\nDifferent responsibilities.",
    "minutes": 2,
    "cue": "Separate reusable source, configured home, project knowledge and local evidence.",
    "stageAction": "Toggle Bare install and Repo kit. Point out which records travel through Git and which do not.",
    "bridge": "Now follow those records through one cycle.",
    "notes": "LINTEL_SOURCE_ROOT identifies trusted helpers and templates; LINTEL_REPO_ROOT is the working consumer. The configuration home is explicit. Bare installation commonly uses ~/.lintel; repository adapters default to .claude/runtime/lintel-home when no home is configured. Their shared source bundle is .github/lintel. That repository kit installs no hook bundle.\n\nCommit reviewed project plans, decisions, lessons and handoffs intentionally. Runtime contains local cycle state, checkpoints, review/QA records, audit observations and MARS panels. A clone does not inherit ignored evidence or private packs.\n\nReview packet inputs can live under runtime/review/<id>; strict decision records use runtime/reviews. MARS uses runtime/mars/<panel>/inputs and records. Profile contexts keep versioned current-profile.json records under the configured home. A receipt records a local operation; it does not establish host activation, independent review or enforcement.",
    "evidenceLabel": "Current source 49f2d152 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/lifecycle.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/architecture.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/review/SKILL.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/mars/SKILL.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/lib/profile_context.py"
    ]
  },
  {
    "id": "tech-cycle",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techcycle",
    "title": "Each phase leaves\na usable record.",
    "minutes": 2,
    "cue": "The record carries the selected work and its evidence into the next phase.",
    "stageAction": "Start at PLAN. Select BUILD, REVIEW and CAPTURE. Use other tabs only if asked about paths.",
    "bridge": "The same records let a fresh session find the unfinished step.",
    "notes": "Start an explicit cycle identity and verified profile context before phase writes. The ledger carries the original map, artifact paths and policy reference. The work map indexes authority; it is not a duplicate backlog. Spec Kit keeps its original task IDs and files.\n\nBUILD records evidence per leaf and reviews each bounded package for spec compliance and then quality. One failed leaf keeps the package open and preserves useful completed evidence. BLOCKED returns to BUILD with the exact unresolved action.\n\nREVIEW sends the shared method packet and checks coverage, then persists content-bound v2 decisions and immutable QA obligations. A later rejecting or malformed applicable decision blocks an older pass. Missing mandatory validation or independent corroboration stays open. A complete report can still contain a failing verdict; a checker exit code alone is not a PASS.\n\nSHIP consumes current review and QA within existing authority. CAPTURE reaffirms actual outcomes and records warranted lessons or decisions. It cannot approve missing work or authorize a deployment.",
    "evidenceLabel": "Current source 49f2d152 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/spec-kit/references/work-map.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/build/SKILL.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/review/references/method.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/review/references/evidence.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/capture/SKILL.md"
    ]
  },
  {
    "id": "tech-resume",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techresume",
    "title": "Resume the work.\nKeep its identity.",
    "minutes": 1.5,
    "cue": "Pause saves continuity. Resume reads it alongside the original work and current evidence.",
    "stageAction": "Point to the committed map, then the original artifacts. Name the missing-review boundary.",
    "bridge": "Continuity helps; the actual client still decides which controls can run.",
    "notes": "Use pause to reserve a collision-safe, owned checkpoint. The compatible filename still ends in -context-save.md; old saved data is not renamed or deleted. Verify nonempty readback before claiming it was saved. resume --from <checkpoint> reads continuity context; it does not restore code, change branches or grant BUILD or SHIP authority. A bare phase or selected job-step keeps the existing override meaning; use an explicit path such as ./BUILD if a checkpoint name collides.\n\nExplicitly selected work wins over an unrelated local ledger or checkpoint. A fresh clone follows an unambiguous committed work map and its original artifacts, then reconciles actual checkout and acceptance evidence. It does not choose the newest file or fabricate lost evidence.\n\nResume verifies the original cycle, target and profile generation/digest. Missing or changed policy needs explicit reconciliation. STARTING, BLOCKED and NEEDS_CONTEXT return to the same unfinished phase. A truncated DONE cannot advance.",
    "evidenceLabel": "Current source 49f2d152 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/pause/SKILL.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/resume/SKILL.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/spec-kit/references/work-map.md"
    ]
  },
  {
    "id": "tech-hooks",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techhooks",
    "title": "Hooks react\nwhere they are registered.",
    "minutes": 2,
    "cue": "Thirty-three scripts have different jobs. Nine core registrations use the Claude Code protocol.",
    "stageAction": "Toggle core and optional. Use one blocker and one warning; leave the full inventory in the reference.",
    "bridge": "The same source reaches several surfaces through different discovery routes.",
    "notes": "The census remains 33 scripts: 9 registered core across 5 event types, plus 24 optional or manual scripts. Registration is not a firing test. The native bundle uses the Claude Code protocol; repository adapters install no hooks. Copilot's own hook facility does not mean Lintel has translated this bundle.\n\nThe two Git scanners deny supported commit/push requests on detected patterns or unavailable required collection/scanning. Warning hooks surface advice; they are not permission controls. Stop does not force continuation or write a checkpoint. The optional frozen-zone warning now uses code-freeze's shared validated state under repository runtime; it does not lock the filesystem. Context-bloat advice uses pause and resume.\n\nhooks-status reads receipts, while doctor --hooks-only diagnoses byte and activation state; neither establishes universal enforcement. Clean/no-record runs remain unobserved. The event catalog has 23 categories and 66 kinds, not 66 platform events.",
    "evidenceLabel": "Current source 49f2d152 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/hooks/hooks.json",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/hooks/shared/secret-scan-block/run.sh",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/hooks/shared/frozen-zone-warn/run.sh",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/hooks/shared/context-bloat-warn/run.sh",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/hooks-status/SKILL.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/lib/event-catalog.json"
    ]
  },
  {
    "id": "tech-clients",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techclients",
    "title": "One method.\nFour client families.",
    "minutes": 2,
    "cue": "Copilot, Claude, Codex and Cursor remain supported. Verify the exact surface you use.",
    "stageAction": "Select Copilot, then Codex to show the cloud/manual distinction. Avoid reading all paths aloud.",
    "bridge": "Portable discovery still needs the right project and policy context.",
    "notes": "The registry now has 14 records: 13 named surfaces across 4 supported families, plus other as an explicit manual fallback. Twelve records have native-format discovery and two are manual: Codex cloud and other. Four roots serve the supported families. Fifteen starter workflow wrappers include MARS; Copilot retains three native role profiles.\n\nOne .github/lintel bundle supplies selected repository routes. The installer does not change host settings, credentials or permissions and installs no hooks. Removed client-family IDs have no compatibility route; other is a manual handoff, not supported integration. Existing supported plugin routes remain.\n\nVendor documentation, delivered files and observed execution are separate. The registry retains three partial Copilot App observations. MARS has separate live-pilot evidence: RM9 observed four model identities but collected only three valid reports, so the panel remained partial and multi_model_verified:false. That one synthetic subject, without a challenge or live single-review comparison, does not certify every client or model.",
    "evidenceLabel": "Current source 49f2d152 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/.claude/decisions/0035-four-supported-client-families.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/lib/cli-tiers.yaml",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/bin/li-copilot.py",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/client-adapters.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/.claude/plans/mars/pilot-2026-09-25-rm9.md"
    ]
  },
  {
    "id": "tech-packs",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techpacks",
    "title": "Carry the policy\nwith the work.",
    "minutes": 1,
    "cue": "Preferences choose context. Required policy must stay intact from plan through delivery.",
    "stageAction": "Move require → resolve → verify. Point to platform permissions and CI as separately configured controls.",
    "bridge": "Then preserve what the next task can actually use.",
    "notes": "profile.yaml holds operator preferences such as role and mode. Required repository or explicit pack selection is different. The effective context binds actual source content, target, generation and digest. A pack name alone cannot establish that the same policy was applied.\n\nCarry the verified reference through selected work, children, review, QA and recovery. Missing required packs or changed policy do not silently fall back to neutral success. A deliberate switch/rebind records a reason, retains prior history and requires affected work to be reconsidered.\n\nPacks provide reviewed standards and context. Platform permissions, CI and live organizational enforcement remain their own configured and verified layer. Required-policy source tests are not an enterprise certification.",
    "evidenceLabel": "Current source 49f2d152 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/.claude/decisions/0029-required-profile-context.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/lifecycle.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/review/references/evidence.md"
    ]
  },
  {
    "id": "tech-maintenance",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techmaintenance",
    "title": "Keep useful knowledge.\nPreserve the evidence.",
    "minutes": 1.5,
    "cue": "A lesson helps only when later work retrieves and applies it.",
    "stageAction": "Walk capture, retrieve and preserve. Distinguish checkpoint continuity from owned-file recovery.",
    "bridge": "The pilot should verify this whole path, including failures.",
    "notes": "lessons-add checks existing entries before choosing add, update, supersede or no-op. Stable L-NNN IDs, a lock and a conditional write preserve ownership and history. There is no active operator-global lessons sink; old global JSONL is read-only legacy data. lessons-surface ranks active literal-keyword matches, then the agent reads and applies the full rule. Stored text or a ranked heading alone does not prove better outcomes.\n\nADRs record consequential choices and rationale, normally beginning Proposed. CAPTURE reaffirms the original mapped task outcomes and handoff rather than generating a competing backlog. Standalone retrospective and release-summary modes preserve their selected window and publication boundary.\n\nOwned snapshots protect recent copies, the newest five and incomplete operations. Pruning needs explicit eligible IDs and refuses unexpected content. Keep transaction receipts with their snapshots. This is bounded recovery, not a universal cleanup policy or a way to compact a model conversation.",
    "evidenceLabel": "Current source 49f2d152 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/lessons-add/SKILL.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/lessons-surface/SKILL.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/adr-new/SKILL.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/capture/SKILL.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/maintenance/SKILL.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/bin/li-snapshot.py"
    ]
  },
  {
    "id": "tech-proof",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techproof",
    "title": "Prove the route\nyou intend to use.",
    "minutes": 2,
    "cue": "Discovery, a real task, a cold restart and a failure case make the claim concrete.",
    "stageAction": "Read the four checks and finish with accepted outcomes and overhead.",
    "bridge": "Return to the main story or open the reference for questions.",
    "notes": "Pin source and client versions, actual tools, selected profile and permissions. Verify discovery, then run a bounded task with original requirements, acceptance evidence and the required independent review. Restart without the original conversation, select the same work and report the actual unmet step.\n\nNegative cases matter: changed policy, skipped mandatory QA, missing independent reviewer, later rejecting decision, ambiguous work map and edited managed files. For MARS, a changed brief, substituted model or incomplete panel must remain visible. For Swarm, missing attribution means serial work and missing review leaves the lane open.\n\nThe committed Universal report now records 109/109 in-scope items and its final 22-job CI run. Document acceptance removed by ADR-0033 was removed, not passed. Current source still labels the development line unreleased and records platform/runtime limitations; this presentation does not rerun or widen those acceptance claims. Historical demonstrations retain their original source pins.\n\nMeasure accepted-change time, interventions, defects, rework, recovery and total process cost under comparable conditions. Neither contribution counts, skill counts nor token guesses establish productivity.",
    "evidenceLabel": "Current source 49f2d152 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/.claude/plans/universal-implementation/reports/final.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/CHANGELOG.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/review/references/evidence.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/concepts/swarming-work.md",
      "https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/skills/mars/SKILL.md"
    ]
  }
];
