window.DECK_SLIDES = [
  {
    "id": "three-hours",
    "chapter": "Meet Lintel",
    "type": "systemcover",
    "title": "We had a plan.\nThe AI had\nother plans.",
    "subtitle": "Ever had to explain the same plan twice?",
    "minutes": 1,
    "notes": "I am Johannes, a Solution Engineer. This is my personal engineering project and the journey behind it. You write a detailed plan. Hours later the agent is doing something impressive, but it is no longer the thing you asked for. Or it stops and you have to reconstruct what was happening. Today I want to show the system I built around that frustration, then test where it adds value. The exchange on screen is an illustration, not a recorded benchmark. Lintel is a personal open-source project, not a Microsoft product.",
    "showSubtitle": true,
    "evidenceLabel": "Illustrative conversation",
    "cue": "Who has corrected an AI on something you agreed three hours ago?",
    "stageAction": "Pause for hands, including Teams. Let the dashboard-to-platform joke land. Introduce yourself in one sentence.",
    "bridge": "Let me show you the whole system before we open any of its parts.",
    "eyebrow": "Lintel · Taming the wild beast"
  },
  {
    "id": "what-is-lintel",
    "chapter": "Meet Lintel",
    "type": "systemmap",
    "title": "Here’s the whole system.",
    "subtitle": "A workflow kit inside the coding tools you already use.",
    "minutes": 1.5,
    "notes": "Start at the top: you supply the outcome and important choices. Your coding client runs the model and tools. Inside that environment, Lintel provides a reusable method. The agent loads a relevant skill and, where supported, delegates a focused agent role. A pack supplies team standards and knowledge. Registered hooks react to selected host events. The agent and invoked helpers update project scaffolding: plans, decisions, lessons and a handoff. Compounding is the return path: retrieve the relevant record before the next task. The kit and pack can be installed for you or the repository; the project records belong with that project. Temporary execution state is separate and Git-ignored. Permissions and CI remain platform controls. This is an architecture overview, not a promise that every client loads every resource. The inspected Lintel hook bundle uses Claude Code registration; Copilot hook parity is a separate implementation plan. CLI, editor and desktop describe possible host surfaces, not identical feature coverage. MDASH and AGT address different jobs; this workflow kit does not replace them. We will return to that boundary after the orientation.",
    "showSubtitle": true,
    "evidenceLabel": "Hook coverage depends on the client and verified activation.",
    "cue": "Your agent does the work. Lintel gives it a method and a useful trail to leave behind.",
    "stageAction": "Read the map top to bottom. Point to the team pack, then follow the return line from project records into the next task.",
    "bridge": "Six names appear in that map. Here is what each one means."
  },
  {
    "id": "inside-the-kit",
    "chapter": "Meet Lintel",
    "type": "buildingblocks",
    "title": "Six parts. One working system.",
    "subtitle": "",
    "minutes": 1,
    "notes": "Scaffolding gives the project places for instructions, plans, decisions, lessons and handoffs. The method defines the workflow and when clarification or review is needed. Skills are reusable recipes for jobs such as architecture, technical review or testing. Agent roles provide focused expertise; separate execution depends on host support. Hooks are registered event checks, not an intelligent observer of everything. Compounding means a reviewed lesson or decision is retrieved and applied to later relevant work. A team pack changes the standards and context across these parts. Compounding needs retrieval and verification; accumulating more files alone does not create value.",
    "showSubtitle": false,
    "evidenceLabel": "Load the parts the task needs.",
    "cue": "Scaffolding is where it lives. The method says how to work. Compounding brings useful learning back.",
    "stageAction": "Use one short sentence per part. Explain that an agent role is a job description and a hook reacts to an event.",
    "bridge": "The useful bit is how these parts maintain the trail while the work happens."
  },
  {
    "id": "state-loop",
    "chapter": "Meet Lintel",
    "type": "stateflow",
    "title": "The work leaves a way back.",
    "subtitle": "The method requires a trail. Skills and agents write it as they work.",
    "minutes": 2,
    "showSubtitle": true,
    "evidenceLabel": "Illustrative walkthrough · no agent or hook is executing here.",
    "cue": "The agent should not need your memory to find its next task.",
    "stageAction": "Click through the three example steps: clarification, saved decision, fresh session. Explain who asks and who writes. Keep the registered-hook lane separate.",
    "notes": "The method requires the agent to clarify material ambiguity, record consequential decisions, keep the plan current and capture evidence. Skills turn those requirements into concrete instructions; agents and local helpers perform the writes. They maintain the existing scaffolding instead of inventing a new memory store. This example begins with an export task and an unresolved date boundary. The workflow surfaces the ambiguity and the agent asks whether dates use UTC or local time. The human answers UTC. The agent records that decision, updates the task and identifies the boundary test as the next action. A compatible SessionStart hook can surface a digest, and a prompt-position hook can reassert the current step. A fresh agent still reads and checks the authoritative files before continuing. Hooks run only on exposed and registered events. A hook may warn, supply context or block selected operations, according to its actual contract; it does not itself understand every uncertainty or guarantee that a question is asked. Stop warnings do not force auto-continuation. Keep reviewed decisions and handoffs with Git; keep temporary counters and runtime ledgers ignored. The quality comes from both writing and reading the trail.",
    "bridge": "Why does that trail matter so much? Because each session has a limited window."
  },
  {
    "id": "context-primer",
    "chapter": "Meet Lintel",
    "type": "primer",
    "title": "A fresh session.\nA new window.",
    "subtitle": "Everything the agent knows about your project has to fit in here — right now.",
    "minutes": 1.5,
    "notes": "Three words. An agent is an AI model that can read your repository, edit files and run commands with your permissions — GitHub Copilot’s agent mode, Claude Code and Codex are examples. Its context window is everything the model can see at this moment: loaded instructions, your request, files it has read, tool output and the conversation so far. It is finite. A session is one working conversation; a fresh session needs its working context loaded again. Memory features do not change this: they are stored text that gets loaded back into the window. Now click Three hours later. The window has filled with tool output, new files and a long conversation. The 09:12 agreement is still somewhere in the log, but it has been crowded out: depending on the tool it is compacted, truncated, or simply gets less attention among everything else. That is a large part of what happened in the opening conversation — not stupidity, not malice. The last line on screen is the important one: files in the repository are still there in the next session. Most of what follows today is a consequence of that: put what matters where the next window can find it. This is a simplified illustration with invented counts; tools manage context differently, and a larger window delays the problem rather than removing it.",
    "sources": [
      "https://www.trychroma.com/research/context-rot"
    ],
    "showSubtitle": true,
    "evidenceLabel": "Simplified illustration · invented counts · tools manage context differently",
    "cue": "The model works with the context it can see right now.",
    "stageAction": "Give an example for each word rather than reading the definitions. Click “Three hours later”. Point at the crowded-out line, then at the files.",
    "bridge": "That is why I stopped trying to be the project’s memory myself."
  },
  {
    "id": "journey",
    "chapter": "Meet Lintel",
    "type": "journey",
    "title": "I became a very expensive\ncopy-and-paste loop.",
    "subtitle": "The progression that led me to Lintel.",
    "minutes": 0.5,
    "notes": "My first fix was the obvious one: better prompts. Then I noticed I was pasting the same expectations into every repository and every session — I had become the memory. The shift was to make the useful method durable: written down in the repository, where the next session can find it without me. This describes the pattern; I am not claiming a measured productivity gain or inventing a personal incident.",
    "showSubtitle": false,
    "evidenceLabel": "A pattern, not a measured result",
    "cue": "My first fix was the obvious one: better prompts.",
    "stageAction": "Move through the three stages and let the “lives in” line do the work. Land “Chief Repetition Officer” at step two.",
    "bridge": "Here is the actual workflow behind that durable method."
  },
  {
    "id": "the-cycle",
    "chapter": "Meet Lintel",
    "type": "cyclemap",
    "title": "Right code.\nWrong problem.",
    "subtitle": "Nine steps. Five of them before a line of code is written.",
    "minutes": 1,
    "notes": "Spoken path — red tab, lime tab, the two flags, the slips. Nothing in those three hours was bad code. It was good work on the wrong thing, and this is where you found out. Same misunderstanding — but here you can find it on paper, in minutes. So the playbook is lopsided on purpose: nine steps, five of them before any code, and before any code it stops for you at least twice: the design, then the plan with a token estimate. Not hours, not money. And every step leaves something written, because the chat will not survive the session; written things can. Lintel calls this line the cycle. You do not need to learn nine names. Learn the shape.\n\nReference for questions: Lintel’s own documentation says it directly — the expensive failures in agent-driven work are correct code built against the wrong premise, discovered three hours later. SENSE reads the situation and ends with a suggested route, which is the next screen. SCOPE sizes the request and asks at most one question. DEFINE produces an approved design, not a draft. DISCOVER only reads: existing decisions, lessons and patterns. PLAN writes three files together: checkable tasks, what done means, and a brief for a fresh session. REVIEW is deliberately adversarial: spec, quality, team standards. SHIP opens a pull request by default. CAPTURE keeps lessons, a decision record and the working notes the next session picks up — the handoff — which a later DISCOVER can find; that is why it is a cycle. Every “skip it and” line is that step’s own declared cost from the documentation, not a measurement.\n\nClaim boundaries: “at least twice” is deliberate. On a full run you are asked to confirm the route after SENSE, possibly one sizing question, then the design, the plan, and an estimate shown before BUILD — a task count and a token estimate labelled uncalibrated, never money or time. An approval gives you the chance to catch a wrong premise; it does not catch it for you. These are instructions the agent is told to follow; real enforcement is the platform’s, which is why there is no lock on this screen. “Leaves something written” does not mean committed: the situation report and the sized request are temporary working state, and a later screen draws that line. Swarming is an optional way to run PLAN, BUILD and REVIEW, not a tenth step. The strip is the illustrative opening conversation, not a measured run.",
    "showSubtitle": false,
    "evidenceLabel": "Workflow instructions · checks and platform controls do the enforcing · chat strip illustrative",
    "cue": "Remember the platform nobody asked for? Look at where you found out.",
    "stageAction": "Pointer only — no clicks, no question to the room. Same order as the spoken path: 1 · the red tab, top right. 2 · the lime tab on the first approval. 3 · the two flags, left of the dashed line. 4 · one sweep along the slips. The approval is your chance to find the mistake: never say it finds it for you. Do not name the nine steps or recite the panel. Ahead of time: click CAPTURE once. Behind: drop the sweep.",
    "eyebrow": "Meet Lintel · the cycle",
    "bridge": "And about now, somebody is thinking: that is a lot of steps."
  },
  {
    "id": "short-routes",
    "chapter": "Meet Lintel",
    "eyebrow": "Meet Lintel · shorter routes",
    "type": "routes",
    "title": "Nine steps\nfor a typo?",
    "subtitle": "SENSE reads the request and suggests a route. You confirm it.",
    "minutes": 1,
    "notes": "Spoken path — no click needed. No. And look what that suggestion rests on: one word. SENSE matched “fix” — that is all the routing is today, keyword rules. So it suggests the short route: build, review, ship. Four of nine; the skipped steps are still drawn, marked as skipped. And it only suggests: the person marker on the line is you, and by default nothing else runs until you say proceed. Research gets three steps and no build. A small feature gets all nine, but a flat plan. And it works the other way: “deploy” sounded like one step. It cannot tell a web page from a landing zone, so it asks once — and the answer sent it the long way.\n\nReference for questions: the documentation’s own heading is “you rarely need all nine”. hotfix is SENSE, BUILD, REVIEW, SHIP, for a known bug with a clear fix. research-dive is SENSE, DEFINE, DISCOVER: understand first, no code yet. A build request gets the full cycle; a clearly small one is sized small, so the plan stays a flat task list and SCOPE asks nothing. Before any code is touched you see what will run, what is skipped and a token estimate, then Proceed? [Y/n/edit]. How to ask for it: run the cycle with your request and SENSE suggests; or name the mode yourself, which always wins; the field guide has the exact spellings per tool. You can also enter at a step, stop early or drop one, and the workflow is told to check dependencies first: BUILD needs a plan, REVIEW needs a diff, SHIP needs a passed review. Any single step can run on its own — the answer to “does a hotfix never record a lesson?” is: run CAPTURE afterwards. A hotfix keeps REVIEW and SHIP.\n\nClaim boundaries: routing is first-match keyword rules; the slot for asking a model is a stub today. “Confidence high” only means a word matched, including the wrong one. The headline is true because of the word fix: “Correct the typo on the export button.” matches nothing, comes back unclear and falls to the full cycle, so you choose or name the mode. Do not improvise requests live: “Add error handling” routes as a fix. Later screens say depth follows risk: that is the principle; today’s implementation is a keyword guess plus your judgement at the confirm prompt, which is why the person marker is part of the picture. Say “by default”: the neutral setup confirms every route, but a team’s standards can allow low-risk routes to start on their own. The size check exists only where SCOPE runs, so not on hotfix or research-dive. Row four is conditional: it is re-routed only if you pick the large reading and nothing is built yet; pick small and the ship route stands. Say it cannot tell, so it asks — never that it noticed its mistake. The question’s wording is illustrative, adapted from the repository’s own example. The skipped-step marker is an instruction to each step, backed by a hook only in Claude Code. In the GitHub Copilot kit the same cycle and modes run, commands are spelled with a dash, and there is no separate fix shortcut — which is why this screen names modes and steps, not commands. The four requests are illustrative; they were checked against the real matching and sizing rules, they are not recorded runs. Routing is advice written in instructions. Nothing here is a lock.",
    "showSubtitle": false,
    "evidenceLabel": "Illustrative requests · keyword rules today · SENSE recommends, you confirm · an explicit mode always wins · workflow instructions, not enforcement",
    "cue": "No. And look what that suggestion rests on.",
    "stageAction": "Pointer, top to bottom — no click needed, no question to the room. 1 · the marked word “Fix”. 2 · along row one’s rail: one lit, the person marker, a jump, three lit. 3 · the lime YOU chip. 4 · the Deploy row’s tag: struck first guess, one question, the long way. Let the pointer fall past rows two and three. Ahead of time: click the Deploy row for the question and both outcomes. Say it cannot tell, so it asks — never that it noticed. Never improvise a request live.",
    "bridge": "So which parts of that trail travel to the next session?"
  },
  {
    "id": "where-it-lives",
    "chapter": "Meet Lintel",
    "type": "storage",
    "title": "Your setup.\nYour project’s memory.",
    "subtitle": "What stays on your machine? What travels with Git?",
    "minutes": 1,
    "showSubtitle": false,
    "evidenceLabel": "Representative Lintel layout · adapter-specific files vary",
    "notes": "Remember the window: files are what survive a session. This is where Lintel puts them. Point to the left first: machine-global means reusable across projects on this computer. The ~/.lintel/ home contains your profile and installed packs, as well as operator-wide records. Your coding client owns its own settings, tools and permissions; ~/.claude/ is a Claude-specific home, not a universal home for every app. Now point right: the project repository keeps reviewed memory, decisions, plans and handoffs under its declared paths. In the standard Lintel layout that is .claude/memory/, .claude/decisions/ and .claude/plans/. Commit the appropriate reviewed knowledge so Git can carry it to the next person or session. The dashed area is .claude/runtime/: temporary execution state is ignored and does not travel in a normal clone. The .claude folder name does not require Claude Code. Client adapters (the few files that teach one coding tool where to find all this — next screen) can add their own files; the Copilot repository kit uses .github/copilot-instructions.md, .github/skills/, .github/agents/ and .github/lintel/. Those details are in the field guide. Your global profile and installed packs do not automatically appear on a colleague’s machine through Git. The active pack must be available and configured there. The point is to separate reusable operator context, portable project knowledge and disposable run state.",
    "cue": "Your setup stays with you. The project’s reviewed knowledge travels with the project.",
    "stageAction": "Trace left → right, then the Git arrow. Point to the dashed runtime box last.",
    "bridge": "Almost none of this is tied to one coding tool. I will show you the exception."
  },
  {
    "id": "supported-tools",
    "chapter": "Meet Lintel",
    "type": "clients",
    "title": "Keep your coding tool.\nShare the working method.",
    "subtitle": "CLI, editor or coding desktop app — through the adapter that fits.",
    "minutes": 1,
    "notes": "Lintel’s direction is universal. This screen describes the integrations declared in this repository snapshot, not a promise that every feature behaves identically in every client. Native skill integrations are declared for Claude Code, Codex CLI and App, Cursor, GitHub Copilot CLI and Factory Droid. Gemini CLI and OpenCode use explicit workflow-file references in the current Lintel integration. Cline, Continue and Aider are best-effort. The Copilot repository kit is a separate adoption route for VS Code, CLI and cloud-agent work. In plain language, an adapter teaches the client where to find the shared instructions. The detail that matters is hooks: scripts the tool runs automatically at a set moment, for example before a commit. Lintel’s hook bundle is supplied for Claude Code; it does not automatically follow the method to other hosts. The full declared matrix is behind the button, for anyone who wants the exact differences. A practical detail: in the Copilot repository kit the planning skill is called /li-plan; other hosts can expose different command names. Install and validate the appropriate adapter in a pilot repo first.",
    "showSubtitle": true,
    "evidenceLabel": "Repository-declared integrations · capabilities vary",
    "cue": "Keep your tool. Reuse the method. Verify what this host actually supports.",
    "stageAction": "Point to the hook boundary. Open the matrix only if asked.",
    "bridge": "One more thing: what this is not."
  },
  {
    "id": "not-one-ring",
    "chapter": "Meet Lintel",
    "type": "guild",
    "title": "No single harness.\nNo magic ring.",
    "subtitle": "Different tools. Different jobs. Plenty of room at the table.",
    "minutes": 0.5,
    "notes": "Now you know what kind of thing Lintel is. A harness, by the way, is just the scaffolding around a model: the instructions, tools and checks it works inside. Before we go deeper: MDASH is awesome, AGT is cool, and this is not a replacement pitch. We have seen other useful approaches in Tech SHOTs. Different problems deserve different tools. Today we are examining the working method around development. One harness to rule them all would probably need a migration plan and three steering committees.",
    "showSubtitle": false,
    "evidenceLabel": "Positioning, not a feature comparison",
    "cue": "MDASH is awesome. AGT is cool. Different problems deserve different tools.",
    "stageAction": "Deliver the magic-ring joke orally; do not turn this into a competitor matrix.",
    "bridge": "Now the ideas underneath — useful with or without Lintel."
  },
  {
    "id": "what-how-why",
    "chapter": "The method",
    "type": "triad",
    "title": "What. How. Why.\nThen make it compound.",
    "subtitle": "A working contract the next session can actually use.",
    "minutes": 1,
    "notes": "Here is the method in three words, and it maps onto the cycle you just saw: What is what DEFINE writes down, How is PLAN through REVIEW, and Why is what CAPTURE keeps. WHAT is the intended result and its boundaries: who is this for, what changes, and what does done mean? HOW is the work: a plan at an actionable level, a repeatable workflow, and specific review and verification steps. WHY is the decision context: constraints, rejected alternatives and the reason we chose this approach. Then compound: capture a correction, retain the decision, and retrieve it when the next task matches. The workflow asks for these artifacts. The artifact itself is not a guarantee of quality. Evidence and review have to make the contract real.",
    "showSubtitle": false,
    "evidenceLabel": "",
    "cue": "What are we building, how do we verify it, and why this approach?",
    "stageAction": "Point once to each word; explain compounding with the return arrow.",
    "bridge": "Writing that contract once is fine. Writing it for the fifth time is the problem."
  },
  {
    "id": "repeat-yourself",
    "chapter": "The method",
    "type": "reuse",
    "title": "Your fifth dashboard\nshould remember the first.",
    "subtitle": "Repeat the useful method. Revisit the actual requirements.",
    "minutes": 1,
    "notes": "Imagine building dashboards across five repos. Each time you ask for sensible empty states, meaningful time axes, accessible charts, correct filtering and exports that match the screen. Those are recurring review questions. A reusable skill can carry them once. It should not blindly carry the previous customer's requirements or architecture. The reusable part is the decision procedure: what to inspect, what to ask, what evidence to produce and when to stop. Click Package the pattern. The invariant checks move into the skill; the new repo's data, audience and constraints still enter every time. This is deliberate reuse, not copy-paste architecture.",
    "showSubtitle": false,
    "evidenceLabel": "Illustrative skill pattern",
    "cue": "The fifth dashboard should reuse the questions, not inherit the first customer’s answers.",
    "stageAction": "Click Package the pattern once. Mention empty states and export consistency.",
    "bridge": "A skill carries the method. It still has to fit in the window."
  },
  {
    "id": "context",
    "chapter": "The method",
    "type": "context",
    "title": "The context window\nis not a junk drawer.",
    "subtitle": "Give the next decision what it needs — and a way back to the source.",
    "minutes": 1,
    "notes": "Back to the window from the beginning. If it is finite, what goes into it is a design decision. This is an interactive illustration, not a token benchmark. Start with everything included: old plans, unrelated lessons, a superseded decision. Click Curate context. Keep the approved scope, current task, relevant decision and matching lesson. Retain source pointers so the agent can inspect more if needed. Context engineering is not just reducing size; it is selecting, structuring and refreshing what matters. Chroma's context-rot experiments and Anthropic's context-engineering discussion motivate this pattern, but neither is a benchmark of Lintel. More text and better context are different objectives.",
    "sources": [
      "https://www.trychroma.com/research/context-rot",
      "https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents"
    ],
    "showSubtitle": false,
    "evidenceLabel": "Selection illustration · not a model benchmark",
    "cue": "More context is easy. Useful context requires a choice.",
    "stageAction": "Click Curate. Identify the four retained records and their source pointers.",
    "bridge": "Right context, right method. The last ingredient is the size of the work."
  },
  {
    "id": "granularity",
    "chapter": "The method",
    "type": "granularity",
    "title": "Small steps.\nA coherent piece of work.",
    "subtitle": "Granular enough to verify. Coarse enough to move.",
    "minutes": 1,
    "notes": "We chose a hybrid. Short implementation tasks, often intended to be around two to five minutes, sit inside a coherent work package. That time is a planning heuristic, not a promise about model or developer speed. The package has an owner, dependencies and an observable acceptance condition. We execute and review the coherent unit, rather than creating a meeting for every tiny edit. For the dashboard, a useful package is consistent filters and export. Its tasks clarify semantics, centralize filtering and check the exported result. Risk sets review depth. A color change and a tenant-boundary change should not get identical ceremony.",
    "showSubtitle": true,
    "evidenceLabel": "Review depth follows risk",
    "cue": "Small steps inside one outcome we can actually review.",
    "stageAction": "Trace the three tasks, then read the acceptance line. Explain the 2–5 minute heuristic orally.",
    "bridge": "That is the method. Time to find out whether it makes any difference."
  },
  {
    "id": "experiment",
    "chapter": "The kitchen demo",
    "type": "experiment",
    "title": "Same brief.\nTwo finished dishes.",
    "subtitle": "The build is prepared. The inspection happens together.",
    "minutes": 1,
    "notes": "We are doing this TV-chef style. Both builds have already run; you do not have to watch a model type for fifteen minutes. We preserve the exact implementation prompt, starting material and available stakeholder answers. Each arm gets its own fresh agent context. One works with the ordinary brief; the other receives the curated Lintel workflow instructions. The baseline is allowed to do a good job. We are inspecting one paired demonstration, not claiming a causal benchmark of every model or tool. The rubric is frozen before the runs. We will show both strengths and misses.",
    "showSubtitle": false,
    "evidenceLabel": "Two prepared agent builds · one paired example",
    "cue": "The cooking is done. Now we taste both dishes.",
    "stageAction": "Say the baseline is competent and allowed to win. Introduce the equal inputs.",
    "bridge": "Here is the brief both agents received."
  },
  {
    "id": "brief",
    "chapter": "The kitchen demo",
    "type": "brief",
    "title": "A dashboard.\nHow hard can it be?",
    "subtitle": "The dangerous words are usually the ordinary ones.",
    "minutes": 1,
    "notes": "Ask the room first; then open the exact prompt rather than relying on the shortened paraphrase. The request asks for a support dashboard with a selected customer, useful charts and an export. Before showing the results, ask the audience: what does active mean? What does customer isolation mean here? Should the export honor all filters? What is the date boundary? The available answer sheet is identical for both arms. The point is to observe whether the workflow makes those questions visible and turns the answers into implementation and checks. These are recorded agent discoveries using supplied answers, not a staged human conversation.",
    "showSubtitle": false,
    "evidenceLabel": "Paraphrase above · exact shared prompt linked",
    "cue": "Which ordinary word hides the biggest assumption?",
    "stageAction": "Ask the room before opening the exact shared prompt.",
    "bridge": "Hold on to your guesses. Let’s open both results."
  },
  {
    "id": "results",
    "chapter": "The kitchen demo",
    "type": "results",
    "title": "Looks good.\nNow make it answer questions.",
    "subtitle": "Open both finished apps. Try the same actions in each.",
    "minutes": 4,
    "notes": "Open the ordinary build first, then the Lintel build. Use the same clicks, same customer, same date range and same export. Ask the audience what they notice, but separate visual preference from functional behavior. Use the prepared common checks as the source of truth; do not invent a failure on stage. If both handle a case correctly, say so. Show the implementation result before the process artifacts so the audience has a concrete object to reason about. Keep the demo modal within the presentation; Escape returns you to this slide. At four minutes, move on even if there are more styling preferences to discuss.",
    "showSubtitle": true,
    "evidenceLabel": "Actual frozen outputs · same inputs and checks",
    "cue": "Let’s make both apps answer the same questions.",
    "stageAction": "Use identical customer, date and CSV actions. Escape closes each app. Four minutes maximum.",
    "bridge": "Both hold up. So look one layer down: what did each agent ask before it wrote code?"
  },
  {
    "id": "questions",
    "chapter": "The kitchen demo",
    "type": "questions",
    "title": "The best line of code\nwas a question.",
    "subtitle": "An ambiguity only helps when it becomes a decision.",
    "minutes": 3,
    "notes": "Use the three tabs to present one question → decision → check trace at a time. Then open each run's question log. Compare what was actually identified, rather than pretending the baseline asked nothing. Follow one question all the way through: the ambiguous word, the stakeholder answer, the planned acceptance condition and the code or test that uses it. The logs distinguish actual questions or discoveries from assumptions. No invented dialogue. If both runs discover the same issue, the difference may be how explicitly it survives into the work, or there may be no difference at all. This is where a thin plan often fails: a label such as add filtering can hide several unresolved contracts. In the recorded final pair, both arms identified the shared ambiguities; the baseline additionally recorded malformed-data handling. Use that as evidence that good project context matters in both setups.",
    "showSubtitle": false,
    "evidenceLabel": "Both runs surfaced these ambiguities.",
    "cue": "Both runs found useful questions. Follow what happened to the answer.",
    "stageAction": "Use the tabs. Open actual logs. Pick one trace rather than reading every entry.",
    "bridge": "A question only matters if it survives into the plan."
  },
  {
    "id": "plans",
    "chapter": "The kitchen demo",
    "type": "plans",
    "title": "A longer plan\nis not a deeper plan.",
    "subtitle": "Depth is traceability: requirement → decision → task → evidence.",
    "minutes": 2,
    "notes": "Open the plans from both arms. Count useful connections, not words. Is a task tied to a file or component? Does it have a dependency? Is there a specific way to verify it? Can a new session tell what remains? A verbose plan that repeats the prompt is still thin. A compact plan can be excellent if it resolves the important questions. This slide is intentionally not a fabricated good-plan versus bad-plan caricature. The files belong to the actual two runs. Use the recorded comparison findings, including ties and strengths in the ordinary arm.",
    "showSubtitle": false,
    "evidenceLabel": "Illustrative trace · actual plans linked",
    "cue": "Plan depth is a connection, not a word count.",
    "stageAction": "Open both actual plans. Follow one requirement through decision, task and evidence.",
    "bridge": "Plans are promises. Checks are what happened."
  },
  {
    "id": "ab-evidence",
    "chapter": "The kitchen demo",
    "type": "scoreboard",
    "title": "LGTM is not\na test result.",
    "subtitle": "One common rubric. Observable behavior. No beauty contest.",
    "minutes": 1.5,
    "notes": "Show the common checks and their observed outcomes. These are the checks performed on these prepared builds, not a universal quality score. The same test meaning applies to both arms. Look at data semantics, filter consistency, boundary behavior and unsafe input handling, as available in the actual report. The question is not which agent can say it tested something more convincingly. It is what we can reproduce. If there are failures, show the exact condition. Do not patch a result mid-demo and keep calling it the original run. The final coordinator rerun recorded 14/14 passing common checks for each arm and no browser errors. Do not convert that tie into a superiority score.",
    "showSubtitle": false,
    "evidenceLabel": "Saved common checks · synthetic fixtures",
    "cue": "LGTM is an opinion. These are checks we can inspect.",
    "stageAction": "Show representative rows. The full report has all fourteen.",
    "bridge": "Fourteen of fourteen. Twice. Let me say plainly what that means."
  },
  {
    "id": "why-different",
    "chapter": "The kitchen demo",
    "type": "causal",
    "title": "Plot twist.\nBoth can code.",
    "subtitle": "The differentiator has to survive the next session.",
    "minutes": 1.5,
    "notes": "Here is the honest result: both finished builds pass all fourteen shared checks. Both identified the important ambiguities, and the baseline also has a useful handoff. We should not pretend that adding Lintel was necessary for good reasoning or functioning code in this task. The Lintel arm produced more explicit spec, task dependency, acceptance, fresh-session prompt and review structure. That is an observed artifact difference, not evidence of faster recovery or better business outcomes. It also has more context and documents to maintain. A single paired run cannot isolate every cause. The next experiment should test whether this added structure actually improves a cold handoff enough to pay for its overhead.",
    "showSubtitle": false,
    "evidenceLabel": "Handoff benefit and productivity gains remain unmeasured.",
    "cue": "Both passed. If I hid that, this would be a sales trick.",
    "stageAction": "Pause on the tie. Explain the additional records and their cost.",
    "bridge": "A tie on code. What I can actually prove is smaller: three mechanisms, no model involved. First: does a team’s profile change anything real?"
  },
  {
    "id": "profile",
    "chapter": "Under the hood",
    "type": "profile",
    "title": "A profile should\nchange the work.",
    "subtitle": "“Enterprise” is not a theme color.",
    "minutes": 2,
    "notes": "Remember the pack from the kit screen: the team’s standards. This switches between two of them, a lab and a customer pilot. Switch between Lab and Customer pilot. This is a separate, deterministic demo: no model runs here, and it is not part of the paired agent builds. The actual Lintel pack resolver supplies values from two synthetic manifests. A presentation consumer turns them into the displayed contract. Notice the evidence requirement changes from a smoke test to a tenant negative test; identity and network design requirements change too. The demo_policy fields are custom presentation fields. No identity or network infrastructure is provisioned, and hard mode is a configuration value, not proof of enforcement. The value hypothesis is concrete: a profile should change decisions, questions and acceptance evidence.",
    "showSubtitle": true,
    "evidenceLabel": "Saved resolver values · custom demo fields · no provisioning",
    "cue": "Enterprise is not a theme color. The requirements must change.",
    "stageAction": "Toggle Lab → Customer pilot. Read the changed evidence field.",
    "bridge": "A profile changes the requirements. Now lose the chat and see what survives."
  },
  {
    "id": "cold-start",
    "chapter": "Under the hood",
    "type": "cold",
    "title": "Delete the chat.\nKeep the plot.",
    "subtitle": "The next session needs coordinates, not a séance.",
    "minutes": 2,
    "notes": "This is the window idea, applied: assume the session is gone — what is left on disk? We do not delete anything in your real repo. The prepared proof creates a local clone of a synthetic fixture without the ignored runtime ledger. The committed specification, plan, tasks and handoff survive. Show the four pointers and the next action T002. The helper validates the map and file boundaries; the explicit handoff supplies the next task. It is not the helper reasoning about priorities. Missing files and a path escaping the repo are rejected in the saved run. A fresh agent still needs to read and reason about those artifacts, but it no longer has to recover the project from chat archaeology. The four on-screen labels stand for the exact committed paths shown in the offline field guide and helper proof explorer.",
    "showSubtitle": false,
    "evidenceLabel": "Saved helper proof · handoff names T002; validator checks the map",
    "cue": "We lose the runtime, not the plot.",
    "stageAction": "Trace the four committed pointers to T002. The saved helper checks the map.",
    "bridge": "The plot survived. Does a lesson?"
  },
  {
    "id": "regression",
    "chapter": "Under the hood",
    "type": "regression",
    "title": "A lesson that never returns\nis just a diary entry.",
    "subtitle": "Capture → retrieve → verify → reinforce.",
    "minutes": 3,
    "notes": "Show Before: lookup by document ID allows another tenant's document. Switch to Fixed: the same three tests now include the tenant condition. Then select Reintroduce bug: deliberately run the vulnerable version again and watch the cross-tenant check fail. That is the important negative control. The prepared lesson is retrieved through the real keyword-scoped memory helper; an obsolete lesson and an unrelated lesson are excluded. This is not model training and not proof of production authentication. It is an example of turning a specific correction into both reusable context and executable protection. Read the red result aloud for Teams.",
    "showSubtitle": false,
    "evidenceLabel": "Actual saved tests · prepared variants · trusted test identity",
    "cue": "Put the bug back. Does the test notice?",
    "stageAction": "Click Before → Fixed → Reintroduce bug. Read the red result aloud.",
    "bridge": "One correction, two homes: a lesson and a test. That generalises."
  },
  {
    "id": "compound",
    "chapter": "Under the hood",
    "type": "compound",
    "title": "Correct once.\nMake the correction travel.",
    "subtitle": "Different artifacts remember different things.",
    "minutes": 1,
    "notes": "A lesson remembers a failure mode and when to look for it. An ADR remembers a decision and its rationale. A skill remembers the reusable method. A test remembers an observable boundary. They work together, but they are not interchangeable. Do not turn every preference into a permanent constitutional rule. Record scope, source and review status; retire what becomes wrong. Compounding context means the next relevant task starts with better material. It does not mean an ever-growing prompt, and it does not promise an exponential learning curve.",
    "showSubtitle": false,
    "evidenceLabel": "Compounding context, not model training",
    "cue": "A correction becomes useful when the next relevant task can find it.",
    "stageAction": "Explain the different jobs of a lesson, ADR, skill and test.",
    "bridge": "That is what it can do. Now the honest part: what it cannot."
  },
  {
    "id": "enforcement",
    "chapter": "The honest value",
    "type": "enforcement",
    "title": "Markdown can tell you to lock it.\nIt cannot be the lock.",
    "subtitle": "Guidance, checks and authority have different jobs.",
    "minutes": 1,
    "notes": "This matters when we talk to customers. The harness can structure the work, ask for evidence and invoke supported checks. Actual permissions, identity, network isolation, CI and deployment approvals must be configured and verified in the platform. A skill saying use least privilege does not grant or enforce least privilege. Likewise, universal method does not mean every host supports the same hooks or parallel agents. Keep this distinction crisp. It makes the rest of the story more credible and gives CSAs a clear architectural boundary.",
    "showSubtitle": false,
    "evidenceLabel": "Platform controls must be configured and verified.",
    "cue": "The instruction describes the lock. The platform has to provide it.",
    "stageAction": "Point to both objects; name permissions and CI as examples.",
    "bridge": "If it cannot enforce, and models keep getting better — what lasts?"
  },
  {
    "id": "smarter-models",
    "chapter": "The honest value",
    "type": "knowledge",
    "title": "A smarter model still wasn’t\nin last week’s meeting.",
    "subtitle": "The durable advantage is your context — not a generic expert persona.",
    "minutes": 1,
    "notes": "As models and native agent tools improve, generic advice to plan carefully or act like an expert becomes weaker differentiation. The strongest value hypothesis is project-specific knowledge: why we rejected an alternative, which requirement the team accepted, what must survive a handoff, and which check has caught a real mistake. The model cannot recover an unavailable decision by being more intelligent. Native tools already provide useful building blocks; Lintel must earn its place through the content, coordination and observed results. That is why this demonstration compares against a competent repo with ordinary project instructions and checks, rather than an artificially weak prompt-only baseline.",
    "showSubtitle": false,
    "evidenceLabel": "Illustrative ADR · the value hypothesis is project-specific knowledge",
    "cue": "Even a smarter model was not in last Tuesday’s meeting.",
    "stageAction": "Use the rejected-option example. Intelligence cannot replace unavailable project knowledge.",
    "bridge": "Context is the asset. Process is the cost."
  },
  {
    "id": "small-core",
    "chapter": "The honest value",
    "type": "smallcore",
    "title": "The process has to\npay rent.",
    "subtitle": "Start small. Add depth when the task earns it.",
    "minutes": 1,
    "notes": "My biggest concern is negative net value. More roles, instructions and review stages can add latency, conflicts and maintenance. A nine-stage cycle does not automatically belong in a one-line fix. The small core is current intent, relevant project knowledge, a checkable next action and proportionate verification. Add deeper architecture, security review or orchestration when risk or coordination needs justify it. Lintel's subtraction decision points in this direction. Its eval decision calls for evidence; an accepted direction is not proof that every evaluation capability is implemented. In a pilot, measure time to an accepted change, interventions, residual defects, cost and cold-session recovery. If process costs more than it prevents, simplify it.",
    "showSubtitle": false,
    "evidenceLabel": "More process can cost more than it prevents.",
    "cue": "Process has to earn the time it takes.",
    "stageAction": "Contrast a label change with a tenant-boundary change.",
    "bridge": "Keep it small, and it helps the people who are just starting."
  },
  {
    "id": "vibe",
    "chapter": "The honest value",
    "type": "vibe",
    "title": "Vibe coding.\nWith a return address.",
    "subtitle": "Keep the fast start. Add a route back to intent.",
    "minutes": 1,
    "notes": "For someone new to Copilot or another coding agent, this can reduce the blank-page problem. Start from a workflow: explain the outcome, resolve the important ambiguity, build one reviewable slice, and verify it. Show the person the questions and acceptance conditions, rather than making a giant instruction file they never read. For a customer this is a pilot hypothesis, not a promise of acceleration. Measure whether the newcomer needs fewer repeated explanations and produces a more defensible handoff. Keep the workflow light enough that it is actually used.",
    "showSubtitle": false,
    "evidenceLabel": "Acceleration is a hypothesis to test.",
    "cue": "Keep the fast start. Give it a route back to the agreed intent.",
    "stageAction": "Connect the four steps to a newcomer’s first small change.",
    "bridge": "That is the newcomer. Here is what it could mean for the rest of us."
  },
  {
    "id": "team-value",
    "chapter": "The honest value",
    "type": "team",
    "title": "Different roles.\nShared context.",
    "subtitle": "One shared contract. Three different jobs.",
    "minutes": 1,
    "notes": "For SEs, the opportunity is more reproducible demos, a clear story about trade-offs and less time reconstructing context before a customer meeting. For CSAs, it is explicit constraints, traceable decisions and a cleaner architecture handoff. For customer developers, especially newcomers, it is a practical way to turn an intent into a verifiable slice without having to invent the review discipline each time. These are proposed benefits to test in a bounded pilot. We are not claiming a measured customer outcome from this internal presentation.",
    "showSubtitle": false,
    "evidenceLabel": "Proposed benefits · validate in a pilot",
    "cue": "The same context helps us in different parts of the customer journey.",
    "stageAction": "Give one concrete benefit each for SE, CSA and developer.",
    "bridge": "None of that is proven yet. So do not adopt it — test it."
  },
  {
    "id": "pilot",
    "chapter": "The honest value",
    "type": "pilot",
    "title": "Don’t roll out a philosophy.\nRun a small experiment.",
    "subtitle": "One workflow. One team. A clear reason to keep it — or stop.",
    "minutes": 1,
    "notes": "Pick a repeating workflow, such as a customer demo dashboard or a prototype handoff. Agree what good looks like before running it. Track rework, missed requirements, handoff completeness and time spent maintaining the workflow. Use several comparable tasks, not only the most flattering run. Keep human review and the same underlying platform controls. Stop or simplify if the method costs more effort than the problems it prevents. A successful pilot gives us a reusable asset and evidence; an unsuccessful pilot gives us a useful boundary.",
    "showSubtitle": false,
    "evidenceLabel": "Several comparable tasks · same knowledge and controls",
    "cue": "One repeating workflow. Several comparable tasks. Then decide.",
    "stageAction": "Point at the four measurements on screen. Keep “what would make us stop?” rhetorical — the discussion is next.",
    "bridge": "Which brings me to you."
  },
  {
    "id": "discussion",
    "chapter": "Your turn",
    "type": "discussion",
    "title": "What are you tired\nof explaining twice?",
    "subtitle": "Pick one recurring task. Name the mistake. Decide what should remember it.",
    "minutes": 5,
    "notes": "Give the room a few seconds to think, then take one answer from Teams first. Ask for a specific recurring task rather than general enthusiasm about agents. Which part should be a skill? Which decision belongs in an ADR? Which mistake deserves a regression test? What would make this too heavy? The goal is not to collect a huge roadmap in five minutes. Choose one candidate workflow and an observable failure that a pilot could try to prevent. If there is disagreement, use it: different contexts may need different harnesses.",
    "showSubtitle": false,
    "evidenceLabel": "5 minutes · choose one pilot candidate",
    "cue": "What are you tired of explaining twice?",
    "stageAction": "Take Teams first. Choose one task, one recurring failure and what should remember it.",
    "bridge": "Let me close with the short version."
  },
  {
    "id": "take-it-with-you",
    "chapter": "Your turn",
    "type": "handoff",
    "title": "The talk ends.\nThe toolkit stays.",
    "minutes": 0.5,
    "cue": "Four things to take forward. One available today; three links to follow.",
    "stageAction": "Name the four deliverables. Explain Core as the small, explicit workflow shell for a customer case. Point attendees to the public site.",
    "bridge": "Start with one workflow worth remembering.",
    "evidenceLabel": "Handoff roadmap · Core, CAIP pack and Benchmark links to follow",
    "notes": "You will get four things. Lintel is the full open-source harness. Pack number one adds the MS employee in CAIP context; its distribution link will follow. Lintel Core is the planned stripped-down shell for building a specific customer harness. The intention is explicit, on-demand use inside the customer’s existing coding desktop or CLI, including GitHub Copilot. It is useful when a person is driving a bounded workflow and a separate hosted agent or dedicated application would add unnecessary operational work. It does not replace hosted orchestration when you need unattended execution, shared services, durable infrastructure or platform controls.\n\nLintel Benchmark is the planned evaluation package; its link will follow too. The prepared A/B lab on this site is available now, but it is not a statistically established productivity benchmark. No private employee pack is included in this public site. The presentation, technical reference, notes and prepared browser demos can already be used here or downloaded as an offline kit."
  },
  {
    "id": "close",
    "chapter": "Your turn",
    "type": "close",
    "title": "Keep the creativity.\nStop paying twice.",
    "subtitle": "For the same explanation. The same decision. The same mistake.",
    "minutes": 0.5,
    "notes": "Close on the practical loop. Three rows, three things we keep paying for twice. The same explanation: write the plan and the handoff where the next session can read them. The same decision: record why, not only what. The same mistake: capture the lesson and give it a test. State the intent. Make the work inspectable. Keep the decisions alive. Retrieve the right lessons. Verify what matters. Lintel is my attempt to make that loop reusable across the tools I work in. It does not replace engineering judgment; it gives that judgment somewhere durable to live. Invite the team to inspect the actual prepared outputs and the comparison protocol in the package; the repository address is on screen. If we named a task in the discussion, try it on that one and tell me what it cost. End on time.",
    "showSubtitle": false,
    "evidenceLabel": "Structure that supports the work.",
    "cue": "Keep the creativity. Stop paying twice.",
    "stageAction": "Do not read the rows; give today’s example for each: the 09:12 agreement, the rejected option B, the tenant leak. Pause. End on time."
  },
  {
    "id": "title",
    "chapter": "Reference",
    "type": "title",
    "title": "Tame the work.\nKeep the spark.",
    "subtitle": "From vibe coding to deliberate engineering.",
    "minutes": 0,
    "notes": "That was the cold open; this is the talk. A personal engineering journey, not a Microsoft product announcement. The four promises are on screen, so do not read them out. Add only what the screen lacks: the A/B test includes the part that did not go my way. The rail at the top shows the seven parts of the story and where we are, so you can always find your place again. If you are new to coding agents, the next couple of minutes are for you.",
    "showSubtitle": true,
    "evidenceLabel": "A personal engineering journey",
    "cue": "I’m Johannes. Fifty minutes: why that happens, and what I did about it.",
    "stageAction": "Let the image breathe for a beat. Do not read the list; add only what the screen lacks. Point once at the act rail at the top.",
    "eyebrow": "Fifty minutes · four promises",
    "bridge": "First, the one idea that explains almost everything else today.",
    "optional": true
  },
  {
    "id": "failure-modes",
    "chapter": "Reference",
    "type": "drift",
    "title": "The agent is busy.\nThe project is elsewhere.",
    "subtitle": "Activity is easy to see. Drift is harder.",
    "minutes": 0,
    "notes": "Three failures. Two follow directly from the window you just saw, and the third is made worse by it. Context rot: the relevant constraint is still in there somewhere, but it is no longer effectively guiding the response. Goal drift: the work has moved away from the agreed outcome. A broken handoff: the session ended, and the next one cannot reliably find the current decision or next task. These can look similar, but adding a longer prompt is not a universal fix. A model may also stop because of a tool, budget or permission boundary; we should inspect the cause rather than diagnose every stop as forgetting. The graphic is a metaphor. Useful questions: what was the last accepted outcome, what evidence exists, and where is the next action recorded?",
    "showSubtitle": true,
    "evidenceLabel": "Metaphorical illustration",
    "cue": "The agent can be busy while the project gets no closer to done.",
    "stageAction": "Name the three failures. Explain that stopping can also be a tool or permission boundary.",
    "bridge": "I met all three. Here is what I did about it — badly, at first.",
    "optional": true
  },
  {
    "id": "one-small-request",
    "chapter": "Reference",
    "type": "firstsession",
    "title": "Small change.\nUseful trail.",
    "subtitle": "“Add a health endpoint with a focused acceptance test.”",
    "minutes": 0,
    "notes": "Make it concrete. This is the small first-session example from the README, illustrated here rather than executed live. A health endpoint is simply a URL that reports whether a service is responding. Ask the agent to plan the change using Lintel. The plan records what success means and the work to do. After the plan is reviewed and execution is authorized, the agent builds the change and runs the focused check. The review and handoff say what changed, what was checked and what the next person should know. The thing to remember is the trail: request, agreed work, checked result, reusable context. Notice what that trail is made of: files. The README runs this example by starting at the planning step directly — any single step can be run on its own. It is not a hotfix: a hotfix has no plan step, and this screen shows an agreed plan.",
    "showSubtitle": false,
    "evidenceLabel": "Illustrated README example · not a recorded execution",
    "cue": "This one is new behaviour, not a fix — so it starts with a plan.",
    "stageAction": "Read the request once. Trace plan → checked result → handoff. Thirty seconds.",
    "bridge": "So where does that trail actually live?",
    "optional": true
  },
  {
    "id": "swarm",
    "chapter": "Optional +5",
    "type": "swarm",
    "title": "More agents.\nSame need for a plan.",
    "subtitle": "Parallelize independent work, not shared confusion.",
    "minutes": 5,
    "optional": true,
    "notes": "Optional five-minute extension only. Preserve the swarming direction: one coordinator, explicit dependency map, separate write scopes, attributable changes and independent review before integration. The diagram is an illustrative topology, not an executed swarm in this presentation. Parallel work is useful when tasks are independent and the host can isolate ownership. Otherwise replay the same briefs serially. Keep the authoritative task map single and treat coordination metadata as coordination. More agents amplify both good structure and unclear responsibility.",
    "showSubtitle": false,
    "evidenceLabel": "Optional topology illustration · not an executed swarm",
    "cue": "More agents amplify the plan you give them.",
    "stageAction": "Optional only. Explain ownership, isolation and independent review."
  },
  {
    "id": "architecture",
    "chapter": "Reference",
    "type": "architecture",
    "title": "Same method.\nDifferent cockpit.",
    "subtitle": "A universal core, adapted to the client you work in.",
    "minutes": 0,
    "notes": "Think of three layers. The client is where you interact with the model and tools: a CLI, an editor or a coding desktop app. Lintel provides portable working instructions, skills, roles, packs and durable artifacts. The platform below still owns the real enforcement: permissions, CI, cloud policies and deployment gates. Shared workflow does not mean identical client capabilities. Native skill discovery, agents and hooks differ by host. In particular, a hook file existing in the repo is not proof that this host executes it. For today's comparison we are explicit about the curated workflow context that is loaded.",
    "optional": true,
    "showSubtitle": false,
    "evidenceLabel": "Host capabilities and enforcement differ.",
    "cue": "Portable method does not mean identical host capabilities.",
    "stageAction": "Reference only; use it to answer architecture questions."
  },
  {
    "id": "resources",
    "chapter": "Reference",
    "type": "resources",
    "title": "Open the hood.",
    "subtitle": "Source artifacts, reproducible checks and presenter controls.",
    "minutes": 0,
    "optional": true,
    "notes": "Reference screen for Q&A. The prepared comparison, the existing helper evidence and the source notes are all local in this package. Arrow keys navigate, N opens notes, O opens overview, F requests fullscreen, and Escape closes a demo or dialog. Recorded observations are labeled. Demo-only fixtures are synthetic. The prior PowerPoint remains available as a backup, but this web presentation is the primary delivery.",
    "showSubtitle": false,
    "evidenceLabel": "Offline source artifacts and presenter guides",
    "cue": "Everything shown here is inspectable in the package.",
    "stageAction": "Reference only; open the requested artifact."
  },
  {
    "id": "product-family",
    "chapter": "Product launch",
    "track": "products",
    "optional": true,
    "type": "productfamily",
    "title": "Meet the Lintel family.",
    "minutes": 0.75,
    "cue": "Four packages, with a different job for each.",
    "stageAction": "Pause on the four motifs. Name each product once. Click an image to open the standalone artwork; each product label jumps to its slide.",
    "bridge": "Start with the complete system.",
    "notes": "Four products, four jobs. A portal for the complete system, layers for team context, an open frame for a focused workflow, and a reticle for measurement. Same family, different responsibilities. Think Unix philosophy, with slightly better lighting.\n\nLintel is the complete harness. The CAIP Pack brings our role and team context. Core is the planned smaller shell for a specific customer case. Benchmark is the planned way to test whether the added process is worth it.\n\nThey have different release states. Lintel is available in the public repository. The CAIP Pack distribution link will follow. Core and Benchmark are planned offerings; we will add their links later. The prepared comparison in this presentation is already available, but it is not the complete Benchmark product.",
    "evidenceLabel": "Product family · Core and Benchmark planned",
    "eyebrow": "THE PRODUCT FAMILY"
  },
  {
    "id": "product-lintel",
    "chapter": "Product launch",
    "track": "products",
    "optional": true,
    "type": "systemmap",
    "title": "Here’s the whole system.",
    "minutes": 1.5,
    "cue": "Lintel is the full working method around your existing coding agent.",
    "stageAction": "Walk from the client through the method to the written artifacts. End at the return loop. This is the same system map used in the introduction.",
    "bridge": "Now add context that is specific to the people doing the work.",
    "notes": "Lintel is the complete company-neutral harness. The coding client executes the work. Lintel supplies reusable workflows and helper scripts, specialist role instructions, a place for plans and decisions, and a way to bring useful knowledge back into the next task.\n\nThe pack is a separate input to the method. Skills and delegated roles do the work; invoked helpers and compatible registered hooks support it. The durable records travel with the project when committed. Temporary runtime files do not.\n\nPoint at the lower platform boundary: Markdown instructions are not platform enforcement. Permissions, sandboxing and CI still belong to the host and delivery environment. Hook coverage varies by client and verified registration.\n\nThis technical map describes the inspected development snapshot. The public release may differ; the reference distinguishes public source from unreleased excerpts.",
    "evidenceLabel": "Full harness · Inspected development snapshot · Hook coverage depends on the host",
    "eyebrow": "01 / LINTEL",
    "subtitle": "The complete workflow kit inside your existing coding tools.",
    "showSubtitle": true
  },
  {
    "id": "product-caip",
    "chapter": "Product launch",
    "track": "products",
    "optional": true,
    "type": "productpack",
    "title": "Your role.\nAlready in the room.",
    "minutes": 1,
    "cue": "The CAIP Pack brings team context to the universal method.",
    "stageAction": "Read the workshop request, then trace the added context to a more relevant brief. Describe this as the pack’s intended use.",
    "bridge": "What if a customer only needs one focused workflow?",
    "notes": "Imagine the request: prepare a customer technical workshop. Without the relevant team context, the agent has to rediscover the audience, expected evidence and our way of working.\n\nThe purpose of Lintel CAIP Pack, Pack number one, is to carry the MS employee in CAIP role and the approved team knowledge and standards that belong with it. The universal method stays in Lintel. The team-specific content stays in the pack. The example on this slide shows the intended value, not a live execution of a released pack.\n\nFor an SE or CSA, this could mean a workshop brief that starts with the right audience, a useful technical agenda and explicit questions still to resolve. The operator remains responsible for the customer context and approved inputs.\n\nThe pack’s distribution link will follow. This public presentation contains no private employee pack.",
    "evidenceLabel": "Lintel CAIP Pack · MS Employee in CAIP · Distribution link to follow",
    "eyebrow": "02 / LINTEL CAIP PACK"
  },
  {
    "id": "product-core",
    "chapter": "Product launch",
    "track": "products",
    "optional": true,
    "type": "productcore",
    "title": "One customer case.\nA smaller harness.",
    "minutes": 1.5,
    "cue": "Core is the planned shell for a focused workflow inside the customer’s coding app.",
    "stageAction": "Trace the explicit start, the chosen workflow and the reviewed artifact. Use architecture review as the example.",
    "bridge": "A smaller workflow still needs to prove that it helps.",
    "notes": "Core is the planned stripped-down version of Lintel. Start with the customer’s case and select only the context, workflow, records and checks it actually needs.\n\nThe intended interaction is explicit: a person asks to run the architecture-review workflow in the coding app they already use, including desktop GitHub Copilot. The harness helps produce a review and decision brief, with enough state to return to the work. It does not need to invoke itself automatically. That is the design intent for Core, not a claim that every host or existing full Lintel install already behaves this way.\n\nThis can avoid maintaining a separate application or hosted agent flow for a bounded, person-driven task. It still takes ownership, versioning and testing. It is not zero maintenance.\n\nWhen a case needs unattended execution, shared services, durable jobs or enforced platform controls, hosted infrastructure still has a job. The question is which runtime the use case requires. Core’s distribution link will follow.",
    "evidenceLabel": "Lintel Core · Planned shell · Explicit invocation is the design intent",
    "eyebrow": "03 / LINTEL CORE"
  },
  {
    "id": "product-benchmark",
    "chapter": "Product launch",
    "track": "products",
    "optional": true,
    "type": "productbenchmark",
    "title": "Does the harness\nearn its place?",
    "minutes": 1.25,
    "cue": "Benchmark should measure accepted work, including the cost of the harness.",
    "stageAction": "Point at what stays the same and what changes. Name the four measures. Open the prepared comparison only if time allows.",
    "bridge": "Choose one recurring task and measure the result.",
    "notes": "The Benchmark offering is planned. Its purpose is to compare a competent baseline against the same setup with Lintel, not to compare a carefully prepared harness with a deliberately weak prompt.\n\nHold the model, task, project knowledge, tests and permissions constant. Change the workflow treatment. Use more than one task and independent repetitions before making a broad claim.\n\nMeasure time to an accepted change, human interventions, remaining defects and recovery, and total cost including the extra process. Bigger plans and longer answers are not success criteria by themselves. If the harness does not help a small task, that is a useful result.\n\nThe existing browser comparison is a prepared single-run exhibit available today. It is useful for inspecting artifacts and decisions, but it does not establish a general productivity gain and is not the complete Benchmark package. Its link will follow.",
    "evidenceLabel": "Lintel Benchmark · Planned evaluation package · Prepared A/B exhibit available now",
    "eyebrow": "04 / LINTEL BENCHMARK"
  },
  {
    "id": "tech-kit",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techkit",
    "title": "Open the toolbox.\nLeave most of it closed.",
    "minutes": 1,
    "cue": "The catalogue is big. The useful working set should be small.",
    "stageAction": "Enter through the Technical tab. Say that this is a separate 18-minute module. Do not read the counts as a feature checklist.",
    "bridge": "Let’s choose the workflows that earn their place.",
    "notes": "We have seen the story and the prepared comparison. Now let’s open the machinery: which instructions we load, who executes them, where the evidence lands, and what actually fires automatically.\n\nThis source snapshot contains 127 canonical skills, 69 agent-role files and 33 hook scripts. Those are inventory counts, not 127 capabilities proven in every client. The library lives in the Lintel source bundle; the project receives the relevant context and outputs. Loading everything would defeat the deliberate-context idea.\n\nA skill is a reusable procedure. An agent file gives a worker a role, scope and reporting contract. A hook is executable code invoked by a compatible host registration, or explicitly by a workflow. The file’s existence alone does not activate anything.\n\nOur operating question is simple: for this task, what must be understood, produced and checked? That determines the working set. Think toolbox, not npm install for your entire brain.",
    "evidenceLabel": "Implementation snapshot · 275a354 · Source details in the technical reference"
  },
  {
    "id": "tech-skills",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techskills",
    "title": "Start with the loop.\nAdd depth on demand.",
    "minutes": 1.5,
    "cue": "My starter set closes the work loop; specialists come in when the task gives them a reason.",
    "stageAction": "Walk left to right through plan, build, review and capture. Point to the three specialist families. Offer the full catalogue without opening all 127 rows.",
    "bridge": "A workflow tells us what happens. A role tells a worker what to own.",
    "notes": "This is an editorial starter set, not a measured popularity ranking. Cycle routes the work; scope and define establish the problem and depth; discover reads relevant knowledge. Plan creates the executable handoff, build works through accepted cards, review inspects the result, ship handles the authorized delivery, and capture records the useful learning.\n\nThe highest-value planning artifact is not a long checklist. A card needs a requirement, dependencies, affected files, acceptance criteria and a verification command. Short tasks can sit inside one coherent work package, with review at the package boundary. Do not run the entire ceremony for a typo.\n\nResume and context-save/context-restore address continuity; doctor, hooks-status and the install checks help investigate a broken setup. Their outputs still need interpretation, because some diagnostic prose contains historical paths.\n\nThen add depth where it matters. ta covers technical architecture, da data, sc security/compliance, dh deployment/hosting, and tq testing/quality. Frontend and generate families help with repeated design and deliverables. Swarm is an opt-in coordination profile, not a default tenth phase. Nice-to-have means optional for this task, not low quality or removable.\n\nCanonical notation is li:plan. Copilot native wrappers use li-plan. Use the actual skill name discovered by your client.",
    "evidenceLabel": "Implementation snapshot · 275a354 · Source details in the technical reference"
  },
  {
    "id": "tech-agents",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techagents",
    "title": "Give each worker a job.\nAnd a boundary.",
    "minutes": 1.5,
    "cue": "A role file is a brief. It does not create another process or grant more permissions.",
    "stageAction": "Follow the prepare → implement → challenge diagram. Point to the single coordinator line. Ask: who owns the verdict?",
    "bridge": "Those workers need to agree on where the truth lives.",
    "notes": "Planner turns the request into executable work. Architect or a domain specialist resolves a design question. Build executes the accepted plan using a worker with a bounded write scope. CodeReviewer and TestRunner supply separate review and test evidence; SecurityAuditor is useful when the change touches a relevant threat boundary.\n\nThe named role matters less than its contract: exact inputs, allowed tools, writable files, acceptance and report format. A reviewer reports findings and limitations rather than quietly fixing the code it is reviewing. Otherwise it is marking its own homework.\n\nA Markdown agent file is not an operating-system permission boundary. Native delegation, separate context, tool restrictions and parallel execution depend on the host. If one agent replays the roles serially, call that self-review. The Copilot kit exposes three native profiles: lintel-planner, lintel-builder and lintel-reviewer; the wider canonical roles are source material loaded as needed.\n\nFor swarming, keep one authoritative task map. The coordinator owns shared state and integration. Concurrent writers need disjoint scopes and attributable isolation, such as separate worktrees. Each lane gets its own report and independent review, followed by review of the reconciled result. Without safe isolation, replay the same briefs sequentially. The evidence should survive even when the original agents do not.",
    "evidenceLabel": "Implementation snapshot · 275a354 · Source details in the technical reference"
  },
  {
    "id": "tech-storage",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techstorage",
    "title": "Four places.\nFour different owners.",
    "minutes": 2,
    "cue": "Installed instructions, personal configuration, project knowledge and runtime scratch are different things.",
    "stageAction": "Point out the Git boundary. Then select Copilot kit to show its local-home override. Read only the two root paths aloud.",
    "bridge": "Now follow one task through those locations.",
    "notes": "Start with the source bundle: skills, agents, hooks, helpers and scaffolding templates. A plugin manager owns its installed location; do not assume that the installed copy lives inside the customer project. The Copilot repository kit instead carries reviewed source resources under .github/lintel and native entry points under .github/skills and .github/agents.\n\nThe ordinary LINTEL_HOME default is ~/.lintel: profile, active-pack selection, packs, roles and reusable assets, plus some cross-repository caches and registries. Here ~ means the current user’s home on that machine. It is configurable. In the portable Copilot helper environment, the default is the project’s .claude/runtime/lintel-home, with an explicit operator setting taking precedence. A global install is not required for that route.\n\nThe project’s durable knowledge belongs in .claude/memory, decisions and plans. These are the files a teammate can receive through Git when committed. The .claude name is a shared Lintel storage convention, not a requirement to use Claude Code.\n\nRuntime ledgers, checkpoints, jobs and audits normally live in .claude/runtime and are ignored. They stay on that checkout. Some logs remain under LINTEL_HOME or configured output roots, so the full inventory identifies exceptions.\n\nThe v5 layout marker controls several path helpers. Legacy repositories can still resolve to tasks, docs/adr and .lintel/state. Resolve the actual layout before migrating anything; do not create two competing memory stores.",
    "evidenceLabel": "Implementation snapshot · 275a354 · Source details in the technical reference"
  },
  {
    "id": "tech-cycle",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techcycle",
    "title": "Every phase leaves\ndifferent evidence.",
    "minutes": 2,
    "cue": "The workflow instructs the agent to write the evidence. A hook does not write all of this for it.",
    "stageAction": "Select PLAN, then BUILD, then CAPTURE. Show that the concrete files change while the durable/runtime distinction stays stable. Mention that the reference covers all nine phases.",
    "bridge": "That split is what makes a restart possible—and sets its limits.",
    "notes": "Follow a task from request to delivery. SENSE and SCOPE record the route, size and intended depth. DEFINE creates the agreed design; DISCOVER leaves a record of useful context. PLAN produces the plan/spec/prompt trio and, for mapped work, work.json that points at the authoritative artifacts.\n\nBUILD updates card status and records verification. REVIEW leaves findings and acceptance evidence. SHIP handles the authorized delivery and records its status; it does not imply production deployment. CAPTURE curates lessons, decisions and the working handoff. Not every phase writes every optional file, and small routes can skip phases deliberately.\n\nClick PLAN: plan.md answers how and in what order, spec.md defines the expected behavior and acceptance, prompt.md tells a fresh executor how to start. Click BUILD: a completed checkbox must point to real evidence, not just an optimistic summary. Click CAPTURE: preserve the reason behind a decision and a reusable lesson, not the entire conversation.\n\nThe state helper appends phase/status records to the runtime ledger when invoked by the workflow. The runtime log helps with local continuity; committed plans and reviewed knowledge carry across checkouts. Some specialist reports remain ignored until explicitly promoted. If a report matters for a teammate’s decision, preserve it at an agreed committed evidence location.\n\nThe reference lists writer, trigger, path, lifetime and limitations for each declared output family. Arbitrary generated apps and operator-selected destinations are intentionally not a finite filename list.",
    "evidenceLabel": "Implementation snapshot · 275a354 · Source details in the technical reference"
  },
  {
    "id": "tech-resume",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techresume",
    "title": "Restart from files.\nNot from hope.",
    "minutes": 1.5,
    "cue": "The fresh session should be able to find the work, the next card and the reason it is next.",
    "stageAction": "Trace todo → work.json → original artifacts. Point to the missing-runtime line. Do not imply that ignored evidence reappears after cloning.",
    "bridge": "What can hooks add around that explicit workflow?",
    "notes": "The committed work map is a small index, not another backlog. At .claude/plans/<initiative>/work.json it names the real specification, plan, tasks and handoff, and can link the swarm coordination contract. The initiative is linked from the committed todo or working-state file.\n\nWhen a new session starts, prefer an operator-named map, then an unambiguous active map. If several initiatives are active, ask which one. Selecting whichever file is newest can quietly resume the wrong work.\n\nFor Spec Kit, original specs/.../spec.md, plan.md and tasks.md and their IDs stay authoritative. Lintel maps them instead of duplicating them. The validator checks the map contract and paths without executing content. It does not certify that a checked task was actually verified.\n\nLocal runtime helps reconstruct the last session position, while context-save/context-restore can use local checkpoints. A fresh clone does not contain those ignored checkpoints, jobs or runtime-only reports. Recover from committed plans and evidence, then rebuild local bookkeeping. If evidence is missing, label the work unverified.\n\nThe generic resume flow still starts from runtime and offers the mapped route; the Copilot native adapter explicitly supports committed-map selection. Test the cold-start route you intend to use. A handoff is only useful if someone who did not attend the conversation can act on it.",
    "evidenceLabel": "Implementation snapshot · 275a354 · Source details in the technical reference"
  },
  {
    "id": "tech-hooks",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techhooks",
    "title": "Hooks react.\nWorkflows do the work.",
    "minutes": 2,
    "cue": "Five registered event types. Nine core scripts. Twenty-four more scripts that are not automatically registered.",
    "stageAction": "Walk the event spine from session start to stop. Toggle to optional groups. Emphasize WARN versus BLOCK, and that Stop does not force continuation.",
    "bridge": "The same workflow can travel further than its hook registration.",
    "notes": "At this snapshot, the Claude-compatible manifest registers nine scripts across SessionStart, UserPromptSubmit, PreToolUse, PostToolUse and Stop. Session digest and cycle position inject context. Proposed-edit and prompt scanners warn. The memory-budget hook warns after edits. The stop hook emits an advisory reminder about incomplete work; host delivery needs verification. It does not force continuation or create a checkpoint.\n\nTwo scripts intentionally return a blocking result for detected secret or customer-data patterns in selected git commit/push commands. These are heuristic checks with overrides and scan limitations, not a complete DLP system. Despite its name, no-direct-main-push only warns. Branch protection and platform permissions are the independent boundary.\n\nToggle the optional view. Fifteen domain advisories cover architecture, data, security, deployment and testing. Six other scripts surface context, design or risk signals. Three job helpers address begin, end and stale work. They have no registrations in the core manifest. Event names in a HOOK.md file are suggested wiring, not evidence that it runs.\n\nSome names promise more than the code: the screenshot check reads DOM text, not pixels; cost and performance warnings do not measure spend or run benchmarks. Domain checks often inspect the existing file before an edit. The full inventory documents these limits.\n\nThe practical test is event → actual payload → script → visible result and audit. A symlink or plugin manifest alone is not that evidence. No hooks were activated while preparing this presentation.",
    "evidenceLabel": "Implementation snapshot · 275a354 · Source details in the technical reference"
  },
  {
    "id": "tech-clients",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techclients",
    "title": "Same knowledge.\nDifferent entry points.",
    "minutes": 2,
    "cue": "Portable content is the goal. Runtime parity is something we must demonstrate per client.",
    "stageAction": "Select Claude Code, then Copilot, then Codex/Cursor. Point out where the source bundle and project outputs differ. Use the reference for the remaining clients.",
    "bridge": "Now make the content specific to the organisation.",
    "notes": "The shared project artifacts can stay the same while discovery and execution differ. Claude Code uses the Claude plugin convention and the registered hook manifest. Codex and Cursor have manifests that point to canonical skills and agents; this Lintel snapshot does not register the hook bundle for those clients. An agents field alone is not proof of live delegation.\n\nCopilot has the most explicit portable repository route: .github/skills/li-*/SKILL.md, three .github/agents profiles, repository instructions and source resources under .github/lintel. The checked manifest contains fourteen workflows including swarm. The CLI plugin packages the same native core entry points. VS Code, CLI and cloud need their own live acceptance checks; another IDE under the Copilot brand does not inherit all these claims.\n\nGemini’s extension manifest points to GEMINI.md. Lintel’s current integration uses context/content rather than declaring native skills or hooks. OpenCode has content-loading instructions; its plugin shim directory is empty. Factory Droid follows the declared marketplace route without Lintel hook translation. Cline, Continue and Aider are best-effort manual instruction routes.\n\nThese are facts about this Lintel revision, not a claim about what current vendors can support. In particular, Copilot has native hook facilities; Lintel’s shipped hook configuration for Copilot is empty. The future universal-adapter plan is not counted as implemented support here.\n\nMarketplace cache paths are host-managed and may vary. Inspect the installed bundle in the client instead of copying a path from someone else’s laptop. The reference records every declared entry point and explicitly marks unspecified locations.",
    "evidenceLabel": "Implementation snapshot · 275a354 · Source details in the technical reference"
  },
  {
    "id": "tech-packs",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techpacks",
    "title": "Your pack makes\n“good” specific.",
    "minutes": 1,
    "cue": "A stronger model still needs the decisions and standards your team actually chose.",
    "stageAction": "Follow the profile → selected pack → task path. Point to the host-policy rail beneath it.",
    "bridge": "That knowledge must stay useful as the project changes.",
    "notes": "A profile selects operator context; an active pack supplies the organisation’s voice, workflows, role context and declared constraints. The neutral _default pack is the baseline when no company identity is configured. It does not turn a personal installation into an approved enterprise deployment.\n\nThe resolver separates configured pack directories, working-repository packs and bundled source. Pack composition replaces defined blocks rather than deeply merging every nested key. Missing-field defaults and explicit inheritance are different mechanisms; inspect the resolved field when debugging unexpected behavior.\n\nUse packs for reviewed project knowledge and repeatable standards: architectural decisions, acceptable evidence, appropriate design conventions and business vocabulary. Keep credentials in the platform’s secret system. A local private pack is not automatically available in a cloud agent’s checkout.\n\nInstructions that say require approval or run a compliance check remain workflow rules until supported execution is configured and tested. A pack field naming a hook does not register it with every client. The team’s actual access control, branch rules and CI remain their own layer.",
    "evidenceLabel": "Implementation snapshot · 275a354 · Source details in the technical reference"
  },
  {
    "id": "tech-maintenance",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techmaintenance",
    "title": "Memory needs an editor.\nNot a landfill.",
    "minutes": 1.5,
    "cue": "Keep the reasoning. Bound the working set. Make disposal explicit.",
    "stageAction": "Move across update, supersede and archive. Point to the committed/runtime separation. Mention the manual maintenance boundary.",
    "bridge": "Finally, prove the setup works after an upgrade.",
    "notes": "There are three different maintenance jobs. First, curate durable knowledge: update an existing fact before appending another version, give lessons stable IDs, and explicitly supersede outdated lessons or decisions while preserving why they existed. Keep the memory index short and the working-state handoff current.\n\nSecond, control transient output: ignore runtime state, checkpoints, job scratch and audit churn according to the repository contract. If test evidence must survive a clone, commit the reviewed evidence deliberately. Gitignored does not mean deleted or harmless, and it is not a privacy boundary.\n\nThird, maintain the installed kit: pin the reviewed source revision, inspect update diffs, preserve project edits and rerun the pilot. The Copilot installer uses a managed inventory and detects conflicts instead of blindly overwriting local changes. It has no general remove command. Do not delete an entire .github or .claude directory to uninstall it.\n\nThe source has memory-budget warnings and on-demand maintenance workflows, not a universal automatic garbage collector. clean recommends save/restart/restore; it cannot compact a host conversation itself. maintenance contains manual procedures and partial examples, so verify targets and retention before running them. Job-end has real promotion/cleanup behavior but is dormant by default; it is not a safe blanket cleanup switch.\n\nOur standard should be: every durable document has a purpose, an owner and a reader. If nobody can explain who will use it next, it is probably documentation compost.",
    "evidenceLabel": "Implementation snapshot · 275a354 · Source details in the technical reference"
  },
  {
    "id": "tech-proof",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techproof",
    "title": "Installed is not\nthe same as working.",
    "minutes": 2,
    "cue": "Test discovery, a real task, a cold restart and the negative cases. Then measure whether the process earned its cost.",
    "stageAction": "Use the four checks as the live-client pilot checklist. Finish with the reference link or return to the main story. Do not claim these checks ran in every client.",
    "bridge": "Take one recurring workflow and run the same acceptance test on the clients your team actually uses.",
    "notes": "Before a rollout or client upgrade, record the Lintel revision, client version, enabled policies and relevant dependencies. Structural checks can show that files and schemas are valid; they cannot prove the model followed them.\n\nOne: verify actual discovery. Which instruction file, skill and agent did the client select? Check for duplicate personal and repository copies. Two: execute one bounded task with a requirement-traced plan and a real failing-then-passing acceptance check. Review the diff and evidence, not just the agent’s summary.\n\nThree: start a fresh session or clone without the original runtime state or personal home. Can it select the correct committed work map and resume at the right card? Four: test negative cases using synthetic fixtures: missing helper, malformed hook input, denied action, ambiguous initiative and edited managed file during update. Required platform controls must still work when agent instructions are ignored.\n\nFor Windows or cloud execution, explicitly confirm Bash, Python and any optional analyzer a selected helper needs. Do not let a silent missing dependency look like a clean scan.\n\nThen assess value with the same model, task, project knowledge, tests and CI in both conditions. Measure time to accepted change, interventions, defects, recovery and total cost, including process overhead. This presentation’s source inspection is not an all-client execution certification or a measured productivity claim.\n\nThat is the technical proposition: a small useful working set, durable decisions and verification you can inspect. The larger library is there when the work needs it.",
    "evidenceLabel": "Implementation snapshot · 275a354 · Source details in the technical reference"
  }
];
