window.DECK_SLIDES = [
  {
    "id": "welcome",
    "chapter": "Welcome",
    "type": "holding",
    "holding": true,
    "title": "The portal is open.",
    "subtitle": "We begin shortly.",
    "minutes": 0,
    "notes": "Leave this screen on while people join. The supplied portal animation loops silently. Pause motion if preferred; reduced-motion settings show the still image by default. This holding screen is outside the 50-minute talk. When everyone is ready, choose Begin or press the right arrow: the original opening starts on slide 2. The illustration sets the atmosphere; it is not evidence of product behavior.",
    "stageAction": "Let the room settle. Use fullscreen if presenting. Choose Begin when you are ready.",
    "bridge": "We had a plan. The AI had other plans."
  },
  {
    "id": "three-hours",
    "chapter": "Meet Lintel",
    "type": "systemcover",
    "title": "We had a plan.\nThe AI had\nother plans.",
    "subtitle": "Ever had to explain the same plan twice?",
    "minutes": 1,
    "notes": "I am Johannes, the creator of Lintel. This is my personal engineering project and the journey behind it. A lintel is a horizontal support beam placed across the top of an opening—such as a door, window, or fireplace—that carries the weight of the structure above it. The name is the metaphor: useful structure supports the work. You write a detailed plan. Hours later the agent is doing something impressive, but it is no longer the thing you asked for. Or it stops and you have to reconstruct what was happening. Today I want to show the system I built around that frustration, then test where it adds value. The exchange on screen is an illustration, not a recorded benchmark. Lintel is a personal open-source project, not a Microsoft product.",
    "showSubtitle": true,
    "evidenceLabel": "Illustrative conversation",
    "cue": "Who has corrected an AI on something you agreed three hours ago?",
    "stageAction": "Pause for hands, including remote participants. Let the dashboard-to-platform joke land. Introduce yourself in one sentence.",
    "bridge": "Let me show you the whole system before we open any of its parts.",
    "eyebrow": "Lintel · Taming the wild beast"
  },
  {
    "id": "what-is-lintel",
    "chapter": "Meet Lintel",
    "type": "systemmap",
    "title": "Here’s the whole system.",
    "subtitle": "A workflow kit inside the coding tools you already use.",
    "minutes": 1.5,
    "notes": "Start at the top: you supply the outcome and important choices. Your coding client runs the model and tools. Lintel provides a reusable method; skills carry workflows and agent roles carry focused assignments. Packs supply team knowledge. The agent and invoked helpers maintain project scaffolding: plans, decisions, lessons and a handoff. The next task retrieves the relevant records.\n\nUniversal changes are merged on the 0.11.0 beta development line. The concrete advances are a shared work map, a verified effective profile, owned installation and recovery, and independent review evidence bound to the content being delivered. These are specific contracts and helpers, not a hosted agent runtime.\n\nAdapters connect the shared kit to an exact client surface. Native-format discovery does not prove execution. The portable repository kit installs no hooks. Lintel’s optional native hook adapter still uses the Claude Code protocol; Copilot has a hook API, but this bundle has not been translated to it. Permissions and CI remain platform controls. MDASH and AGT serve different jobs.",
    "showSubtitle": true,
    "evidenceLabel": "Hook coverage depends on the client and verified activation.",
    "cue": "Your agent does the work. Lintel gives it a method and a useful trail to leave behind.",
    "stageAction": "Read the map top to bottom. Point to the team pack, then follow the return line from project records into the next task.",
    "bridge": "Before we open those parts, here is the moment this changed how I worked.",
    "sources": [
      "https://github.com/jokerman89/lintel/blob/80002ed4aaa8697ff658f50902a469c80e14856d/docs/architecture.md",
      "https://github.com/jokerman89/lintel/blob/80002ed4aaa8697ff658f50902a469c80e14856d/docs/client-adapters.md"
    ]
  },
  {
    "id": "swarming-moment",
    "chapter": "Meet Lintel",
    "type": "swarmreveal",
    "title": "I stopped being the queue.",
    "subtitle": "My GitHub activity, before and after adopting Lintel swarming.",
    "showSubtitle": false,
    "minutes": 0.5,
    "eyebrow": "MY JOURNEY / THE SWARMING MOMENT",
    "evidenceLabel": "Two selected days from my GitHub history. Contributions measure activity — not quality or bugs fixed.",
    "cue": "Here is a day from before I had swarming in Lintel. Fifty-five contributions. Then I changed how I organised the work.",
    "stageAction": "Point to 55. Click “Then I turned on swarming.” Let 711 land in silence for two beats. Point to the original screenshots, then trace the report-to-fix flow. Use “Replay reveal” if rehearsing.",
    "bridge": "More throughput also gave me a very large reminder about delivery boundaries.",
    "notes": "Before swarming, one busy day showed 55contributions. Afterwards, this day showed 711. [Reveal.] That changed the scale of work I could coordinate. These are two personal activity snapshots, not proof of quality or a measured speedup. More activity still has to become reviewed, useful changes. And that brings me to the next morning.",
    "sources": [
      "../presenter/sources.html#swarming-activity",
      "../reference-source/docs-concepts-swarming-work-md.html#L4"
    ]
  },
  {
    "id": "we-broke-github",
    "chapter": "Meet Lintel",
    "type": "githubmoment",
    "title": "We broke GitHub.*",
    "subtitle": "*My browser tab, technically.",
    "showSubtitle": true,
    "minutes": 0.5,
    "eyebrow": "THE NEXT MORNING",
    "evidenceLabel": "Personal incident · PR #93 screenshot · not a throughput benchmark",
    "cue": "740 commits. 760 files. One very unhappy browser tab.",
    "stageAction": "Point to the unresponsive-tab message, pause for the joke, then move on. Do not open the enormous PR live.",
    "bridge": "The lesson is to agree the delivery boundary before workers start. Here are the parts that make the work reviewable.",
    "notes": "I tried the new swarming and left it working overnight. I forgot to authorize pull requests along the way. The result: 740 commits, 760 files—and an unresponsive browser tab. So, obviously, we broke GitHub. [Pause.] My tab, to be precise. More throughput still needs small, reviewable deliveries.\n\nThis is my account of the incident. The supplied screenshot documents the visible PR counts and unresponsive tab, not a GitHub outage or a measured productivity gain. Agree PR authorization, bounded delivery packages and a stop condition before dispatch. A missing delivery decision is a reason to pause the affected work, not permission to keep expanding it.",
    "sources": [
      "https://github.com/jokerman89/lintel/pull/93"
    ]
  },
  {
    "id": "inside-the-kit",
    "chapter": "Meet Lintel",
    "type": "buildingblocks",
    "title": "Six parts. One working system.",
    "subtitle": "",
    "minutes": 1,
    "notes": "Scaffolding gives the project places for instructions, plans, decisions, lessons and handoffs. The method defines the workflow and when clarification or review is needed. Skills are reusable recipes for jobs such as architecture, technical review or testing. Agent roles provide focused expertise; separate execution depends on host support. Hooks are registered event checks, not an intelligent observer of everything. Compounding means a reviewed lesson or decision is retrieved and applied to later relevant work. A team pack changes the standards and context across these parts. Compounding needs retrieval and verification; accumulating more files alone does not create value.",
    "showSubtitle": false,
    "evidenceLabel": "Load the parts the task needs.",
    "cue": "Scaffolding is where it lives. The method says how to work. Compounding brings useful learning back.",
    "stageAction": "Use one short sentence per part. Explain that an agent role is a job description and a hook reacts to an event.",
    "bridge": "The useful bit is how these parts maintain the trail while the work happens."
  },
  {
    "id": "state-loop",
    "chapter": "Meet Lintel",
    "type": "stateflow",
    "title": "The work leaves a way back.",
    "subtitle": "The method requires a trail. Skills and agents write it as they work.",
    "minutes": 2,
    "showSubtitle": true,
    "evidenceLabel": "Illustrative walkthrough · no agent or hook is executing here.",
    "cue": "The agent should not need your memory to find its next task.",
    "stageAction": "Click through the three example steps: clarification, saved decision, fresh session. Explain who asks and who writes. Keep the registered-hook lane separate.",
    "notes": "The method requires the agent to clarify material ambiguity, record consequential decisions, keep the plan current and capture evidence. Skills turn those requirements into concrete instructions; agents and local helpers perform the writes. They maintain the existing scaffolding instead of inventing a new memory store. This example begins with an export task and an unresolved date boundary. The workflow surfaces the ambiguity and the agent asks whether dates use UTC or local time. The human answers UTC. The agent records that decision, updates the task and identifies the boundary test as the next action. A compatible SessionStart hook can surface a digest, and a prompt-position hook can reassert the current step. A fresh agent still reads and checks the authoritative files before continuing. Hooks run only on exposed and registered events. A hook may warn, supply context or block selected operations, according to its actual contract; it does not itself understand every uncertainty or guarantee that a question is asked. Stop warnings do not force auto-continuation. Keep reviewed decisions and handoffs with Git; keep temporary counters and runtime ledgers ignored. The quality comes from both writing and reading the trail.",
    "bridge": "Why does that trail matter so much? Because each session has a limited window."
  },
  {
    "id": "context-primer",
    "chapter": "Meet Lintel",
    "type": "primer",
    "title": "A fresh session.\nA new window.",
    "subtitle": "Everything the agent knows about your project has to fit in here — right now.",
    "minutes": 1.5,
    "notes": "Three words. An agent is an AI model that can read your repository, edit files and run commands with your permissions — GitHub Copilot’s agent mode, Claude Code and Codex are examples. Its context window is everything the model can see at this moment: loaded instructions, your request, files it has read, tool output and the conversation so far. It is finite. A session is one working conversation; a fresh session needs its working context loaded again. Memory features do not change this: they are stored text that gets loaded back into the window. Now click Three hours later. The window has filled with tool output, new files and a long conversation. The 09:12 agreement is still somewhere in the log, but it has been crowded out: depending on the tool it is compacted, truncated, or simply gets less attention among everything else. That is a large part of what happened in the opening conversation — not stupidity, not malice. The last line on screen is the important one: files in the repository are still there in the next session. Most of what follows today is a consequence of that: put what matters where the next window can find it. This is a simplified illustration with invented counts; tools manage context differently, and a larger window delays the problem rather than removing it.",
    "sources": [
      "https://www.trychroma.com/research/context-rot"
    ],
    "showSubtitle": true,
    "evidenceLabel": "Simplified illustration · invented counts · tools manage context differently",
    "cue": "The model works with the context it can see right now.",
    "stageAction": "Give an example for each word rather than reading the definitions. Click “Three hours later”. Point at the crowded-out line, then at the files.",
    "bridge": "That is why I stopped trying to be the project’s memory myself."
  },
  {
    "id": "journey",
    "chapter": "Meet Lintel",
    "type": "journey",
    "title": "I became a very expensive\ncopy-and-paste loop.",
    "subtitle": "The progression that led me to Lintel.",
    "minutes": 0.5,
    "notes": "My first fix was the obvious one: better prompts. Then I noticed I was pasting the same expectations into every repository and every session — I had become the memory. The shift was to make the useful method durable: written down in the repository, where the next session can find it without me. This describes the pattern; I am not claiming a measured productivity gain or inventing a personal incident.",
    "showSubtitle": false,
    "evidenceLabel": "A pattern, not a measured result",
    "cue": "My first fix was the obvious one: better prompts.",
    "stageAction": "Move through the three stages and let the “lives in” line do the work. Land “Chief Repetition Officer” at step two.",
    "bridge": "Here is the actual workflow behind that durable method."
  },
  {
    "id": "the-cycle",
    "chapter": "Meet Lintel",
    "type": "cyclemap",
    "title": "Right code.\nWrong problem.",
    "subtitle": "Nine steps. Five of them before a line of code is written.",
    "minutes": 1,
    "notes": "Spoken path — red tab, lime tab, the two flags, the slips. Nothing in those three hours was bad code. It was good work on the wrong thing, and this is where you found out. Same misunderstanding — but here you can find it on paper, in minutes. So the playbook is lopsided on purpose: nine steps, five of them before any code, and before any code it stops for you at least twice: the design, then the plan with a token estimate. Not hours, not money. And every step leaves something written, because the chat will not survive the session; written things can. Lintel calls this line the cycle. You do not need to learn nine names. Learn the shape.\n\nReference for questions: Lintel’s own documentation says it directly — the expensive failures in agent-driven work are correct code built against the wrong premise, discovered three hours later. SENSE reads the situation and ends with a suggested route, which is the next screen. SCOPE sizes the request and asks at most one question. DEFINE produces an approved design, not a draft. DISCOVER only reads: existing decisions, lessons and patterns. PLAN writes three files together: checkable tasks, what done means, and a brief for a fresh session. REVIEW is deliberately adversarial: spec, quality, team standards. SHIP opens a pull request by default. CAPTURE keeps lessons, a decision record and the working notes the next session picks up — the handoff — which a later DISCOVER can find; that is why it is a cycle. Every “skip it and” line is that step’s own declared cost from the documentation, not a measurement.\n\nClaim boundaries: “at least twice” is deliberate. On a full run you are asked to confirm the route after SENSE, possibly one sizing question, then the design, the plan, and an estimate shown before BUILD — a task count and a token estimate labelled uncalibrated, never money or time. An approval gives you the chance to catch a wrong premise; it does not catch it for you. These are instructions the agent is told to follow; real enforcement is the platform’s, which is why there is no lock on this screen. “Leaves something written” does not mean committed: the situation report and the sized request are temporary working state, and a later screen draws that line. Swarming is an optional way to run PLAN, BUILD and REVIEW, not a tenth step. The strip is the illustrative opening conversation, not a measured run.",
    "showSubtitle": false,
    "evidenceLabel": "Workflow instructions · checks and platform controls do the enforcing · chat strip illustrative",
    "cue": "Remember the platform nobody asked for? Look at where you found out.",
    "stageAction": "Pointer only — no clicks, no question to the room. Same order as the spoken path: 1 · the red tab, top right. 2 · the lime tab on the first approval. 3 · the two flags, left of the dashed line. 4 · one sweep along the slips. The approval is your chance to find the mistake: never say it finds it for you. Do not name the nine steps or recite the panel. Ahead of time: click CAPTURE once. Behind: drop the sweep.",
    "eyebrow": "Meet Lintel · the cycle",
    "bridge": "And about now, somebody is thinking: that is a lot of steps."
  },
  {
    "id": "short-routes",
    "chapter": "Meet Lintel",
    "eyebrow": "Meet Lintel · shorter routes",
    "type": "routes",
    "title": "Nine steps\nfor a typo?",
    "subtitle": "SENSE reads the request and suggests a route. You confirm it.",
    "minutes": 1,
    "notes": "Spoken path — no click needed. No. And look what that suggestion rests on: one word. SENSE matched “fix” — that is all the routing is today, keyword rules. So it suggests the short route: build, review, ship. Four of nine; the skipped steps are still drawn, marked as skipped. And it only suggests: the person marker on the line is you, and by default nothing else runs until you say proceed. Research gets three steps and no build. A small feature gets all nine, but a flat plan. And it works the other way: “deploy” sounded like one step. It cannot tell a web page from a landing zone, so it asks once — and the answer sent it the long way.\n\nReference for questions: the documentation’s own heading is “you rarely need all nine”. hotfix is SENSE, BUILD, REVIEW, SHIP, for a known bug with a clear fix. research-dive is SENSE, DEFINE, DISCOVER: understand first, no code yet. A build request gets the full cycle; a clearly small one is sized small, so the plan stays a flat task list and SCOPE asks nothing. Before any code is touched you see what will run, what is skipped and a token estimate, then Proceed? [Y/n/edit]. How to ask for it: run the cycle with your request and SENSE suggests; or name the mode yourself, which always wins; the field guide has the exact spellings per tool. You can also enter at a step, stop early or drop one, and the workflow is told to check dependencies first: BUILD needs a plan, REVIEW needs a diff, SHIP needs a passed review. Any single step can run on its own — the answer to “does a hotfix never record a lesson?” is: run CAPTURE afterwards. A hotfix keeps REVIEW and SHIP.\n\nClaim boundaries: routing is first-match keyword rules; the slot for asking a model is a stub today. “Confidence high” only means a word matched, including the wrong one. The headline is true because of the word fix: “Correct the typo on the export button.” matches nothing, comes back unclear and falls to the full cycle, so you choose or name the mode. Do not improvise requests live: “Add error handling” routes as a fix. Later screens say depth follows risk: that is the principle; today’s implementation is a keyword guess plus your judgement at the confirm prompt, which is why the person marker is part of the picture. Say “by default”: the neutral setup confirms every route, but a team’s standards can allow low-risk routes to start on their own. The size check exists only where SCOPE runs, so not on hotfix or research-dive. Row four is conditional: it is re-routed only if you pick the large reading and nothing is built yet; pick small and the ship route stands. Say it cannot tell, so it asks — never that it noticed its mistake. The question’s wording is illustrative, adapted from the repository’s own example. The skipped-step marker is an instruction to each step, backed by a hook only in Claude Code. In the GitHub Copilot kit the same cycle and modes run, commands are spelled with a dash, and there is no separate fix shortcut — which is why this screen names modes and steps, not commands. The four requests are illustrative; they were checked against the real matching and sizing rules, they are not recorded runs. Routing is advice written in instructions. Nothing here is a lock.",
    "showSubtitle": false,
    "evidenceLabel": "Illustrative requests · keyword rules today · SENSE recommends, you confirm · an explicit mode always wins · workflow instructions, not enforcement",
    "cue": "No. And look what that suggestion rests on.",
    "stageAction": "Pointer, top to bottom — no click needed, no question to the room. 1 · the marked word “Fix”. 2 · along row one’s rail: one lit, the person marker, a jump, three lit. 3 · the lime YOU chip. 4 · the Deploy row’s tag: struck first guess, one question, the long way. Let the pointer fall past rows two and three. Ahead of time: click the Deploy row for the question and both outcomes. Say it cannot tell, so it asks — never that it noticed. Never improvise a request live.",
    "bridge": "So which parts of that trail travel to the next session?"
  },
  {
    "id": "where-it-lives",
    "chapter": "Meet Lintel",
    "type": "storage",
    "title": "Your setup.\nYour project’s memory.",
    "subtitle": "What stays on your machine? What travels with Git?",
    "minutes": 1,
    "showSubtitle": false,
    "evidenceLabel": "Representative Lintel layout · adapter-specific files vary",
    "notes": "Remember the window: files are what survive a session. This is where Lintel puts them. Point to the left first: machine-global means reusable across projects on this computer. The ~/.lintel/ home contains your profile and installed packs, as well as operator-wide records. Your coding client owns its own settings, tools and permissions; ~/.claude/ is a Claude-specific home, not a universal home for every app. Now point right: the project repository keeps reviewed memory, decisions, plans and handoffs under its declared paths. In the standard Lintel layout that is .claude/memory/, .claude/decisions/ and .claude/plans/. Commit the appropriate reviewed knowledge so Git can carry it to the next person or session. The dashed area is .claude/runtime/: temporary execution state is ignored and does not travel in a normal clone. The .claude folder name does not require Claude Code. Client adapters (the few files that teach one coding tool where to find all this — next screen) can add their own files; the Copilot route of the Universal repository kit uses .github/copilot-instructions.md, .github/skills/, .github/agents/ and .github/lintel/. Those details are in the field guide. Your global profile and installed packs do not automatically appear on a colleague’s machine through Git. The active pack must be available and configured there. The point is to separate reusable operator context, portable project knowledge and disposable run state.\n\nThe shared source bundle remains .github/lintel/ for compatibility. Other selected surfaces get their own discovery roots pointing into it. A repo can require a specific pack in .claude/profile-requirements.json; profile.yaml carries role/mode preferences, not pack selection. Bound profile drift requires explicit reconciliation. See the technical module for exact paths.",
    "cue": "Your setup stays with you. The project’s reviewed knowledge travels with the project.",
    "stageAction": "Trace left → right, then the Git arrow. Point to the dashed runtime box last.",
    "bridge": "Almost none of this is tied to one coding tool. I will show you the exception.",
    "sources": [
      "https://github.com/jokerman89/lintel/blob/80002ed4aaa8697ff658f50902a469c80e14856d/docs/client-adapters.md",
      "https://github.com/jokerman89/lintel/blob/80002ed4aaa8697ff658f50902a469c80e14856d/docs/lifecycle.md"
    ]
  },
  {
    "id": "supported-tools",
    "chapter": "Meet Lintel",
    "type": "clients",
    "title": "One method.\nYour actual tools.",
    "subtitle": "CLI · desktop · IDE · cloud — check the exact surface.",
    "minutes": 1,
    "notes": "The Universal registry now names 37 surfaces across 14 product families, plus an explicit manual fallback. Twenty-five records have a generated native-format discovery route. CLI, desktop, IDE and cloud are separate entries, because one product name does not imply the same capabilities everywhere. Gemini CLI and OpenCode CLI now have native-format skill routes; the old content-only slide is retired.\n\nKeep three evidence levels separate: vendor documentation, delivered Lintel files, and observed host execution. The registry has three partial Copilot App observations and no complete live acceptance record. Other unrecorded observations mean not_run, not proven failure.\n\nThe shared .github/lintel bundle reuses the existing Copilot installation engine. It is not Copilot-only. Native roots differ by surface. The portable route installs no hooks; the optional Claude-compatible plugin adapter is separate. Inspect the detailed matrix and validate your actual host before relying on controls.",
    "showSubtitle": true,
    "evidenceLabel": "37 named surfaces + manual fallback · not 37 certified integrations",
    "cue": "Keep your tool. Reuse the method. Verify what this host actually supports.",
    "stageAction": "Point to the hook boundary. Open the matrix only if asked.",
    "bridge": "One more thing: what this is not.",
    "sources": [
      "https://github.com/jokerman89/lintel/blob/80002ed4aaa8697ff658f50902a469c80e14856d/docs/client-adapters.md",
      "https://github.com/jokerman89/lintel/blob/80002ed4aaa8697ff658f50902a469c80e14856d/lib/cli-tiers.yaml"
    ]
  },
  {
    "id": "not-one-ring",
    "chapter": "Meet Lintel",
    "type": "guild",
    "title": "No single harness.\nNo magic ring.",
    "subtitle": "Different tools. Different jobs. Plenty of room at the table.",
    "minutes": 0.5,
    "notes": "Now you know what kind of thing Lintel is. A harness, by the way, is just the scaffolding around a model: the instructions, tools and checks it works inside. Before we go deeper: MDASH is awesome, AGT is cool, and this is not a replacement pitch. Other useful approaches solve different parts of the problem. Different problems deserve different tools. Today we are examining the working method around development. One harness to rule them all would probably need a migration plan and three steering committees.",
    "showSubtitle": false,
    "evidenceLabel": "Positioning, not a feature comparison",
    "cue": "MDASH is awesome. AGT is cool. Different problems deserve different tools.",
    "stageAction": "Deliver the magic-ring joke orally; do not turn this into a competitor matrix.",
    "bridge": "Now the ideas underneath — useful with or without Lintel."
  },
  {
    "id": "what-how-why",
    "chapter": "The method",
    "type": "triad",
    "title": "What. How. Why.\nThen make it compound.",
    "subtitle": "A working contract the next session can actually use.",
    "minutes": 1,
    "notes": "Here is the method in three words, and it maps onto the cycle you just saw: What is what DEFINE writes down, How is PLAN through REVIEW, and Why is what CAPTURE keeps. WHAT is the intended result and its boundaries: who is this for, what changes, and what does done mean? HOW is the work: a plan at an actionable level, a repeatable workflow, and specific review and verification steps. WHY is the decision context: constraints, rejected alternatives and the reason we chose this approach. Then compound: capture a correction, retain the decision, and retrieve it when the next task matches. The workflow asks for these artifacts. The artifact itself is not a guarantee of quality. Evidence and review have to make the contract real.",
    "showSubtitle": false,
    "evidenceLabel": "",
    "cue": "What are we building, how do we verify it, and why this approach?",
    "stageAction": "Point once to each word; explain compounding with the return arrow.",
    "bridge": "Writing that contract once is fine. Writing it for the fifth time is the problem."
  },
  {
    "id": "repeat-yourself",
    "chapter": "The method",
    "type": "reuse",
    "title": "Your fifth dashboard\nshould remember the first.",
    "subtitle": "Repeat the useful method. Revisit the actual requirements.",
    "minutes": 1,
    "notes": "Imagine building dashboards across five repos. Each time you ask for sensible empty states, meaningful time axes, accessible charts, correct filtering and exports that match the screen. Those are recurring review questions. A reusable skill can carry them once. It should not blindly carry the previous customer's requirements or architecture. The reusable part is the decision procedure: what to inspect, what to ask, what evidence to produce and when to stop. Click Package the pattern. The invariant checks move into the skill; the new repo's data, audience and constraints still enter every time. This is deliberate reuse, not copy-paste architecture.",
    "showSubtitle": false,
    "evidenceLabel": "Illustrative skill pattern",
    "cue": "The fifth dashboard should reuse the questions, not inherit the first customer’s answers.",
    "stageAction": "Click Package the pattern once. Mention empty states and export consistency.",
    "bridge": "A skill carries the method. It still has to fit in the window."
  },
  {
    "id": "context",
    "chapter": "The method",
    "type": "context",
    "title": "The context window\nis not a junk drawer.",
    "subtitle": "Give the next decision what it needs — and a way back to the source.",
    "minutes": 1,
    "notes": "Back to the window from the beginning. If it is finite, what goes into it is a design decision. This is an interactive illustration, not a token benchmark. Start with everything included: old plans, unrelated lessons, a superseded decision. Click Curate context. Keep the approved scope, current task, relevant decision and matching lesson. Retain source pointers so the agent can inspect more if needed. Context engineering is not just reducing size; it is selecting, structuring and refreshing what matters. Chroma's context-rot experiments and Anthropic's context-engineering discussion motivate this pattern, but neither is a benchmark of Lintel. More text and better context are different objectives.",
    "sources": [
      "https://www.trychroma.com/research/context-rot",
      "https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents"
    ],
    "showSubtitle": false,
    "evidenceLabel": "Selection illustration · not a model benchmark",
    "cue": "More context is easy. Useful context requires a choice.",
    "stageAction": "Click Curate. Identify the four retained records and their source pointers.",
    "bridge": "Right context, right method. The last ingredient is the size of the work."
  },
  {
    "id": "granularity",
    "chapter": "The method",
    "type": "granularity",
    "title": "Small steps.\nA coherent piece of work.",
    "subtitle": "Granular enough to verify. Coarse enough to move.",
    "minutes": 1,
    "notes": "We chose a hybrid. Short implementation tasks, often intended to be around two to five minutes, sit inside a coherent work package. That time is a planning heuristic, not a promise about model or developer speed. The package has an owner, dependencies and an observable acceptance condition. We execute and review the coherent unit, rather than creating a meeting for every tiny edit. For the dashboard, a useful package is consistent filters and export. Its tasks clarify semantics, centralize filtering and check the exported result. Risk sets review depth. A color change and a tenant-boundary change should not get identical ceremony.",
    "showSubtitle": true,
    "evidenceLabel": "Review depth follows risk",
    "cue": "Small steps inside one outcome we can actually review.",
    "stageAction": "Trace the three tasks, then read the acceptance line. Explain the 2–5 minute heuristic orally.",
    "bridge": "That is the method. Time to find out whether it makes any difference."
  },
  {
    "id": "experiment",
    "chapter": "The kitchen demo",
    "type": "experiment",
    "title": "One brief.\nThree ways to build.",
    "subtitle": "Naked Copilot → Lintel → Lintel + Swarming",
    "minutes": 1,
    "notes": "This replaces the old two-dashboard exhibit. The new kitchen test builds Service House: a working restaurant operations app. Every arm receives the same prompt, public brief, fixture, selectors and starter. Naked Copilot uses one session without Lintel or delegation. Lintel uses the finalized pinned workflow, serial packages and independent review. Lintel + Swarming uses the same Lintel version and delegate configuration, with independent implementation packages in parallel.\n\nTV-chef delivery still works: run the comparison beforehand and inspect the frozen outputs in the local dashboard. This presentation snapshot has no completed three-arm results. A local naked-only pilot is not the three-arm comparison. Do not imply that a reference fixture is an agent result. The benchmark must be authorized and run before showing a winner.",
    "showSubtitle": true,
    "evidenceLabel": "New kitchen protocol · comparative results pending",
    "cue": "Same kitchen. Same order. Three ways to run the pass.",
    "stageAction": "Introduce the three treatments. Say that the public snapshot contains no completed three-arm comparison.",
    "bridge": "First, freeze what a finished kitchen actually means."
  },
  {
    "id": "brief",
    "chapter": "The kitchen demo",
    "type": "brief",
    "title": "“Just a kitchen app.”\nFamous last words.",
    "subtitle": "32 observable requirements. 100 possible points.",
    "minutes": 1,
    "notes": "Service House has Menu, Orders, Inventory and Reports, with a basket and checkout. It includes exact cents, combined filters, order transitions, stock reservation, persistence, reports, CSV, theme, mobile and keyboard behavior. There are 32 frozen requirements; K16 ticket creation and K25 persistence weigh five points, every other requirement three, totaling100.\n\nThe shared prompt explicitly says not to ask follow-up questions. Important business choices are already in the brief. Unlike the old example, this experiment does not measure discovery of missing stakeholder answers. It measures whether each workflow carries the same explicit requirements into the build and verification. Show the exact prompt, not a paraphrase masquerading as the input.",
    "showSubtitle": true,
    "evidenceLabel": "Service House · frozen public contract · synthetic data",
    "cue": "The homepage is the easy part. The dinner shift is the test.",
    "stageAction": "Open the brief. Point to exact currency, cancellation and persistence—not all32 rows.",
    "bridge": "Now we can inspect the same dinner shift in each result."
  },
  {
    "id": "results",
    "chapter": "The kitchen demo",
    "type": "results",
    "title": "The dinner shift\nis the demo.",
    "subtitle": "Try the same actions in all three arms.",
    "minutes": 4,
    "notes": "The public guide explains the experiment; the actual read-only dashboard runs locally on port 4310. It is not a static Pages app and no live trial telemetry is published here. When comparative runs are ready, show all arms, including failures and timeouts. Open their real apps from the dashboard, then use the same operations.\n\nFirst, order two soups and a lemonade with KITCHEN10: total 21.29 dollars. Second, cancel an eligible ticket and verify stock is restored once. Third, reload and verify orders, statuses, basket and inventory persist without a duplicate checkout. Finally, inspect an individual requirement failure in the ledger.\n\nIf the measured candidates are unavailable, show the frozen brief and empty comparison state. A reference app can illustrate intended behavior only if named as a fixture. Never use it as the Lintel arm or fabricate a winner. Keep this inspection to four minutes.",
    "showSubtitle": true,
    "evidenceLabel": "Local dashboard for actual evidence · no published comparison yet",
    "cue": "Pretty is the opening act. Correct is the dinner service.",
    "stageAction": "Open the local dashboard if prepared. Inspect the same actions in each completed candidate. If runs are pending, walk the contract only and say so.",
    "bridge": "The critical choices were supplied up front. Did they survive implementation?"
  },
  {
    "id": "questions",
    "chapter": "The kitchen demo",
    "type": "questions",
    "title": "No questions.\nNo moving goalposts.",
    "subtitle": "The decisions are in the brief. Make them survive the build.",
    "minutes": 3,
    "notes": "The earlier kitchen demo used stakeholder questions. This replacement deliberately freezes the answers. The prompt forbids follow-up questions, so we must not invent question logs or praise one arm for asking more.\n\nFollow K14: subtotal 21.50, discount 2.15, tax 1.94, total 21.29. The implementation must preserve cents and the stated rounding. Follow K20: cancellation restores stock exactly once, including protection against repeated actions. Follow K25: reload preserves state without duplicating checkout.\n\nThese are contract traces we intend to inspect, not explanations of an observed winner. A plan is thin when it says add checkout but loses these conditions. A workflow earns its cost when the conditions remain visible through implementation and independent checking.",
    "showSubtitle": true,
    "evidenceLabel": "Illustrative contract traces · not agent transcripts",
    "cue": "This time, “what did you mean?” is already answered.",
    "stageAction": "Trace one of three contracts: cents, cancel-once stock, or reload persistence.",
    "bridge": "Depth is whether the requirement reaches a check, not how long the plan looks."
  },
  {
    "id": "plans",
    "chapter": "The kitchen demo",
    "type": "plans",
    "title": "A plan should\nleave fingerprints.",
    "subtitle": "Requirement → work package → implementation → independent check.",
    "minutes": 2,
    "notes": "This diagram is an expected trace, not an actual plan from a completed trial. Once the runs exist, inspect the real files in each candidate without inventing missing artifacts. Does K20 have an owner, dependency and observable acceptance? Does the implementation reserve and restore stock consistently? Can independent review identify the exact content it checked?\n\nThe serial and swarm treatments must retain the same review policy. Parallelism changes scheduling, not the quality bar. A larger plan is not automatically better, and missing native reviewers cannot be replaced by the builder declaring itself independent. Measure whether useful structure survives at a reasonable cost.",
    "showSubtitle": true,
    "evidenceLabel": "Expected trace · actual plan comparison awaits runs",
    "cue": "Do not count pages. Follow K20.",
    "stageAction": "Trace cancellation through ownership, implementation and observable stock restoration. When runs exist, open their actual artifacts.",
    "bridge": "Then separate what we measure. A fast response is not a finished product."
  },
  {
    "id": "ab-evidence",
    "chapter": "The kitchen demo",
    "type": "scoreboard",
    "title": "Four measures.\nZero invented winners.",
    "subtitle": "Speed, completeness and cost are different questions.",
    "minutes": 1.5,
    "notes": "First HTTP response, usable UI and declared completion are separate timestamps. A timeout is not completed work. The independent headless grader evaluates 32 requirements for 100 possible points and preserves failures and screenshots. All coordinator, worker, reviewer and retry costs belong in actual billed credits; tokens and model multipliers are not billed credits. Missing or partial receipts remain unknown or partial.\n\nRecorded harness self-checks show the reference fixture at 100/100 and the incomplete control at 0/100. These prove grader mechanics for those fixtures, not Lintel performance. Comparative outcomes are not published in this snapshot. Do not transplant the old 14/14 comparison into this experiment.",
    "showSubtitle": true,
    "evidenceLabel": "Reference/control checks ≠ comparative model results",
    "cue": "Unknown credits are unknown—not a very impressive zero.",
    "stageAction": "Read time-to-live, declared completion, coverage and billed credits separately. Reference100/100 is calibration only.",
    "bridge": "Even when results arrive, one more distinction matters: what did we actually change?"
  },
  {
    "id": "why-different",
    "chapter": "The kitchen demo",
    "type": "causal",
    "title": "Let the baseline win.\nIf it wins.",
    "subtitle": "A benchmark that cannot disappoint you is a demo trick.",
    "minutes": 1.5,
    "notes": "Naked versus Lintel changes the workflow and also permits delegate models. It compares a workflow/model configuration, not the isolated causal effect of a text file. The two Lintel arms keep the same version, delegate models and independent review policy; serial versus parallel packages is their intended difference. Record actual resolved models. A separate all-same-model series would add a useful control.\n\nActive implementation overlap is needed to verify swarming; overlapping session lifetimes or parallel reviewers do not establish it. Run arms sequentially, then counterbalance orders over independent repetitions. Three windows building simultaneously make a good spectacle, but introduce resource contention. Keep timeouts, failures, exclusions and sample counts. The result may be no gain—or negative net value. That is useful.\n\nWe now leave the new benchmark and inspect historical deterministic helper examples. Their original source pins remain visible; they are not current Universal acceptance runs.",
    "showSubtitle": true,
    "evidenceLabel": "Hypothesis until measured · no causal speedup claim",
    "cue": "The result gets a vote. My favourite tool does not get a head start.",
    "stageAction": "Name the model-mix confound. Explain the cleaner serial-versus-swarm question.",
    "bridge": "While that comparison is pending, here are three smaller mechanisms we have saved evidence for."
  },
  {
    "id": "profile",
    "chapter": "Under the hood",
    "type": "profile",
    "title": "A profile should\nchange the work.",
    "subtitle": "“Enterprise” is not a theme color.",
    "minutes": 2,
    "notes": "Remember the pack from the kit screen: the team’s standards. This switches between two of them, a lab and a customer pilot. Switch between Lab and Customer pilot. This is a separate, deterministic demo: no model runs here, and it is not part of the paired agent builds. The actual Lintel pack resolver supplies values from two synthetic manifests. A presentation consumer turns them into the displayed contract. Notice the evidence requirement changes from a smoke test to a tenant negative test; identity and network design requirements change too. The demo_policy fields are custom presentation fields. No identity or network infrastructure is provisioned, and hard mode is a configuration value, not proof of enforcement. The value hypothesis is concrete: a profile should change decisions, questions and acceptance evidence.\n\nThis saved mechanism proof predates the Universal integration. It retains its original provenance. Current Universal adds content-bound profile identity, shared lifecycle recovery and structured evidence; this older run does not verify those additions.",
    "showSubtitle": true,
    "evidenceLabel": "Historical helper proof · original source pin · not Universal acceptance",
    "cue": "Enterprise is not a theme color. The requirements must change.",
    "stageAction": "Toggle Lab → Customer pilot. Read the changed evidence field.",
    "bridge": "A profile changes the requirements. Now lose the chat and see what survives."
  },
  {
    "id": "cold-start",
    "chapter": "Under the hood",
    "type": "cold",
    "title": "Delete the chat.\nKeep the plot.",
    "subtitle": "The next session needs coordinates, not a séance.",
    "minutes": 2,
    "notes": "This is the window idea, applied: assume the session is gone — what is left on disk? We do not delete anything in your real repo. The prepared proof creates a local clone of a synthetic fixture without the ignored runtime ledger. The committed specification, plan, tasks and handoff survive. Show the four pointers and the next action T002. The helper validates the map and file boundaries; the explicit handoff supplies the next task. It is not the helper reasoning about priorities. Missing files and a path escaping the repo are rejected in the saved run. A fresh agent still needs to read and reason about those artifacts, but it no longer has to recover the project from chat archaeology. The four on-screen labels stand for the exact committed paths shown in the offline field guide and helper proof explorer.\n\nThis saved mechanism proof predates the Universal integration. It retains its original provenance. Current Universal adds content-bound profile identity, shared lifecycle recovery and structured evidence; this older run does not verify those additions.",
    "showSubtitle": false,
    "evidenceLabel": "Historical helper proof · original source pin · not Universal acceptance",
    "cue": "We lose the runtime, not the plot.",
    "stageAction": "Trace the four committed pointers to T002. The saved helper checks the map.",
    "bridge": "The plot survived. Does a lesson?"
  },
  {
    "id": "regression",
    "chapter": "Under the hood",
    "type": "regression",
    "title": "A lesson that never returns\nis just a diary entry.",
    "subtitle": "Capture → retrieve → verify → reinforce.",
    "minutes": 3,
    "notes": "Show Before: lookup by document ID allows another tenant's document. Switch to Fixed: the same three tests now include the tenant condition. Then select Reintroduce bug: deliberately run the vulnerable version again and watch the cross-tenant check fail. That is the important negative control. The prepared lesson is retrieved through the real keyword-scoped memory helper; an obsolete lesson and an unrelated lesson are excluded. This is not model training and not proof of production authentication. It is an example of turning a specific correction into both reusable context and executable protection. Read the red result aloud for remote participants.\n\nThis saved mechanism proof predates the Universal integration. It retains its original provenance. Current Universal adds content-bound profile identity, shared lifecycle recovery and structured evidence; this older run does not verify those additions.",
    "showSubtitle": false,
    "evidenceLabel": "Historical helper proof · original source pin · not Universal acceptance",
    "cue": "Put the bug back. Does the test notice?",
    "stageAction": "Click Before → Fixed → Reintroduce bug. Read the red result aloud.",
    "bridge": "One correction, two homes: a lesson and a test. That generalises."
  },
  {
    "id": "compound",
    "chapter": "Under the hood",
    "type": "compound",
    "title": "Correct once.\nMake the correction travel.",
    "subtitle": "Different artifacts remember different things.",
    "minutes": 1,
    "notes": "A lesson remembers a failure mode and when to look for it. An ADR remembers a decision and its rationale. A skill remembers the reusable method. A test remembers an observable boundary. They work together, but they are not interchangeable. Do not turn every preference into a permanent constitutional rule. Record scope, source and review status; retire what becomes wrong. Compounding context means the next relevant task starts with better material. It does not mean an ever-growing prompt, and it does not promise an exponential learning curve.",
    "showSubtitle": false,
    "evidenceLabel": "Compounding context, not model training",
    "cue": "A correction becomes useful when the next relevant task can find it.",
    "stageAction": "Explain the different jobs of a lesson, ADR, skill and test.",
    "bridge": "That is what it can do. Now the honest part: what it cannot."
  },
  {
    "id": "enforcement",
    "chapter": "The honest value",
    "type": "enforcement",
    "title": "Markdown can tell you to lock it.\nIt cannot be the lock.",
    "subtitle": "Guidance, checks and authority have different jobs.",
    "minutes": 1,
    "notes": "This matters when we talk to customers. The harness can structure the work, ask for evidence and invoke supported checks. Actual permissions, identity, network isolation, CI and deployment approvals must be configured and verified in the platform. A skill saying use least privilege does not grant or enforce least privilege. Likewise, universal method does not mean every host supports the same hooks or parallel agents. Keep this distinction crisp. It makes the rest of the story more credible and gives architects a clear boundary.",
    "showSubtitle": false,
    "evidenceLabel": "Platform controls must be configured and verified.",
    "cue": "The instruction describes the lock. The platform has to provide it.",
    "stageAction": "Point to both objects; name permissions and CI as examples.",
    "bridge": "If it cannot enforce, and models keep getting better — what lasts?"
  },
  {
    "id": "smarter-models",
    "chapter": "The honest value",
    "type": "knowledge",
    "title": "A smarter model still wasn’t\nin last week’s meeting.",
    "subtitle": "The durable advantage is your context — not a generic expert persona.",
    "minutes": 1,
    "notes": "As models and native agent tools improve, generic advice to plan carefully or act like an expert becomes weaker differentiation. The strongest value hypothesis is project-specific knowledge: why we rejected an alternative, which requirement the team accepted, what must survive a handoff, and which check has caught a real mistake. The model cannot recover an unavailable decision by being more intelligent. Native tools already provide useful building blocks; Lintel must earn its place through the content, coordination and observed results. That is why this demonstration compares against a competent repo with ordinary project instructions and checks, rather than an artificially weak prompt-only baseline.",
    "showSubtitle": false,
    "evidenceLabel": "Illustrative ADR · the value hypothesis is project-specific knowledge",
    "cue": "Even a smarter model was not in last Tuesday’s meeting.",
    "stageAction": "Use the rejected-option example. Intelligence cannot replace unavailable project knowledge.",
    "bridge": "Context is the asset. Process is the cost."
  },
  {
    "id": "small-core",
    "chapter": "The honest value",
    "type": "smallcore",
    "title": "Less surface.\nKeep the depth.",
    "subtitle": "127 skills today → about 80 planned.",
    "minutes": 1,
    "notes": "My biggest concern is negative net value. More roles, instructions and review stages can add latency, conflicts and maintenance. A nine-stage cycle does not automatically belong in a one-line fix. The small core is current intent, relevant project knowledge, a checkable next action and proportionate verification. Add deeper architecture, security review or orchestration when risk or coordination needs justify it. Lintel's subtraction decision points in this direction. Its eval decision calls for evidence; an accepted direction is not proof that every evaluation capability is implemented. In a pilot, measure time to an accepted change, interventions, residual defects, cost and cold-session recovery. If process costs more than it prevents, simplify it.\n\nI am consolidating roughly 120 skills toward about 80. Today the inspected source still has 127 definitions. The goal is fewer overlapping entry points with richer workflows behind them, not deleting valuable capability. This reduction is planned, not delivered, and the count alone proves no quality improvement.",
    "showSubtitle": true,
    "evidenceLabel": "Consolidation target · preserve useful capability",
    "cue": "Fewer things to choose. Keep the parts that do useful work.",
    "stageAction": "Contrast a label change with a tenant-boundary change.",
    "bridge": "Keep it small, and it helps the people who are just starting."
  },
  {
    "id": "vibe",
    "chapter": "The honest value",
    "type": "vibe",
    "title": "Vibe coding.\nWith a return address.",
    "subtitle": "Keep the fast start. Add a route back to intent.",
    "minutes": 1,
    "notes": "For someone new to Copilot or another coding agent, this can reduce the blank-page problem. Start from a workflow: explain the outcome, resolve the important ambiguity, build one reviewable slice, and verify it. Show the person the questions and acceptance conditions, rather than making a giant instruction file they never read. For a customer this is a pilot hypothesis, not a promise of acceleration. Measure whether the newcomer needs fewer repeated explanations and produces a more defensible handoff. Keep the workflow light enough that it is actually used.",
    "showSubtitle": false,
    "evidenceLabel": "Acceleration is a hypothesis to test.",
    "cue": "Keep the fast start. Give it a route back to the agreed intent.",
    "stageAction": "Connect the four steps to a newcomer’s first small change.",
    "bridge": "That is the newcomer. Here is what it could mean for the rest of us."
  },
  {
    "id": "team-value",
    "chapter": "The honest value",
    "type": "team",
    "title": "Different roles.\nShared context.",
    "subtitle": "One shared contract. Three different jobs.",
    "minutes": 1,
    "notes": "For demo builders, the opportunity is more reproducible demos, a clear story about trade-offs and less time reconstructing context before a customer meeting. For architects, it is explicit constraints, traceable decisions and a cleaner architecture handoff. For customer developers, especially newcomers, it is a practical way to turn an intent into a verifiable slice without having to invent the review discipline each time. These are proposed benefits to test in a bounded pilot. We are not claiming a measured customer outcome from this presentation.",
    "showSubtitle": false,
    "evidenceLabel": "Proposed benefits · validate in a pilot",
    "cue": "The same context helps us in different parts of the customer journey.",
    "stageAction": "Give one concrete benefit each for demo builder, architect and developer.",
    "bridge": "None of that is proven yet. So do not adopt it — test it."
  },
  {
    "id": "pilot",
    "chapter": "The honest value",
    "type": "pilot",
    "title": "Don’t roll out a philosophy.\nRun a small experiment.",
    "subtitle": "One workflow. One team. A clear reason to keep it — or stop.",
    "minutes": 1,
    "notes": "Pick a repeating workflow, such as a customer demo dashboard or a prototype handoff. Agree what good looks like before running it. Track rework, missed requirements, handoff completeness and time spent maintaining the workflow. Use several comparable tasks, not only the most flattering run. Keep human review and the same underlying platform controls. Stop or simplify if the method costs more effort than the problems it prevents. A successful pilot gives us a reusable asset and evidence; an unsuccessful pilot gives us a useful boundary.",
    "showSubtitle": false,
    "evidenceLabel": "Several comparable tasks · same knowledge and controls",
    "cue": "One repeating workflow. Several comparable tasks. Then decide.",
    "stageAction": "Point at the four measurements on screen. Keep “what would make us stop?” rhetorical — the discussion is next.",
    "bridge": "Which brings me to you."
  },
  {
    "id": "discussion",
    "chapter": "Your turn",
    "type": "discussion",
    "title": "What are you tired\nof explaining twice?",
    "subtitle": "Pick one recurring task. Name the mistake. Decide what should remember it.",
    "minutes": 4,
    "notes": "Give the room a few seconds to think, then take one answer from a remote participant first. Ask for a specific recurring task rather than general enthusiasm about agents. Which part should be a skill? Which decision belongs in an ADR? Which mistake deserves a regression test? What would make this too heavy? The goal is not to collect a huge roadmap in four minutes. Choose one candidate workflow and an observable failure that a pilot could try to prevent. If there is disagreement, use it: different contexts may need different harnesses.",
    "showSubtitle": false,
    "evidenceLabel": "4 minutes · choose one pilot candidate",
    "cue": "What are you tired of explaining twice?",
    "stageAction": "Take a remote participant first. Choose one task, one recurring failure and what should remember it.",
    "bridge": "Let me close with the short version."
  },
  {
    "id": "take-it-with-you",
    "chapter": "Your turn",
    "type": "handoff",
    "title": "The talk ends.\nThe toolkit stays.",
    "minutes": 0.5,
    "cue": "Four things to take forward. One available today; three links to follow.",
    "stageAction": "Name the four deliverables. Explain Core as the small, explicit workflow shell for a customer case. Point attendees to the public site.",
    "bridge": "Start with one workflow worth remembering.",
    "evidenceLabel": "Handoff roadmap · Core, CAIP pack and Benchmark links to follow",
    "notes": "You will get four things. Lintel is the full open-source harness. Pack number one adds the MS employee in CAIP context; its distribution link will follow. Lintel Core is the planned stripped-down shell for building a specific customer harness. The intention is explicit, on-demand use inside the customer’s existing coding desktop or CLI, including GitHub Copilot. It is useful when a person is driving a bounded workflow and a separate hosted agent or dedicated application would add unnecessary operational work. It does not replace hosted orchestration when you need unattended execution, shared services, durable infrastructure or platform controls.\n\nLintel Benchmark is the planned evaluation package; its link will follow too. The prepared A/B lab on this site is available now, but it is not a statistically established productivity benchmark. No private employee pack is included in this public site. The presentation, technical reference, notes and prepared browser demos can already be used here or downloaded as an offline kit."
  },
  {
    "id": "close",
    "chapter": "Your turn",
    "type": "close",
    "title": "Keep the creativity.\nStop paying twice.",
    "subtitle": "For the same explanation. The same decision. The same mistake.",
    "minutes": 0.5,
    "notes": "Close on the practical loop. Three rows, three things we keep paying for twice. The same explanation: write the plan and the handoff where the next session can read them. The same decision: record why, not only what. The same mistake: capture the lesson and give it a test. State the intent. Make the work inspectable. Keep the decisions alive. Retrieve the right lessons. Verify what matters. Lintel is my attempt to make that loop reusable across the tools I work in. It does not replace engineering judgment; it gives that judgment somewhere durable to live. Invite the team to inspect the actual prepared outputs and the comparison protocol in the package; the repository address is on screen. If we named a task in the discussion, try it on that one and tell me what it cost. End on time.",
    "showSubtitle": false,
    "evidenceLabel": "Structure that supports the work.",
    "cue": "Keep the creativity. Stop paying twice.",
    "stageAction": "Do not read the rows; give today’s example for each: the 09:12 agreement, the rejected option B, the tenant leak. Pause. End on time."
  },
  {
    "id": "title",
    "chapter": "Reference",
    "type": "title",
    "title": "Tame the work.\nKeep the spark.",
    "subtitle": "From vibe coding to deliberate engineering.",
    "minutes": 0,
    "notes": "That was the cold open; this is the talk. A personal engineering journey, not a Microsoft product announcement. The four promises are on screen, so do not read them out. Add only what the screen lacks: the A/B test includes the part that did not go my way. The rail at the top shows the seven parts of the story and where we are, so you can always find your place again. If you are new to coding agents, the next couple of minutes are for you.",
    "showSubtitle": true,
    "evidenceLabel": "A personal engineering journey",
    "cue": "I’m Johannes. Fifty minutes: why that happens, and what I did about it.",
    "stageAction": "Let the image breathe for a beat. Do not read the list; add only what the screen lacks. Point once at the act rail at the top.",
    "eyebrow": "Fifty minutes · four promises",
    "bridge": "First, the one idea that explains almost everything else today.",
    "optional": true
  },
  {
    "id": "failure-modes",
    "chapter": "Reference",
    "type": "drift",
    "title": "The agent is busy.\nThe project is elsewhere.",
    "subtitle": "Activity is easy to see. Drift is harder.",
    "minutes": 0,
    "notes": "Three failures. Two follow directly from the window you just saw, and the third is made worse by it. Context rot: the relevant constraint is still in there somewhere, but it is no longer effectively guiding the response. Goal drift: the work has moved away from the agreed outcome. A broken handoff: the session ended, and the next one cannot reliably find the current decision or next task. These can look similar, but adding a longer prompt is not a universal fix. A model may also stop because of a tool, budget or permission boundary; we should inspect the cause rather than diagnose every stop as forgetting. The graphic is a metaphor. Useful questions: what was the last accepted outcome, what evidence exists, and where is the next action recorded?",
    "showSubtitle": true,
    "evidenceLabel": "Metaphorical illustration",
    "cue": "The agent can be busy while the project gets no closer to done.",
    "stageAction": "Name the three failures. Explain that stopping can also be a tool or permission boundary.",
    "bridge": "I met all three. Here is what I did about it — badly, at first.",
    "optional": true
  },
  {
    "id": "one-small-request",
    "chapter": "Reference",
    "type": "firstsession",
    "title": "Small change.\nUseful trail.",
    "subtitle": "“Add a health endpoint with a focused acceptance test.”",
    "minutes": 0,
    "notes": "Make it concrete. This is the small first-session example from the README, illustrated here rather than executed live. A health endpoint is simply a URL that reports whether a service is responding. Ask the agent to plan the change using Lintel. The plan records what success means and the work to do. After the plan is reviewed and execution is authorized, the agent builds the change and runs the focused check. The review and handoff say what changed, what was checked and what the next person should know. The thing to remember is the trail: request, agreed work, checked result, reusable context. Notice what that trail is made of: files. The README runs this example by starting at the planning step directly — any single step can be run on its own. It is not a hotfix: a hotfix has no plan step, and this screen shows an agreed plan.",
    "showSubtitle": false,
    "evidenceLabel": "Illustrated README example · not a recorded execution",
    "cue": "This one is new behaviour, not a fix — so it starts with a plan.",
    "stageAction": "Read the request once. Trace plan → checked result → handoff. Thirty seconds.",
    "bridge": "So where does that trail actually live?",
    "optional": true
  },
  {
    "id": "swarm",
    "chapter": "Optional +5",
    "type": "swarm",
    "title": "More agents.\nSame need for a plan.",
    "subtitle": "Parallelize independent work, not shared confusion.",
    "minutes": 5,
    "optional": true,
    "notes": "Optional five-minute extension only. Preserve the swarming direction: one coordinator, explicit dependency map, separate write scopes, attributable changes and independent review before integration. The diagram is an illustrative topology, not an executed swarm in this presentation. Parallel work is useful when tasks are independent and the host can isolate ownership. Otherwise replay the same briefs serially. Keep the authoritative task map single and treat coordination metadata as coordination. More agents amplify both good structure and unclear responsibility.",
    "showSubtitle": false,
    "evidenceLabel": "Optional topology illustration · not an executed swarm",
    "cue": "More agents amplify the plan you give them.",
    "stageAction": "Optional only. Explain ownership, isolation and independent review."
  },
  {
    "id": "architecture",
    "chapter": "Reference",
    "type": "architecture",
    "title": "Same method.\nDifferent cockpit.",
    "subtitle": "A universal core, adapted to the client you work in.",
    "minutes": 0,
    "notes": "Think of three layers. The client is where you interact with the model and tools: a CLI, an editor or a coding desktop app. Lintel provides portable working instructions, skills, roles, packs and durable artifacts. The platform below still owns the real enforcement: permissions, CI, cloud policies and deployment gates. Shared workflow does not mean identical client capabilities. Native skill discovery, agents and hooks differ by host. In particular, a hook file existing in the repo is not proof that this host executes it. For today's comparison we are explicit about the curated workflow context that is loaded.",
    "optional": true,
    "showSubtitle": false,
    "evidenceLabel": "Host capabilities and enforcement differ.",
    "cue": "Portable method does not mean identical host capabilities.",
    "stageAction": "Reference only; use it to answer architecture questions."
  },
  {
    "id": "resources",
    "chapter": "Reference",
    "type": "resources",
    "title": "Open the hood.",
    "subtitle": "Source artifacts, reproducible checks and presenter controls.",
    "minutes": 0,
    "optional": true,
    "notes": "Open the new Service House kitchen guide, the historical helper proof explorer, the regenerated English notes or the current Universal technical inventory. The kitchen runs locally; its comparative results are pending. The historical two-dashboard build is no longer part of the current public exhibit.",
    "showSubtitle": false,
    "evidenceLabel": "Offline source artifacts and presenter guides",
    "cue": "Everything shown here is inspectable in the package.",
    "stageAction": "Reference only; open the requested artifact."
  },
  {
    "id": "product-family",
    "chapter": "Product launch",
    "track": "products",
    "optional": true,
    "type": "productfamily",
    "title": "Meet the Lintel family.",
    "minutes": 0.75,
    "cue": "Four packages, with a different job for each.",
    "stageAction": "Pause on the four motifs. Name each product once. Click an image to open the standalone artwork; each product label jumps to its slide.",
    "bridge": "Start with the complete system.",
    "notes": "Four products, four jobs. A portal for the complete system, layers for team context, an open frame for a focused workflow, and a reticle for measurement. Same family, different responsibilities. Think Unix philosophy, with slightly better lighting.\n\nLintel is the complete harness. The CAIP Pack brings our role and team context. Core is the planned smaller shell for a specific customer case. Benchmark is the planned way to test whether the added process is worth it.\n\nThey have different release states. Lintel is available in the public repository. The CAIP Pack distribution link will follow. Core and Benchmark are planned offerings; we will add their links later. The prepared comparison in this presentation is already available, but it is not the complete Benchmark product.",
    "evidenceLabel": "Product family · Core and Benchmark planned",
    "eyebrow": "THE PRODUCT FAMILY"
  },
  {
    "id": "product-lintel",
    "chapter": "Product launch",
    "track": "products",
    "optional": true,
    "type": "systemmap",
    "title": "Here’s the whole system.",
    "minutes": 1.5,
    "cue": "Lintel is the full working method around your existing coding agent.",
    "stageAction": "Walk from the client through the method to the written artifacts. End at the return loop. This is the same system map used in the introduction.",
    "bridge": "Now add context that is specific to the people doing the work.",
    "notes": "Lintel is the complete company-neutral harness. The coding client executes the work. Lintel supplies reusable workflows and helper scripts, specialist role instructions, a place for plans and decisions, and a way to bring useful knowledge back into the next task.\n\nThe pack is a separate input to the method. Skills and delegated roles do the work; invoked helpers and compatible registered hooks support it. The durable records travel with the project when committed. Temporary runtime files do not.\n\nPoint at the lower platform boundary: Markdown instructions are not platform enforcement. Permissions, sandboxing and CI still belong to the host and delivery environment. Hook coverage varies by client and verified registration.\n\nThis technical map describes the inspected development snapshot. The public release may differ; the reference distinguishes public source from unreleased excerpts.",
    "evidenceLabel": "Full harness · Inspected development snapshot · Hook coverage depends on the host",
    "eyebrow": "01 / LINTEL",
    "subtitle": "The complete workflow kit inside your existing coding tools.",
    "showSubtitle": true
  },
  {
    "id": "product-caip",
    "chapter": "Product launch",
    "track": "products",
    "optional": true,
    "type": "productpack",
    "title": "Your role.\nAlready in the room.",
    "minutes": 1,
    "cue": "The CAIP Pack brings team context to the universal method.",
    "stageAction": "Read the workshop request, then trace the added context to a more relevant brief. Describe this as the pack’s intended use.",
    "bridge": "What if a customer only needs one focused workflow?",
    "notes": "Imagine the request: prepare a customer technical workshop. Without the relevant team context, the agent has to rediscover the audience, expected evidence and our way of working.\n\nThe purpose of Lintel CAIP Pack, Pack number one, is to carry the MS employee in CAIP role and the approved team knowledge and standards that belong with it. The universal method stays in Lintel. The team-specific content stays in the pack. The example on this slide shows the intended value, not a live execution of a released pack.\n\nFor a solution engineer or architect, this could mean a workshop brief that starts with the right audience, a useful technical agenda and explicit questions still to resolve. The operator remains responsible for the customer context and approved inputs.\n\nThe pack’s distribution link will follow. This public presentation contains no private employee pack.",
    "evidenceLabel": "Lintel CAIP Pack · MS Employee in CAIP · Distribution link to follow",
    "eyebrow": "02 / LINTEL CAIP PACK"
  },
  {
    "id": "product-core",
    "chapter": "Product launch",
    "track": "products",
    "optional": true,
    "type": "productcore",
    "title": "One customer case.\nA smaller harness.",
    "minutes": 1.5,
    "cue": "Core is the planned shell for a focused workflow inside the customer’s coding app.",
    "stageAction": "Trace the explicit start, the chosen workflow and the reviewed artifact. Use architecture review as the example.",
    "bridge": "A smaller workflow still needs to prove that it helps.",
    "notes": "Core is the planned stripped-down version of Lintel. Start with the customer’s case and select only the context, workflow, records and checks it actually needs.\n\nThe intended interaction is explicit: a person asks to run the architecture-review workflow in the coding app they already use, including desktop GitHub Copilot. The harness helps produce a review and decision brief, with enough state to return to the work. It does not need to invoke itself automatically. That is the design intent for Core, not a claim that every host or existing full Lintel install already behaves this way.\n\nThis can avoid maintaining a separate application or hosted agent flow for a bounded, person-driven task. It still takes ownership, versioning and testing. It is not zero maintenance.\n\nWhen a case needs unattended execution, shared services, durable jobs or enforced platform controls, hosted infrastructure still has a job. The question is which runtime the use case requires. Core’s distribution link will follow.",
    "evidenceLabel": "Lintel Core · Planned shell · Explicit invocation is the design intent",
    "eyebrow": "03 / LINTEL CORE"
  },
  {
    "id": "product-benchmark",
    "chapter": "Product launch",
    "track": "products",
    "optional": true,
    "type": "productbenchmark",
    "title": "Does the harness\nearn its place?",
    "minutes": 1.25,
    "cue": "Benchmark should measure accepted work, including the cost of the harness.",
    "stageAction": "Point at what stays the same and what changes. Name the four measures. Open the prepared comparison only if time allows.",
    "bridge": "Choose one recurring task and measure the result.",
    "notes": "Lintel Benchmark is the evaluation direction. The current kitchen harness now defines three arms: Naked Copilot, Lintel serial and Lintel + Swarming. All share the Service House brief and 32 requirements for 100 points. It records usable UI, declared completion, requirement coverage and billed credits separately.\n\nThe harness and reference/control checks exist locally. The public page describes the method; it does not bundle the local server, publish trial/session records or claim completed comparative runs. The distribution link remains pending. This is not evidence of a productivity win. Normal Lintel versus naked also changes delegation/model mix; keep the caveat visible and repeat with matched models if isolating that effect.",
    "evidenceLabel": "Kitchen harness prepared · comparative results and distribution pending",
    "eyebrow": "04 / LINTEL BENCHMARK"
  },
  {
    "id": "tech-kit",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techkit",
    "title": "Open the toolbox.\nChoose a small working set.",
    "minutes": 1,
    "cue": "Universal 0.11.0 keeps one method across the clients we use. Choose the few parts this task needs.",
    "stageAction": "Enter through the Technical tab. Establish that this is a separate eighteen-minute module. Read the current count once, then distinguish planned curation from shipped change.",
    "bridge": "Start with the work loop, then add the expertise the task needs.",
    "notes": "This section describes merged Universal 0.11.0 at source revision 80002ed4. The source has 127 canonical skills, 69 agent roles and 33 hook scripts. Those are reusable source definitions, not everything loaded into one conversation, and not proof that every client executes every capability.\n\nThe next direction is curation toward roughly 80 skills while preserving useful methods. That is planned work, not a reduction this release already delivered. In particular, the preservation map’s 80 CAP records are an audit category, not an eighty-skill product. All original canonical paths and 46 aliases remain.\n\nThe useful unit is one outcome with the right context, clear ownership and enough evidence to accept it. We will follow that through the shared lifecycle, then look at where actual client tools change execution.",
    "evidenceLabel": "Universal 0.11.0 · source 80002ed4 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/80002ed4/skills/CATALOG.md#L10",
      "https://github.com/jokerman89/lintel/blob/80002ed4/.claude/plans/universal-implementation/reports/P13-skills-preservation.md#L414"
    ]
  },
  {
    "id": "tech-skills",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techskills",
    "title": "Start with the loop.\nAdd depth on demand.",
    "minutes": 1.5,
    "cue": "Plan the original work, build a bounded package, review its actual result and keep the useful lesson.",
    "stageAction": "Walk PLAN → BUILD → REVIEW → CAPTURE. Spend the extra sentence on REVIEW: a PASS heading is not enough. Keep specialist detail in the notes and reference.",
    "bridge": "A workflow defines the method. A role defines who owns a bounded piece of it.",
    "notes": "The nine-phase lifecycle stays intact. PLAN keeps the original requirements and task IDs in one work map. BUILD groups connected short leaves into a bounded package with one owner. Every leaf retains its acceptance evidence; a failed leaf keeps the package open. REVIEW and QA are bound to the selected content and requirements, so a previous pass cannot clear a changed result. CAPTURE preserves reviewed progress, decisions and lessons.\n\nTA, DA, SC, DH and TQ add architecture, data, security, delivery and testing depth. Their data helper records and verifies observations; the agent still performs the specialist work. Its output does not grant release clearance.\n\nBrowser operations and the design contract have bounded acceptance evidence, including a static page and a React/Vite app. Document-format capabilities remain staged: Word, PowerPoint, workbook and PDF end-to-end acceptance was removed from Universal’s scope, never passed or waived. The PDF writer remains; its removed reader cannot verify output text, pages or rendering. Visio has no writer.",
    "evidenceLabel": "Universal 0.11.0 · source 80002ed4 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/80002ed4/docs/concepts/engineering-modules.md#L3",
      "https://github.com/jokerman89/lintel/blob/80002ed4/skills/review/references/evidence.md#L73",
      "https://github.com/jokerman89/lintel/blob/80002ed4/.claude/decisions/0033-remove-document-format-acceptance-and-pdf-reader.md#L25"
    ]
  },
  {
    "id": "tech-agents",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techagents",
    "title": "Give each worker a job.\nAnd a boundary.",
    "minutes": 1.5,
    "cue": "A role is a bounded brief. Independent review needs an actual independent reviewer.",
    "stageAction": "Follow prepare → implement → challenge. Point to the coordinator. Distinguish isolated parallel writers from read-only parallel research.",
    "bridge": "The workers and reviewers need the same source of truth and the same ownership boundaries.",
    "notes": "A Planner or Architect clarifies requirements, alternatives and acceptance. A scoped worker implements one package and returns attributable changes and evidence for every leaf. A reviewer reports findings against that result; the reviewer does not repair its own findings. A different actor name or an available delegation tool is not proof of an independent invocation.\n\nSwarming is an opt-in execution profile over PLAN, BUILD and REVIEW. It adds committed briefs, scope and evidence pointers alongside the original work map. One coordinator owns shared state, generated reducers, commits and serial integration. Concurrent writers require disjoint write scopes and attributable worktrees, patches or equivalent host-enforced isolation. A union diff from a shared checkout cannot establish ownership.\n\nWithout safe concurrent execution, run the same briefs sequentially. Without a required independent reviewer, keep the substantive package open. Lane review does not replace final review of the reconciled integration branch.",
    "evidenceLabel": "Universal 0.11.0 · source 80002ed4 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/80002ed4/docs/concepts/swarming-work.md#L29",
      "https://github.com/jokerman89/lintel/blob/80002ed4/docs/concepts/swarming-work.md#L129",
      "https://github.com/jokerman89/lintel/blob/80002ed4/skills/review/references/evidence.md#L230"
    ]
  },
  {
    "id": "tech-storage",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techstorage",
    "title": "Four places.\nFour different owners.",
    "minutes": 2,
    "cue": "Trusted source, configuration home, project knowledge and local evidence have different owners and lifetimes.",
    "stageAction": "Point out the Git boundary. Toggle Bare install to Repo kit. Explain that the shared .github/lintel bundle serves the selected Universal clients, not only Copilot.",
    "bridge": "Now follow a task through those locations and watch how evidence changes.",
    "notes": "The trusted Lintel source supplies helpers, skills and roles. LINTEL_SOURCE_ROOT identifies it; LINTEL_REPO_ROOT identifies the exact working project. Never choose helper code from an untrusted target because its name happens to match.\n\nThe configuration home is explicit. A bare installation normally uses the personal .lintel home. Repository adapters default to the project’s .claude/runtime/lintel-home when no home was configured. The shared source bundle remains .github/lintel for compatibility and serves every selected Universal route; it installs no hook bundle.\n\nCurated plans, decisions, lessons and handoffs belong with the project and are committed intentionally. Ignored runtime includes the cycle ledger, review evidence, checkpoints and audit observations. Profile contexts keep a current-profile.json with verified generations; recovery transactions retain their receipt and snapshot together.\n\nA fresh clone receives committed intent, not ignored evidence or private policy. A receipt describes an observed local operation; it does not establish host activation, independent review or policy enforcement.",
    "evidenceLabel": "Universal 0.11.0 · source 80002ed4 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/80002ed4/docs/lifecycle.md#L9",
      "https://github.com/jokerman89/lintel/blob/80002ed4/docs/client-adapters.md#L18",
      "https://github.com/jokerman89/lintel/blob/80002ed4/docs/lifecycle.md#L104",
      "https://github.com/jokerman89/lintel/blob/80002ed4/lib/profile_context.py#L654"
    ]
  },
  {
    "id": "tech-cycle",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techcycle",
    "title": "Every phase leaves\ndifferent evidence.",
    "minutes": 2,
    "cue": "The same work and profile identity travel through the phases. The evidence changes as the work progresses.",
    "stageAction": "Select PLAN, BUILD and REVIEW; then CAPTURE if time permits. For REVIEW, explain current content plus immutable acceptance, rather than reading filenames aloud.",
    "bridge": "Those identities make a restart useful, and show when it must stop for reconciliation.",
    "notes": "A cycle begins with an explicit identity before its phases write state. The ledger carries the selected work map, original artifact paths and verified profile reference. SCOPE, DEFINE and DISCOVER add the relevant decisions and source knowledge. PLAN preserves one authoritative task artifact; Spec Kit keeps its original files and IDs.\n\nBUILD records acceptance per leaf while implementing and reviewing a coherent package. REVIEW adds a version-2 decision bound to the selected product snapshot and acceptance sources. Required QA obligations are selected before observations. Results cannot hide a failed requirement by dropping it, relabelling it advisory or inventing not-applicable after the fact.\n\nThe reader considers the latest applicable decision before its verdict. A later rejecting or malformed relevant decision blocks an older PASS. The delivery gate checks review and QA against the same context; it permits continuing work already authorized, not a new deployment.\n\nCAPTURE keeps verified progress, decisions and corrections useful for the next session. Human-readable reports remain useful, but their filename or PASS heading is not clearance.",
    "evidenceLabel": "Universal 0.11.0 · source 80002ed4 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/80002ed4/skills/spec-kit/references/work-map.md#L123",
      "https://github.com/jokerman89/lintel/blob/80002ed4/skills/build/SKILL.md#L330",
      "https://github.com/jokerman89/lintel/blob/80002ed4/skills/review/references/evidence.md#L261",
      "https://github.com/jokerman89/lintel/blob/80002ed4/skills/review/references/evidence.md#L302"
    ]
  },
  {
    "id": "tech-resume",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techresume",
    "title": "Restart from the work.\nVerify the context.",
    "minutes": 1.5,
    "cue": "A fresh session must find the original work, verify its context and identify the actual unmet step.",
    "stageAction": "Trace the committed index to original artifacts. Point to the profile/cycle check and the missing-review line. Do not imply that cloning reconstructs evidence.",
    "bridge": "Hooks can add observations around that workflow, when their actual host registration exists.",
    "notes": "Choose an operator-named work map, or an unambiguous active map linked from the committed todo and working state. Do not select by newest timestamp. The map points to the original specification, plan, tasks and handoff. Its source checkbox view does not certify acceptance.\n\nThe shared resume path selects the original cycle and verifies the profile context, generation, digest, required policy and target. Missing references or changed sources do not silently become a new neutral profile. An explicit transfer, rebind or replan is needed, with affected evidence reviewed again.\n\nSTARTING, BLOCKED and NEEDS_CONTEXT return to the same phase. A truncated DONE record cannot advance it. Committed artifacts let a new clone inspect intent; ignored local evidence and private policy do not appear by magic. Preserve attributable unfinished work and quarantine anything whose owner or review cannot be established. Missing required review keeps the work open.",
    "evidenceLabel": "Universal 0.11.0 · source 80002ed4 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/80002ed4/skills/spec-kit/references/work-map.md#L88",
      "https://github.com/jokerman89/lintel/blob/80002ed4/skills/spec-kit/references/work-map.md#L154",
      "https://github.com/jokerman89/lintel/blob/80002ed4/lib/workflow.sh#L183",
      "https://github.com/jokerman89/lintel/blob/80002ed4/docs/concepts/swarming-work.md#L172"
    ]
  },
  {
    "id": "tech-hooks",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techhooks",
    "title": "Hooks react.\nReceipts show what happened.",
    "minutes": 2,
    "cue": "Nine core registrations and twenty-four optional scripts. A recorded event is an observation, not a green light.",
    "stageAction": "Toggle the core and optional groups. Distinguish warning, block and observation. Explain one unavailable-scanner receipt instead of adding another inventory slide.",
    "bridge": "The workflow travels through more clients than this native hook adapter.",
    "notes": "The source contains 33 hook scripts. Nine core registrations use the Claude Code protocol across five event types; 24 more scripts remain optional or manually invoked. The Universal repository kit installs none, even for a selected Claude route. Copilot has vendor-native hooks, but this release does not translate Lintel’s bundle to them. Actual registration and firing still need evidence.\n\nTwo git scanners intentionally deny commits or pushes. Their supported literal command parser collects the relevant candidate content and refuses ambiguous inspection or missing scanners instead of treating failure as a clean scan. These remain bounded pattern scanners with explicit overrides, not complete data-loss prevention. Other scripts often warn or remind. Stop does not force continuation.\n\nThe new event catalog describes 23 producer categories and 66 record kinds, not 66 hooks. The event reader reports observed records only. A block receipt may say the check was not performed because the scanner was unavailable. Missing records mean unobserved; a record itself is not proof of host enforcement.",
    "evidenceLabel": "Universal 0.11.0 · source 80002ed4 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/80002ed4/hooks/hooks.json#L1",
      "https://github.com/jokerman89/lintel/blob/80002ed4/hooks/shared/_input.sh#L94",
      "https://github.com/jokerman89/lintel/blob/80002ed4/lib/event-catalog.json#L1",
      "https://github.com/jokerman89/lintel/blob/80002ed4/bin/li-events.py#L471"
    ]
  },
  {
    "id": "tech-clients",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techclients",
    "title": "One method.\nYour actual tools.",
    "minutes": 2,
    "cue": "Universal delivers shared adapters. Documented capability, delivered files and observed execution are three different things.",
    "stageAction": "Select Claude, Copilot and Gemini/OpenCode to show what changed. Keep the remaining surface matrix in the technical reference. Do not describe families as one uniform host.",
    "bridge": "The next boundary is the organization’s policy and the exact profile this work is using.",
    "notes": "The registry has 37 named surfaces across fourteen product families plus a manual fallback. Twenty-five records have native-format skill routes; thirteen use a manual route including that fallback. These count delivered contracts and files, not certified clients. A shared engine generates fourteen starter workflows and preserves the full canonical source bundle. Copilot additionally retains its three native role profiles.\n\nCodex CLI, desktop and IDE use .agents/skills; Codex cloud is manual. Cursor CLI, IDE and cloud use .cursor/skills. Gemini CLI and OpenCode CLI now have native-format routes; OpenCode desktop and IDE remain manual. Exact routes for Factory, Antigravity, Kiro, Devin, Junie, Cline, Continue and Aider are in the reference. Existing plugin and extension routes remain.\n\nAll selected repository routes share .github/lintel. The directory name does not make this Copilot-only. No Lintel hooks are installed by that route. The registry records only three partial Copilot App observations and no complete per-operation acceptance record. Actual discovery, questioning, delegation, isolation, review and resume must be checked in the selected client and version. Missing independent review remains open.",
    "evidenceLabel": "Universal 0.11.0 · source 80002ed4 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/80002ed4/docs/client-adapters.md#L18",
      "https://github.com/jokerman89/lintel/blob/80002ed4/lib/cli-tiers.yaml#L67",
      "https://github.com/jokerman89/lintel/blob/80002ed4/lib/cli-tiers.yaml#L117",
      "https://github.com/jokerman89/lintel/blob/80002ed4/shims/universal/ADAPTER.md#L65"
    ]
  },
  {
    "id": "tech-packs",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techpacks",
    "title": "Make “good” specific.\nKeep its identity stable.",
    "minutes": 1,
    "cue": "A required profile cannot silently disappear into neutral defaults. Its identity travels with the work.",
    "stageAction": "Follow require → resolve → verify. Say context, generation and digest once; explain them as which policy content this work was approved against.",
    "bridge": "The same discipline applies to the knowledge and receipts we preserve.",
    "notes": "Team requirements can name a required pack in .claude/profile-requirements.json. An explicit pack invocation is also required selection. Missing, malformed or incompatible required content blocks; it does not silently become the neutral baseline. An invalid optional legacy preference may use a validated neutral fallback only with an explicit diagnostic. profile.yaml retains role and mode preferences; it is not the pack selector.\n\nThe effective profile carries a context, generation and content digest. The resolver verifies requirements, selected manifests, ancestry, defaults and source/target identity. Same-time edits or a changed pointer still count as drift. An explicit, reason-bearing rebind preserves the previous generation and requires affected work to be replanned and reviewed.\n\nThis gives review a stable policy reference. It does not install an organization’s controls or prove those controls operated. Platform permissions and CI remain separately configured and verified; the initiative’s real required-policy enforcement remains unverified in the recorded acceptance setting.",
    "evidenceLabel": "Universal 0.11.0 · source 80002ed4 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/80002ed4/.claude/decisions/0029-required-profile-context.md#L24",
      "https://github.com/jokerman89/lintel/blob/80002ed4/docs/lifecycle.md#L152",
      "https://github.com/jokerman89/lintel/blob/80002ed4/.claude/plans/universal-implementation/reports/final.md#L133"
    ]
  },
  {
    "id": "tech-maintenance",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techmaintenance",
    "title": "Keep the lesson.\nKeep the evidence.",
    "minutes": 1.5,
    "cue": "Capture the rule and its reason. Retrieve it when relevant. Preserve evidence before disposing of scratch.",
    "stageAction": "Move across capture, retrieve and preserve. Separate a useful saved lesson from proof that it improved the next outcome; do the same for a receipt and enforcement.",
    "bridge": "Then test whether the whole setup works in the client that will use it.",
    "notes": "A correction should leave a dated rule with context and preventive action. Update or explicitly supersede an existing lesson when appropriate; keep the reason. Current architecture, specifications and accepted decisions outrank remembered advice. Loading the relevant lesson on the next task is observable behavior; improved outcomes need their own evidence.\n\nCheckpoints now include repository identity, refuse unsafe paths and avoid overwriting collisions. The mapped original work and verified profile reference must survive the handoff. A file reservation alone is not a completed checkpoint.\n\nOwned snapshots and recovery have concrete inventory and preimage checks. Snapshot retention protects recent copies, the newest five and incomplete operations; pruning requires explicitly selected eligible snapshots and refuses unowned content. Keep a transaction receipt with its referenced snapshot. That is bounded recovery, not a universal retention policy. Maintenance does not compact the host conversation or run a cleanup daemon. An event receipt records an observation, not quality or compliance clearance.",
    "evidenceLabel": "Universal 0.11.0 · source 80002ed4 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/80002ed4/scaffolding/01-foundation/CORE-PRINCIPLES.md#L25",
      "https://github.com/jokerman89/lintel/blob/80002ed4/skills/context-save/SKILL.md#L41",
      "https://github.com/jokerman89/lintel/blob/80002ed4/skills/maintenance/SKILL.md#L47",
      "https://github.com/jokerman89/lintel/blob/80002ed4/bin/li-snapshot.py#L376"
    ]
  },
  {
    "id": "tech-proof",
    "chapter": "Technical deep dive",
    "track": "technical",
    "optional": true,
    "type": "techproof",
    "title": "Installed is not\nthe same as working.",
    "minutes": 2,
    "cue": "Test discovery, accepted work, a cold restart and refusal cases. Measure outcomes and overhead.",
    "stageAction": "Use the four checks as the rollout checklist. End on the measured-outcome line. Offer the reference without opening its full inventory unless asked.",
    "bridge": "Choose one recurring task and run the same acceptance protocol in the clients your team actually uses.",
    "notes": "Pin the Lintel revision, client version, selected profile, tools and permissions. First verify which instruction, skill and role were actually discovered. Then execute one bounded task with original requirement IDs, a real acceptance check, attributable changes and the required independent review.\n\nRestart without the original chat. Select the same work map and original cycle, verify the profile and report the actual unmet step. Use synthetic negative cases: changed policy content, failed or skipped mandatory QA, later rejecting review, missing independent reviewer, ambiguous work map and edited managed files. A missing capability must remain visible.\n\nSource checks and hosted tests establish their stated boundaries, not every client’s runtime behavior or model quality. The current source includes bounded browser/design acceptance; document-format acceptance remains staged or removed as documented. Do not turn the historical demo into Universal evidence, or the merged initiative report’s stale 108/109 wording into a stronger closure claim without the exact final CI/review record.\n\nMeasure time to accepted change, interventions, rework, defects, recovery and total process cost under comparable conditions. A smaller useful working set and inspectable evidence are the proposition; a productivity improvement must be measured.",
    "evidenceLabel": "Universal 0.11.0 · source 80002ed4 · observed limits apply",
    "subtitle": null,
    "sources": [
      "https://github.com/jokerman89/lintel/blob/80002ed4/shims/universal/ADAPTER.md#L104",
      "https://github.com/jokerman89/lintel/blob/80002ed4/skills/review/references/evidence.md#L302",
      "https://github.com/jokerman89/lintel/blob/80002ed4/.claude/decisions/0033-remove-document-format-acceptance-and-pdf-reader.md#L25",
      "https://github.com/jokerman89/lintel/blob/80002ed4/.claude/plans/universal-implementation/reports/final.md#L133"
    ]
  }
];
