// component: current-presentation-scenes
// intent: ../README.md
// constraints: source-backed diagrams; pending benchmark data must never look measured
// last_intent_review: 2026-09-28
window.LINTEL_REFRESH=({shell,icon,viewButton})=>{
 const arms=[['01','terminal','Naked Copilot','One fresh session','No Lintel · no delegation'],['02','layers','Lintel','Serial work packages','Independent review retained'],['03','route','Lintel + Swarming','Parallel ready packages','Same review policy + delegate models']];
 const tickets=()=>'<div class="kitchen-tickets">'+arms.map(([n,i,title,mode,detail])=>'<article class="kitchen-ticket"><div class="ticket-number">ORDER / '+n+'</div>'+icon(i)+'<h2>'+title+'</h2><p class="ticket-mode">'+mode+'</p><small>'+detail+'</small><span class="ticket-state">RESULTS PENDING</span></article>').join('')+'</div>';
 const guide=(label='Open the kitchen guide',anchor='')=>viewButton(label,'../comparison/index.html'+anchor,'Service House · kitchen test');
 return {
 githubmoment:s=>shell(s,'<figure class="github-proof"><img src="../assets/swarming/github-tab.png" alt="PR93 shows740commits and760files; the browser says This page is not responding. The screenshot does not establish a GitHub outage."><figcaption><b>740 commits</b><span>760 files</span><em>Throughput still needs a delivery boundary.</em></figcaption></figure>','refresh github-moment'),
 clients:s=>shell(s,'<div class="client-family-grid">'+[['Claude','.claude/skills'],['GitHub Copilot','.github/skills'],['Codex','.agents/skills'],['Cursor','.cursor/skills']].map(([n,p])=>'<article>'+icon('terminal')+'<h2>'+n+'</h2><code>'+p+'</code></article>').join('')+'</div><div class="universal-surface"><span>CLI</span><span>Desktop</span><span>IDE</span><span>Cloud</span></div><div class="evidence-ladder"><span>Vendor documented</span><b>→</b><span>Lintel delivered</span><b>→</b><span>Host observed</span></div><div class="refresh-bottom"><p>13 named surfaces + explicit manual fallback.<br>Codex cloud is manual. Repo kit installs no hooks.</p>'+viewButton('Exact surface matrix','technical-reference.html#clients','Current client registry')+'</div>','refresh'),
 reviewmethod:s=>shell(s,'<div class="review-scene"><article class="review-question"><span>ONE CONCRETE QUESTION</span>'+icon('bubble')+'<h2>Can cancel restore<br>stock twice?</h2><p>Show the input.<br><strong class="accent">Show what actually happened.</strong></p><code>K20 → implementation → repeated-cancel check</code></article><div class="review-account"><div>'+icon('compass')+'<section><h2>Ask the relevant questions</h2><p>Contract · boundaries · failure paths</p></section></div><div>'+icon('flask')+'<section><h2>Label the evidence</h2><p>Executed · traced · pattern · hypothesis</p></section></div><div>'+icon('file')+'<section><h2>Account for every question</h2><p>Findings, checked, N/A or not checked—with reasons</p></section></div><div class="review-rule">Changed inputs? Recheck.<br>Missing coverage? Still incomplete.</div></div></div>','refresh'),
 marspanel:s=>shell(s,'<div class="mars-diagram"><article class="mars-packet">'+icon('file')+'<span>ONE FROZEN SUBJECT</span><h2>Same brief.<br>Same rubric.</h2><p>Review Method packet</p></article><div class="mars-lanes" aria-label="Illustrative independent reviewer contexts">'+['A','B','C','D'].map((n,i)=>'<div>'+icon('person')+'<b>'+n+'</b><span>Separate context<br><strong>'+ (i===3?'Gaps stay visible':'Independent first pass')+'</strong></span></div>').join('')+'</div><article class="mars-synthesis">'+icon('scales')+'<span>COORDINATOR SYNTHESIS</span><h2><span class="accent">Evidence.</span><br>Not a vote.</h2><p>Findings · dissent · gaps<br>Challenge when needed</p></article></div><div class="recipe-rule"><b>DIFFERENT JOBS</b> Swarm <strong class="accent">builds</strong> packages. MARS <strong class="accent">reviews</strong> one subject.</div>','refresh'),
 productlintel:s=>shell(s,'<div class="first-task"><div class="first-task-prompt"><span>YOUR FIRST USEFUL TASK</span><blockquote>“Plan a health endpoint<br>with a focused acceptance test.”</blockquote><p>Inspect conventions. Agree the plan.<br><strong>Implement only when authorized.</strong></p></div><ol>'+[['compass','Select','Reviewed source + exact client'],['check','Verify','Real check + separate review'],['handoff','Resume','Same work in a fresh session']].map(([i,h,p])=>'<li>'+icon(i)+'<div><h2>'+h+'</h2><p>'+p+'</p></div></li>').join('')+'</ol></div><div class="refresh-bottom"><p class="accent">One accepted change. One useful handoff.</p><a class="action" href="https://github.com/jokerman89/lintel/blob/49f2d15260f096213086f02dfeb1fae6cbe62d45/docs/getting-started.md" target="_blank" rel="noopener">Start with one task ↗</a></div>','refresh product-slide first-task-slide'),
 experiment:s=>shell(s,tickets()+'<div class="recipe-rule"><b>SAME</b> Prompt · brief · fixture · starter · acceptance</div><div class="refresh-bottom"><p>Prepared ahead. Inspect together.<br>Only real runs earn a result.</p>'+guide()+'</div>','refresh'),
 brief:s=>shell(s,'<div class="service-house"><div class="service-brand"><span>THE DINNER SHIFT</span><h2>Service<br>House.</h2><p>A working operations app.</p></div><div class="service-menu">'+[['01','Menu','Find a dish. Build a basket.'],['02','Orders','Queue → cook → ready.'],['03','Inventory','Reserve. Cancel. Restore once.'],['04','Reports','Ready-ticket revenue + CSV.']].map(([n,t,d])=>'<div><small>'+n+'</small><strong>'+t+'</strong><p>'+d+'</p></div>').join('')+'</div></div><div class="refresh-bottom"><p>Exact cents · persistence · mobile · keyboard</p>'+guide('Read the exact prompt','#prompt')+guide('All 32 requirements','#requirements')+'</div>','refresh'),
 results:s=>shell(s,'<div class="dinner-actions"><article>'+icon('terminal')+'<b>01 / CHECK OUT</b><h2>$21.29</h2><p>2 soups + lemonade<br>with KITCHEN10</p></article><article>'+icon('route')+'<b>02 / CANCEL</b><h2>Once.</h2><p>Stock restored once.<br>Try the action again.</p></article><article>'+icon('archive')+'<b>03 / RELOAD</b><h2>Still here.</h2><p>Orders and stock persist.<br>No duplicated checkout.</p></article></div><div class="refresh-bottom"><p>Same clicks in every actual candidate.<br>Read failures in the requirement ledger.</p><a class="action primary" target="_blank" rel="noopener" href="http://127.0.0.1:4310">Open local dashboard ↗</a>'+guide('Guide / fallback')+'</div>','refresh'),
 questions:s=>shell(s,'<div class="contract-lines"><div><span>K14</span><strong>Money</strong><p>21.50 − 2.15 + 1.94 = <b>21.29</b></p></div><div><span>K20</span><strong>Cancellation</strong><p>Restore reserved stock <b>exactly once.</b></p></div><div><span>K25</span><strong>Persistence</strong><p>Reload the state. <b>Do not replay checkout.</b></p></div></div><div class="recipe-rule">The brief answers it. The work must preserve it.</div>','refresh'),
 plans:s=>shell(s,'<div class="contract-flow">'+[['K20','Restore stock once.'],['WORK PACKAGE','One owner. Clear dependency.'],['IMPLEMENTATION','Guard the terminal state.'],['INDEPENDENT CHECK','Repeat cancel. Inspect stock.']].map(([l,v])=>'<article><span>'+l+'</span><h2>'+v+'</h2></article>').join('')+'</div><div class="refresh-bottom"><p>A trace to inspect in the real runs.<br>Not a prewritten winning plan.</p>'+guide('How we compare','#protocol')+'</div>','refresh'),
 scoreboard:s=>shell(s,'<div class="measure-ledger">'+[['01','clock','Time to live','First usable UI.','Separately from first HTTP.'],['02','check','Declared completion','Timeouts stay timeouts.','Keep the actual completion status.'],['03','layers','Requirement coverage','32 checks · 100 points.','Show failures, not just a score.'],['04','scales','Billed credits','Count the whole run.','Sessions · workers · reviews · retries.']].map(([n,i,h,point,detail])=>'<article>'+icon(i)+'<div><h2><small>'+n+'</small>'+h+'</h2><p class="measure-point">'+point+'</p><p class="measure-detail">'+detail+'</p></div></article>').join('')+'</div><div class="refresh-bottom"><p><strong>Unknown ≠ zero.</strong><br>Reference-fixture scores are calibration only.</p>'+guide('Evidence status','#evidence')+'</div>','refresh measure-slide'),
 causal:s=>shell(s,'<div class="comparison-question"><article><span>NAKED → LINTEL</span><h2>Workflow<br>+ model mix.</h2><p>Delegates are part of the treatment.</p></article><article><span>LINTEL → SWARM</span><h2>Same method.<br>Different scheduling.</h2><p>Verify actual active worker overlap.</p></article></div><div class="recipe-rule">Repeat. Counterbalance. Include failures and overhead.</div>','refresh'),
 productbenchmark:s=>shell(s,'<div class="benchmark-new"><div class="benchmark-contract">'+icon('flask')+'<span>THE CURRENT KITCHEN HARNESS</span><h2>One brief.<br>Three treatments.</h2><p class="benchmark-treatments">Naked Copilot · Lintel · Lintel + Swarming</p></div><div class="benchmark-receipt"><span>MEASURE SEPARATELY</span><ul>'+[['clock','Time to live'],['check','Declared completion'],['layers','Requirement coverage'],['scales','Billed credits']].map(([i,t])=>'<li>'+icon(i)+'<span>'+t+'</span></li>').join('')+'</ul></div></div><div class="refresh-bottom"><p>Harness prepared locally.<br><strong class="accent">Comparison results + distribution pending.</strong></p>'+guide()+'</div>','refresh product-slide')
 };
};
