
window.LINTEL_TECHNICAL=({shell,icon,state,viewButton})=>{
const ref=(anchor,label='Open the technical reference')=>viewButton(label,'technical-reference.html#'+anchor,'Lintel · technical reference');
const kicker=t=>'<span class="t-k">'+t+'</span>';
const foot=(t,a='overview',label)=>'<div class="t-foot"><span>'+t+'</span>'+ref(a,label)+'</div>';
const wrap=(s,h,c='')=>shell(s,h,'technical '+c);
const line=(i,h,p)=>'<div class="t-line">'+icon(i)+'<div><h2>'+h+'</h2><p>'+p+'</p></div></div>';
const phaseNames=['SENSE','SCOPE','DEFINE','DISCOVER','PLAN','BUILD','REVIEW','SHIP','CAPTURE'];
const phases=[
 ['Route the request','Runtime · state/00-state.md','SENSE entry: intent, mode, role','Configured home · sessions/','Pack cache when resolver runs','SENSE appends the route; it does not implement the request.'],
 ['Agree the size and depth','Runtime · state/scope.md','Or jobs/&lt;id&gt;/scope.md when a job is active','Runtime · state/00-state.md','SCOPE entry + scope_path','Small work stays small. Ambiguous scope is resolved before planning.'],
 ['Make the design explicit','Repo · .claude/engineering/design-archive/','Design document when that archive exists','Otherwise · runtime/state/','Dated design + optional private lens notes','An agreed design is not automatically a committed design. Check its destination.'],
 ['Find the relevant knowledge','Runtime · state/discover-report-&lt;time&gt;.md','Sources, constraints, decisions and gaps','Runtime · state/00-state.md','DISCOVER entry points to the report','Read relevant knowledge; do not load the whole catalogue.'],
 ['Write a cold-executor handoff','Committed intent · plans/&lt;initiative&gt;/','plan.md · spec.md · prompt.md · work.json¹','Runtime · state/','Planner checkpoint · analyze report · phase entry','¹ work.json applies to mapped work. Spec Kit retains its original artifacts.'],
 ['Implement and verify a card','Project · task-defined paths','Code + tests + authoritative task status','Runtime · state/build-log.md','Verification details + BUILD phase entries','Preserve reviewed evidence in Git when it must survive a fresh clone.'],
 ['Challenge the result','Runtime · state/review-report-&lt;time&gt;.md','Findings, severity, coverage and verdict','Runtime · state/compliance-report-&lt;time&gt;.md','Conditional: when the pack defines gates','The verdict needs real evidence. A report filename proves neither execution nor quality.'],
 ['Deliver within authorization','Git / platform · selected delivery path','Commit / PR / demo artifacts as authorized','Runtime · state/00-state.md','SHIP result and delivery pointers','SHIP does not authorize deployment, publishing or a direct push to main.'],
 ['Keep what the next session needs','Committed knowledge · memory/ + decisions/','Lessons · working state · ADRs when warranted','Committed handoff · plans/&lt;initiative&gt;/prompt.md','Refreshed handoff + final runtime phase entry','Reviewed knowledge is curated. Optional exports require configured destinations.']
];
const clients=[
 {name:'Claude Code',entry:'.claude-plugin/plugin.json',native:'skills/ · agents/',detail:'Host plugin convention loads the bundle.',hook:'9 core hook registrations',hpath:'hooks/hooks.json',note:'Compatible host registration + a firing test still required.'},
 {name:'Copilot',entry:'.github/skills/li-*/SKILL.md',native:'.github/agents/*.agent.md',detail:'14 native workflows · 3 agent profiles',hook:'No Lintel hooks installed',hpath:'.github/lintel/ = portable source',note:'Repository kit: VS Code, CLI and cloud. Validate each surface.'},
 {name:'Codex / Cursor',entry:'.codex-plugin/plugin.json\n.cursor-plugin/plugin.json',native:'skills/ · agents/',detail:'Manifests point to the canonical bundle.',hook:'No Lintel hook registration',hpath:'Host-managed installed bundle',note:'Discovery, delegation and permissions need client-specific evidence.'},
 {name:'Gemini / OpenCode',entry:'gemini-extension.json → GEMINI.md\n.opencode/INSTALL.md',native:'Workflow files read as content',detail:'No native skill adapters declared on these routes.',hook:'No Lintel hook registration',hpath:'Extension bundle / reviewed checkout',note:'This describes Lintel’s integration, not every vendor capability.'},
 {name:'Droid / manual',entry:'Droid marketplace route\nOther clients: custom instructions',native:'Droid: declared native skills',detail:'Cline · Continue · Aider: best-effort content route.',hook:'No Lintel hook registration',hpath:'AGENT-INSTRUCTIONS.md + selected workflows',note:'Resolve the actual installed location in the host; no cache-path guesswork.'}
];
return {
techkit:s=>wrap(s,'<div class="t-toolbox"><div class="t-library">'+kicker('SOURCE LIBRARY · NOT AN AUTO-LOAD LIST')+'<div class="t-counts"><div><strong>127</strong><span>skills</span></div><div><strong>69</strong><span>agent roles</span></div><div><strong>33</strong><span>hook scripts</span></div></div><p>Reusable procedures. Bounded roles.<br>Executable reactions.</p></div><div class="t-working">'+icon('compass')+kicker('THIS TASK’S WORKING SET')+'<h2>One intent.<br>Relevant context.<br>Enough verification.</h2><span class="t-aside">Your context window is not a package manager.</span></div></div>'+foot('A separate 18-minute module · level 200','overview','Browse all inventories'),'t-kit'),
techskills:s=>wrap(s,'<div class="t-skill-loop">'+[['route','PLAN','Requirements → cards'],['terminal','BUILD','Cards → evidence'],['check','REVIEW','Evidence → verdict'],['bulb','CAPTURE','Corrections → knowledge']].map(([i,h,p])=>'<article>'+icon(i)+'<h2>'+h+'</h2><p>'+p+'</p></article>').join('')+'</div><div class="t-skill-depth">'+line('compass','Route & recover','cycle · scope · define · discover · ship · resume')+line('layers','Go deeper when needed','ta · da · sc · dh · tq · plan reviews')+line('flask','Specialise the output','frontend-* · generate-* · swarm')+'</div>'+foot('Starter set = editorial recommendation, not a usage ranking.','skills','Search all 127 skills'),'t-skills'),
techagents:s=>wrap(s,'<div class="t-agent-chain"><article>'+kicker('PREPARE')+icon('compass')+'<h2>Planner<br>Architect</h2><p>Intent · alternatives<br>Acceptance · dependencies</p></article><i>→</i><article>'+kicker('IMPLEMENT')+icon('terminal')+'<h2>build<br>+ scoped worker</h2><p>Declared files<br>Attributable changes</p></article><i>→</i><article>'+kicker('CHALLENGE')+icon('check')+'<h2>CodeReviewer<br>TestRunner</h2><p>SecurityAuditor when relevant<br>Findings + limitations</p></article></div><div class="t-coordinator">'+icon('git')+'<strong>Swarm: one coordinator</strong><span>One task map · isolated lanes · independent review · integration evidence</span></div>'+foot('No native delegation? Sequence the roles and label self-review.','agents','Search all 69 agents'),'t-agents'),
techstorage:s=>{const kit=state.techHome==='kit';return wrap(s,'<div class="t-storage-grid"><article>'+kicker('01 / INSTALLED SOURCE')+icon('layers')+'<h2>The reusable library</h2><code>skills/ · agents/ · '+(kit?'docs/':'hooks/')+'<br>lib/ · bin/ · scaffolding/</code><p>'+(kit?'Source: <b>.github/lintel/</b> · hooks excluded':'Plugin / bare-install source bundle')+'</p></article><article class="t-home">'+kicker('02 / CONFIGURATION HOME')+'<div class="t-tabs"><button data-tech-home="default" aria-pressed="'+!kit+'">Bare install</button><button data-tech-home="kit" aria-pressed="'+kit+'">Copilot kit</button></div><h2>'+(kit?'Local by default':'Personal by default')+'</h2><code>'+(kit?'.claude/runtime/lintel-home/':'~/.lintel/')+'</code><p>Explicit <b>LINTEL_HOME</b> overrides the default.</p></article><article class="t-durable">'+kicker('03 / PROJECT · COMMIT INTENTIONALLY')+icon('git')+'<h2>Knowledge that travels</h2><code>.claude/memory/<br>.claude/decisions/ · .claude/plans/</code><p>Plan · decision · lesson · handoff</p></article><article class="t-runtime">'+kicker('04 / PROJECT · GIT-IGNORED')+icon('clock')+'<h2>Local working state</h2><code>.claude/runtime/<br>state/ · sessions/ · jobs/ · audit/</code><p>Not carried by a fresh clone.</p></article></div>'+foot('v5 layout shown. Legacy paths and configured destinations are in the inventory.','artifacts','Inspect all output families'),'t-storage');},
techcycle:s=>{const n=state.techPhase??4,p=phases[n];return wrap(s,'<div class="t-phase-tabs" role="group" aria-label="Choose a cycle phase">'+phaseNames.map((x,i)=>'<button data-tech-phase="'+i+'" aria-pressed="'+(i===n)+'"><small>0'+(i+1)+'</small>'+x+'</button>').join('')+'</div><div class="t-phase-result" aria-live="polite"><div class="t-phase-purpose">'+kicker(phaseNames[n])+'<h2>'+p[0]+'</h2>'+icon(n===8?'bulb':n===4?'route':'file')+'</div><div class="t-phase-files"><div>'+kicker(p[1])+'<p>'+p[2]+'</p></div><div>'+kicker(p[3])+'<p>'+p[4]+'</p></div></div></div><div class="t-callout">'+p[5]+'</div>'+foot('Paths below .claude/ unless a different root is shown.','artifacts','Phase-by-phase inventory'),'t-cycle');},
techresume:s=>wrap(s,'<div class="t-resume-layout"><div class="t-resume-map"><div>'+kicker('SELECT THE INITIATIVE')+'<code>plans/todo.md<br>memory/working-state.md</code></div><b>↓</b><div class="t-map-focus">'+kicker('COMMITTED INDEX')+'<code>plans/&lt;initiative&gt;/work.json</code></div><b>↓</b><div>'+kicker('FOLLOW THE ORIGINAL ARTIFACTS')+'<code>spec · plan · tasks · prompt<br>+ swarm coordination when used</code></div></div><div class="t-resume-truth">'+icon('handoff')+'<h2>The next session<br>needs a return address.</h2><p>One map. Original task IDs.<br>Evidence before “done”.</p><div class="t-missing">Missing runtime ≠ missing intent.<br>Missing evidence ≠ verified work.</div></div></div>'+foot('Paths below .claude/. Spec Kit keeps specs/… artifacts. Ambiguous map? Ask.','recovery','Read the recovery contract'),'t-resume'),
techhooks:s=>{const opt=state.techHooks==='optional';const rows=opt?[['15','ENGINEERING','Architecture · data · security · deployment · testing','Advisory scripts; several inspect the existing file before an edit.'],['6','CROSS-CUTTING','Context · design · freeze · merge · production · DOM text','Not activated by the core manifest.'],['3','JOB LIFECYCLE','job-begin · job-end · job-stale-warn','Explicit helper contracts; begin/end can mutate files.']]:[['1','SessionStart','session-digest','Adds compact startup context.'],['2','UserPromptSubmit','cycle-position-inject · no-customer-data-in-message','Context reminder + prompt warning.'],['4','PreToolUse','Edit warning · git secret/data blockers · main-push warning','Only secret-scan-block and customer-data-block intentionally deny.'],['1','PostToolUse','memory-budget-warn','Warns about budgets; does not rewrite memory.'],['1','Stop','cycle-incomplete-warn','Emits advice; no forced continuation or checkpoint.']];return wrap(s,'<div class="t-hook-heading"><div class="t-tabs"><button data-tech-hooks="core" aria-pressed="'+!opt+'">9 registered core</button><button data-tech-hooks="optional" aria-pressed="'+opt+'">24 optional / manual</button></div><span>Registration: Claude-compatible manifest</span></div><div class="t-hook-list '+(opt?'is-optional':'')+'">'+rows.map(([n,h,p,d])=>'<div><b>'+n+'</b><section><h2>'+h+'</h2><p>'+p+'</p></section><small>'+d+'</small></div>').join('')+'</div>'+foot('WARN is not BLOCK. A script on disk is not a firing hook.','hooks','Inspect all 33 hook scripts'),'t-hooks');},
techclients:s=>{const n=state.techClient??1,c=clients[n];return wrap(s,'<div class="t-tabs t-client-tabs">'+clients.map((x,i)=>'<button data-tech-client="'+i+'" aria-pressed="'+(i===n)+'">'+x.name+'</button>').join('')+'</div><div class="t-client-content" aria-live="polite"><article>'+kicker('DISCOVERY / ENTRY')+'<h2>'+c.name+'</h2><pre>'+c.entry+'</pre><code>'+c.native+'</code><p>'+c.detail+'</p></article><article>'+kicker('LINTEL EXECUTION BOUNDARY')+icon('lock')+'<h2>'+c.hook+'</h2><code>'+c.hpath+'</code><p>'+c.note+'</p></article></div><div class="t-client-common">'+icon('folder')+'<b>Shared project knowledge</b><code>.claude/memory/ · decisions/ · plans/</code></div>'+foot('Shipped Lintel integration at this revision; not a limit on vendor capabilities.','clients','Full client and path matrix'),'t-clients');},
techpacks:s=>wrap(s,'<div class="t-pack-path"><article>'+kicker('OPERATOR')+icon('person')+'<h2>Profile</h2><code>profile.yaml</code><p>Role · mode · context</p></article><b>→</b><article>'+kicker('ORGANISATION')+icon('building')+'<h2>Active pack</h2><code>packs/active-pack</code><p>Standards · vocabulary<br>Workflow expectations</p></article><b>→</b><article>'+kicker('PROJECT')+icon('file')+'<h2>This task</h2><code>Resolved relevant fields</code><p>Specific acceptance<br>Useful evidence</p></article></div><div class="t-policy-rail">'+icon('lock')+'<strong>Platform policy + permissions + CI</strong><span>Configured and verified separately.</span></div>'+foot('Neutral _default pack · explicit composition · no credentials in packs.','packs','Pack resolution and trust'),'t-packs'),
techmaintenance:s=>wrap(s,'<div class="t-maintain">'+[['book','UPDATE','One fact. One current home.','Edit the existing knowledge.'],['route','SUPERSEDE','Keep the reason visible.','Link the newer lesson or ADR.'],['archive','ARCHIVE','Give temporary work a lifetime.','Review retention before disposal.']].map(([i,k,h,p])=>'<article>'+icon(i)+kicker(k)+'<h2>'+h+'</h2><p>'+p+'</p></article>').join('')+'</div><div class="t-maintain-bottom"><div><b>Committed knowledge</b><span>Curate it. Review it. Keep it useful.</span></div><div><b>Ignored runtime</b><span>Bound it. Preserve needed evidence.</span></div></div>'+foot('Warnings + manual maintenance workflows. No universal automatic garbage collector.','maintenance','What maintenance actually does'),'t-maintenance'),
techproof:s=>wrap(s,'<div class="t-proof-grid">'+[['01','DISCOVERY','Which copy actually loaded?','file'],['02','REAL TASK','Where is the acceptance evidence?','check'],['03','COLD RESTART','Can a fresh session find the next card?','handoff'],['04','NEGATIVE CASE','What happens when a dependency fails?','flask']].map(([n,k,h,i])=>'<article><span>'+n+'</span>'+icon(i)+kicker(k)+'<h2>'+h+'</h2></article>').join('')+'</div><div class="t-proof-end"><p>Record the revision. Test the client.<br><b>Measure the overhead as well as the benefit.</b></p><div>'+ref('rollout','Take the pilot checklist')+'<a class="action" href="#three-hours">Back to the main story ↗</a></div></div>','t-proof')
};
};
